"""
Slides 09-11 -- guild -> nectar theft -> network -> within-guild projection ->
niches -> the guild as a community.

One scene and ONE camera for frames 09a, 09b, 10, 11a and 11b: every node sits
at the same place on every slide, so stepping through them reads as one
picture being built up and then redrawn, not as five pictures.

  09a  the fly and its guild of long-tubed plants
  09b  + Babiana thunbergii, a sunbird flower the fly robs (with the photo)
  10   + the other pollinators and plants: the network around the pair
  11a  the links between guilds recede; pollinators that share plants are
       joined by arcs (the one-guild projection)
  11b  the plant row becomes a resource axis with one utilisation curve per
       pollinator
  11c  the same guild on a circle, with competition coefficients and selection
       gradients for every pair (its own layout)

What is real and what is schematic
----------------------------------
Real:
  * the focal pair, Moegistorhynchus longirostris and Lapeirousia anceps;
  * the six guild plants in 09a/09b and their order by tube length (Goldblatt
    & Manning 2000, Table 2); the guild has at least 20 members (Manning &
    Goldblatt 1997);
  * the fly takes nectar from Babiana thunbergii, a sunbird flower, almost
    never touching anthers or stigma (Pauw et al. 2009, Fig. 5: the photo);
  * in frame 10, the two tabanids that share the guild and the plants they
    share with the fly: Philoliche gulosa (Tritonia crispa, Lapeirousia
    fabricii, L. anceps) and P. rostrata (Ixia paniculata) (Goldblatt &
    Manning 2000, Table 2), and the malachite sunbird on B. thunbergii.
Guild sizes quoted on frame 10: "six or seven fly species" (Goldblatt &
Manning 2000, text); about 35 plant species with pollination records in their
Table 2 for this guild (a scripted count of the table's text); at least 20 for
M. longirostris (Manning & Goldblatt 1997).
Schematic: every other node and link, generated by one trait-matching rule (a
pollinator visits plants whose rank on the trait axis lies within its range),
which is what lets the bipartite links turn into utilisation curves in 11b.

`frame_pair` (the to-scale portrait of the fly and flower) is kept as an
extra, s09x_pair_portrait; it is not part of the sequence.
"""
import numpy as np

from glyphs import *  # noqa: F403
from matplotlib.patches import Rectangle
from semstyle import *  # noqa: F403

# ------------------------------------------------------------------ scene --
Y_TOP, Y_BOT = 190.0, 0.0
NP = 14
PLANT_X = 70 + 80.0 * np.arange(NP)                 # trait rank -> x
# pollinators: x position, centre and half-width of visited range (plant rank)
# pollinators: centre and half-width of the visited range, in plant ranks; each
# pollinator is drawn directly above the centre of its own range
_RANGES = [
    (0.5, 1.0),
    (1.6, 1.5),
    (3.0, 1.1),      # the sunbird that pollinates B. thunbergii
    (4.5, 1.6),
    (5.2, 1.3),
    (6.0, 1.1),      # Philoliche rostrata: also Ixia paniculata (11)
    (8.0, 2.1),      # Philoliche gulosa: plants 6..10
    (10.3, 3.2),     # M. longirostris: plants 8..13  (index FLY)
    (12.2, 1.2),
]
POLL = [(70 + 80.0 * c, c, h) for c, h in _RANGES]
FLY, FLOWER, BABIANA, SUNBIRD = 7, 10, 3, 2
ROSTRATA, GULOSA = 5, 6
GUILD_NAMES = {8: "Tritonia\ncrispa", 9: "Lapeirousia\nfabricii",
               11: "Ixia\npaniculata", 12: "Geissorhiza\nexscapa",
               13: "Gladiolus\nangustus"}
PHOTO = HERE.parent / "assets" / "pauw2009_fig5_babiana.png"
CAM = (590, 116, 1180)      # one camera for 09a, 09b, 10, 11a, 11b
POLL_X = np.array([p[0] for p in POLL])


def adjacency():
    A = np.zeros((len(POLL), NP), int)
    for i, (_, c, h) in enumerate(POLL):
        for j in range(NP):
            if abs(j - c) <= h:
                A[i, j] = 1
    A[FLY, :8] = 0                      # the guild is the long-tubed plants
    A[ROSTRATA, 11] = 1                 # P. rostrata on Ixia paniculata
    return A


A = adjacency()
TOP = [(x, Y_TOP) for x in POLL_X]
BOT = [(x, Y_BOT) for x in PLANT_X]


def draw_icons(pen):
    """Small fly above its node, small flower below its node."""
    fx, fy = TOP[FLY]
    lx, ly = BOT[FLOWER]
    fly(pen, fx - 9, fy + 46, s=17, proboscis=26)
    flower(pen, lx, ly - 26, s=22, tube=36)


# ------------------------------------------------------------------ frames --
MM = 2.4                                   # scene units per millimetre in 09a


def frame_pair():
    fig = figure_px(FULL)
    ax, k = camera_axes(fig, 822, 100, 600)
    pen = Pen(ax, k)
    p, q = TOP[FLY], BOT[FLOWER]
    recip(pen, p, q, gap=17, rad=0.30, px=2.2, colors=(INDIGO, OCHRE), head=9)
    species(pen, *p, 12, "A")
    species(pen, *q, 12, "B")
    off = 20
    ax.text(p[0] + off, p[1], "Moegistorhynchus longirostris", ha="left",
            va="center", fontsize=fs(FS_SMALL), style="italic", color=INDIGO)
    ax.text(q[0] + off, q[1], "Lapeirousia anceps", ha="left", va="center",
            fontsize=fs(FS_SMALL), style="italic", color=OCHRE)
    mid = ((p[0] + q[0]) / 2, (p[1] + q[1]) / 2)
    ax.text(mid[0] - 36, mid[1], "selects on\ntube depth", ha="right",
            va="center", fontsize=fs(FS_SMALL), color=INDIGO, linespacing=1.15)
    ax.text(mid[0] + 40, mid[1], "selects on\nproboscis length", ha="left",
            va="center", fontsize=fs(FS_SMALL), color=OCHRE, linespacing=1.15)

    # the portrait, to scale: body 16 mm, proboscis 65 mm, tube 60 mm
    xP, yH = 652, 204
    L_prob, L_tube = 65 * MM, 60 * MM
    mouth, base = flower(pen, xP, yH - 30, s=10 * MM * 1.15, tube=L_tube)
    top, tip = fly(pen, xP, yH, s=10 * MM, proboscis=L_prob, z=9)
    dim_bracket(pen, xP - 22, tip[1], top[1])
    ax.text(xP - 29, (top[1] + tip[1]) / 2 + 8, r"proboscis $x$", ha="right",
            va="center", fontsize=fs(FS_SMALL), color=INK)
    dim_bracket(pen, xP + 22, base[1], mouth[1] - 16)
    ax.text(xP + 29, (mouth[1] + base[1]) / 2 - 20, r"tube $y$", ha="left",
            va="center", fontsize=fs(FS_SMALL), color=INK)
    ax.plot([xP + 44, p[0] - 16], [yH + 4, p[1]], color=FAINT, lw=pen.lw(1.2),
            ls=(0, (1, 2.4)), zorder=1)
    ax.plot([xP + 8, q[0] - 16], [base[1] - 4, q[1]], color=FAINT,
            lw=pen.lw(1.2), ls=(0, (1, 2.4)), zorder=1)
    cv = canvas(fig)
    status(cv, "schematic", "drawn to scale from Pauw et al. 2009: body 16 mm, proboscis 65 mm, tube 60 mm")
    save(fig, "s09x_pair_portrait")


def frame_guild(babiana=True):
    fig = figure_px(FULL)
    ax, k = camera_axes(fig, *CAM)
    pen = Pen(ax, k)
    p = TOP[FLY]
    guild = [j for j in range(NP) if A[FLY, j]]
    for j in guild:
        link(pen, p, BOT[j], px=1.6, color=FAINT)
    link(pen, p, BOT[FLOWER], px=3.6, color=INK, z=3)
    species(pen, *p, 12, "A")
    for j in guild:
        species(pen, *BOT[j], 11, "B")
    draw_icons(pen)
    ax.text(p[0] + 22, p[1] + 4, "Moegistorhynchus longirostris", ha="left",
            va="center", fontsize=fs(FS_SMALL), style="italic", color=INDIGO)
    for j, name in GUILD_NAMES.items():
        ax.text(BOT[j][0], Y_BOT - 20, name, ha="center", va="top",
                fontsize=fs(FS_TINY), style="italic", color=OCHRE,
                linespacing=1.12)
    lx = BOT[FLOWER][0]
    ax.text(lx, Y_BOT - 74, "Lapeirousia\nanceps", ha="center", va="top",
            fontsize=fs(FS_TINY), style="italic", color=OCHRE, linespacing=1.12,
            fontweight="bold")
    gx = [BOT[j][0] for j in guild]
    yb = Y_BOT - 126
    ax.plot([gx[0] - 30, gx[-1] + 30], [yb, yb], color=MUTED, lw=pen.lw(1.3))
    for xx in (gx[0] - 30, gx[-1] + 30):
        ax.plot([xx, xx], [yb, yb + 7], color=MUTED, lw=pen.lw(1.3))
    ax.text(gx[0] - 44, yb + 2, "its guild: at least 20 long-tubed species; tubes lengthen to the right",
            ha="right", va="center", fontsize=fs(FS_SMALL), color=INK)
    cv = canvas(fig)
    src = "guild: Manning & Goldblatt 1997; Goldblatt & Manning 2000"
    if babiana:
        link(pen, p, BOT[BABIANA], px=1.8, color=MUTED, ls=(0, (3, 2.4)))
        species(pen, *BOT[BABIANA], 11, "B", "open")
        bx = BOT[BABIANA][0]
        ax.text(bx + 22, Y_BOT + 2, "Babiana thunbergii", ha="left", va="center",
                fontsize=fs(FS_SMALL), style="italic", color=OCHRE)
        ax.text(bx + 22, Y_BOT - 22, "a sunbird flower: nectar taken,\nanthers and stigma seldom touched",
                ha="left", va="top", fontsize=fs(FS_TINY), color=MUTED, linespacing=1.15)
        src += "; Pauw et al. 2009"
        if PHOTO.exists():
            import matplotlib.image as mpimg
            img = mpimg.imread(PHOTO)
            h_px = 262
            w_px = h_px * img.shape[1] / img.shape[0]
            x0, y0 = 138, 276
            cv.imshow(img, extent=[x0, x0 + w_px, y0, y0 + h_px], zorder=3,
                      aspect="auto", interpolation="lanczos")
            cv.set_xlim(0, fig._px[0])
            cv.set_ylim(0, fig._px[1])
            cv.add_patch(Rectangle((x0, y0), w_px, h_px, facecolor="none",
                                   edgecolor=INK, linewidth=lw(1.2), zorder=4))
            bpx = ((bx - (CAM[0] - CAM[2] / 2)) * k,
                   (Y_BOT - (CAM[1] - fig._px[1] / k / 2)) * k)
            cv.plot([x0 + w_px * 0.75, bpx[0]], [y0, bpx[1] + 15], color=MUTED,
                    lw=lw(1.2), zorder=2)
            cv.text(x0 + w_px + 12, y0 + h_px - 4, "the same fly on\nB. thunbergii",
                    ha="left", va="top", fontsize=fs(FS_TINY), color=MUTED,
                    linespacing=1.15)
            src += "  \u00B7  photo: Pauw et al. 2009, Evolution 63:268, Fig. 5"
    status(cv, "schematic", src)
    save(fig, "s09b_guild" if babiana else "s09a_guild")


def _rows_labels(ax, plants=True, counts=False):
    ax.text(18, Y_TOP + 76, "pollinators", ha="left", va="bottom",
            fontsize=fs(FS_LABEL), color=INDIGO, fontweight="bold")
    if counts:
        ax.text(138, Y_TOP + 78, "six or seven long-proboscid flies in this guild, and other visitors",
                ha="left", va="bottom", fontsize=fs(FS_TINY), color=MUTED)
    if plants:
        ax.text(18, Y_BOT - 70, "plants", ha="left", va="top",
                fontsize=fs(FS_LABEL), color=OCHRE, fontweight="bold")
        if counts:
            ax.text(92, Y_BOT - 72, "about 35 species with records; this fly alone visits at least 20,\nand takes nectar from others outside the guild",
                    ha="left", va="top", fontsize=fs(FS_TINY), color=MUTED,
                    linespacing=1.2)


def frame_network():
    fig = figure_px(FULL)
    ax, k = camera_axes(fig, *CAM)
    pen = Pen(ax, k)
    for i in range(len(POLL)):
        for j in range(NP):
            if A[i, j]:
                link(pen, TOP[i], BOT[j], px=1.5, color=FAINT)
    link(pen, TOP[FLY], BOT[BABIANA], px=1.6, color=MUTED, ls=(0, (3, 2.4)))
    link(pen, TOP[FLY], BOT[FLOWER], px=3.6, color=INK, z=3)
    for p in TOP:
        species(pen, *p, 12, "A")
    for q in BOT:
        species(pen, *q, 11, "B")
    draw_icons(pen)
    _rows_labels(ax, counts=True)
    ya = Y_BOT - 132
    arrow(pen, (410, ya), (760, ya), px=1.4, color=MUTED, head=9)
    ax.text(400, ya, "shorter tubes, shorter mouthparts", ha="right", va="center",
            fontsize=fs(FS_SMALL), color=MUTED)
    ax.text(770, ya, "longer", ha="left", va="center", fontsize=fs(FS_SMALL),
            color=MUTED)
    ax.text(TOP[FLY][0] + 44, Y_TOP + 64, "the pair we started with", ha="left",
            va="center", fontsize=fs(FS_SMALL), color=INK)
    for i, name in [(GULOSA, "Philoliche\ngulosa"), (ROSTRATA, "Philoliche\nrostrata"),
                    (SUNBIRD, "malachite\nsunbird")]:
        ax.text(TOP[i][0], Y_TOP + 20, name, ha="center", va="bottom",
                fontsize=fs(FS_TINY), style="italic", color=INDIGO,
                linespacing=1.12)
    ax.text(BOT[BABIANA][0], Y_BOT - 20, "Babiana\nthunbergii", ha="center",
            va="top", fontsize=fs(FS_TINY), style="italic", color=OCHRE,
            linespacing=1.12)
    cv = canvas(fig)
    status(cv, "schematic", "the Moegistorhynchus\u2013Philoliche guild: Goldblatt & Manning 2000 (Table 2); Manning & Goldblatt 1997; Pauw et al. 2009")
    save(fig, "s10_network")


def shared_partners():
    n = len(POLL)
    W = np.zeros((n, n), int)
    for i in range(n):
        for j in range(i + 1, n):
            W[i, j] = W[j, i] = int((A[i] & A[j]).sum())
    return W


def _arcs(pen, W, color=INDIGO):
    n = len(POLL)
    for i in range(n):
        for j in range(i + 1, n):
            if W[i, j]:
                d = (POLL_X[j] - POLL_X[i])
                arc(pen, TOP[i], TOP[j], bulge=(0.17 + 0.00012 * d),
                    px=1.2 + 1.3 * W[i, j], color=color, z=3)


def frame_within():
    fig = figure_px(FULL)
    ax, k = camera_axes(fig, *CAM)
    pen = Pen(ax, k)
    W = shared_partners()
    for i in range(len(POLL)):
        for j in range(NP):
            if A[i, j]:
                link(pen, TOP[i], BOT[j], px=1.3, color=LINE)
    _arcs(pen, W)
    for p in TOP:
        species(pen, *p, 12, "A")
    for q in BOT:
        species(pen, *q, 11, "B", "ghost")
    _rows_labels(ax, plants=False)
    ax.text(18, Y_BOT - 34, "plants = shared resources", ha="left", va="top",
            fontsize=fs(FS_LABEL), color=MUTED, fontweight="bold")
    ax.text(590, Y_TOP + 188, "pollinators that share plants compete",
            ha="center", va="center", fontsize=fs(FS_LABEL), color=INK)
    ax.text(590, Y_TOP + 160, "arc width = number of shared partners",
            ha="center", va="center", fontsize=fs(FS_SMALL), color=MUTED)
    cv = canvas(fig)
    status(cv, "schematic", "one-guild projection of the network in slide 10")
    save(fig, "s11a_within")


def frame_niche():
    fig = figure_px(FULL)
    ax, k = camera_axes(fig, *CAM)
    pen = Pen(ax, k)
    W = shared_partners()
    _arcs(pen, W)
    # the plant row becomes a resource axis
    arrow(pen, (20, Y_BOT), (1165, Y_BOT), px=1.6, color=FAINT, head=10)
    xs = np.linspace(22, 1150, 900)
    curves, peaks = [], []
    for i, (x, c, h) in enumerate(POLL):
        mu = 70 + 80.0 * c
        sd = 80.0 * h / 1.9
        height = min(118.0, 5200.0 / sd)        # equal total use: area fixed
        curves.append(Y_BOT + height * np.exp(-0.5 * ((xs - mu) / sd) ** 2))
        peaks.append((mu, Y_BOT + height))
    curves = np.array(curves)
    order = np.argsort([pk[0] for pk in peaks])
    for a_, b_ in zip(order[:-1], order[1:]):
        ov = np.minimum(curves[a_], curves[b_])
        ax.fill_between(xs, Y_BOT, ov, where=ov > Y_BOT + 1.5, facecolor=INDIGO_T,
                        edgecolor=INDIGO, hatch="////", linewidth=0, zorder=2)
    for i, (x, c, h) in enumerate(POLL):
        ax.plot(xs, curves[i], color=INDIGO, lw=pen.lw(2.2), zorder=3)
        ax.plot([x, peaks[i][0]], [Y_TOP - 13, peaks[i][1] + 2], color=FAINT,
                lw=pen.lw(1.2), ls=(0, (2, 2)), zorder=2)
    for p in TOP:
        species(pen, *p, 12, "A")
    _rows_labels(ax, plants=False)
    ax.text(1160, Y_BOT - 14, "resource axis", ha="right", va="top",
            fontsize=fs(FS_LABEL), color=MUTED, fontweight="bold")
    ax.text(18, Y_BOT - 14, "curves: what each species uses", ha="left", va="top",
            fontsize=fs(FS_SMALL), color=MUTED)
    ax.text(590, Y_TOP + 188, "overlap in resource use sets competition",
            ha="center", va="center", fontsize=fs(FS_LABEL), color=INK)
    ax.text(590, Y_TOP + 160, "hatched = overlap between neighbours on the axis",
            ha="center", va="center", fontsize=fs(FS_SMALL), color=MUTED)
    cv = canvas(fig)
    status(cv, "schematic", "the set-up of the diffuse-coevolution model, Week et al. 2021")
    save(fig, "s11b_niche")


def pair_quantities():
    """Competition coefficients and selection gradients for every pair of the
    example guild, from Week et al. (2021), Eq. 35 (SM.109-110), with equal
    abundances, niche use and competition strength (c = U = N = 1):

        b_ij     = 1 / (w_i^2 + w_j^2)        w_i: width of i's utilisation curve
        alpha_ij = sqrt(b_ij / 2 pi) exp(-b_ij d_ij^2 / 2),   d_ij = x_i - x_j
        beta_ij  = b_ij d_ij alpha_ij
        gamma_ij = b_ij (1 - b_ij d_ij^2) alpha_ij
    """
    mu = np.array([70 + 80.0 * c for _, c, _ in POLL])
    sd = np.array([80.0 * h / 1.9 for _, _, h in POLL])
    d = mu[:, None] - mu[None, :]
    b = 1.0 / (sd[:, None] ** 2 + sd[None, :] ** 2)
    alpha = np.sqrt(b / (2 * np.pi)) * np.exp(-b * d ** 2 / 2)
    return alpha, b * d * alpha, b * (1 - b * d ** 2) * alpha


def theory_curves(b, n=200):
    """With one niche width for everyone (one b), every pair sits on a curve
    set only by how far apart the two species are (Eq. 35 / SM.110).  Writing
    s = sqrt(b) |x_i - x_j|:
        alpha = sqrt(b / 2 pi) exp(-s^2 / 2)
        |beta| = sqrt(b) s alpha
        gamma  = b (1 - s^2) alpha
    Returns alpha, |beta|, gamma along s from 0 (same niche) to far apart."""
    s = np.linspace(0, 4.5, n)
    alpha = np.sqrt(b / (2 * np.pi)) * np.exp(-s ** 2 / 2)
    return alpha, np.sqrt(b) * s * alpha, b * (1 - s ** 2) * alpha


def _niche_pair(fig, cv, pen, xc, y0, s, breadth, push):
    """Two utilisation curves a scaled distance s apart, with what competition
    selects for.  `breadth`: selection on each species' variance (its niche
    breadth), drawn as one vertical arrow centred on each curve, down for less
    variance (-1) and up for more (+1).  `push`: how hard the two means are
    pushed apart (0 to 1), drawn as grey horizontal arrows above the peaks."""
    w, h = 112, 78
    ax = px_axes(fig, xc - w / 2, y0, w, h)
    x = np.linspace(-4.2, 4.2, 300)
    sd = 1 / np.sqrt(2)                       # so that the scaled distance is s
    f1 = np.exp(-0.5 * ((x + s / 2) / sd) ** 2)
    f2 = np.exp(-0.5 * ((x - s / 2) / sd) ** 2)
    ax.fill_between(x, 0, np.minimum(f1, f2), facecolor=INDIGO_T, edgecolor=INDIGO,
                    hatch="////", linewidth=0, zorder=1)
    ax.plot(x, f1, color=INDIGO, lw=lw(2.4), zorder=3)
    ax.plot(x, f2, color=INDIGO, lw=lw(2.4), ls=(0, (3.2, 1.6)), zorder=3)
    ax.set_xlim(-4.2, 4.2)
    ax.set_ylim(0, 1.62)
    blank(ax)
    ax.spines["bottom"].set_visible(True)
    kw = dict(arrowstyle="-|>,head_length=0.62,head_width=0.34", color=INK, lw=lw(2.6),
              shrinkA=0, shrinkB=0)
    if breadth:                                # one arrow per species, on its own curve
        off = max(s / 2, 0.52)                 # keep the two apart when the curves coincide
        lo, hi = 0.20, 0.78
        for c in (-off, off):
            a_, b_ = (hi, lo) if breadth < 0 else (lo, hi)
            ax.annotate("", xy=(c, b_), xytext=(c, a_), arrowprops=kw, zorder=6)
    if push > 0:                               # the two means pushed apart
        kw2 = dict(kw, color=MUTED, lw=lw(2.0))
        ax.annotate("", xy=(-s / 2 - 1.3 * push, 1.36), xytext=(-s / 2, 1.36), arrowprops=kw2,
                    zorder=5)
        ax.annotate("", xy=(s / 2 + 1.3 * push, 1.36), xytext=(s / 2, 1.36), arrowprops=kw2,
                    zorder=5)
    return ax


def frame_circle():
    """Left: the guild as a community; every link carries a competition
    coefficient and two selection gradients (Week et al. 2021, Eq. 35).
    Right: those gradients against competition for every pair (dots) with the
    one-width curve (grey), and under the axis what increasing competition
    looks like as niche overlap: far apart, nothing; partly overlapping, each
    is pushed away and a narrower niche pays (gamma < 0); nearly coincident,
    there is nowhere to go and a broader niche pays (gamma > 0).  The sign
    change is at a scaled distance of one, alpha = e^(-1/2) of its maximum."""
    fig = figure_px(FULL)
    cv = canvas(fig)
    pen = Pen(cv)
    n = len(POLL)
    W = shared_partners()
    alpha, beta, gamma = pair_quantities()
    off = ~np.eye(n, dtype=bool)
    amax = alpha[off].max()

    # ---- the same network, nodes on a circle ---------------------------------
    c0, R = (220, 318), 132
    ang = np.radians(90 - np.arange(n) * 360.0 / n)
    pts = [(c0[0] + R * np.cos(a), c0[1] + R * np.sin(a)) for a in ang]
    for i in range(n):
        for j in range(i + 1, n):
            if W[i, j]:
                hot = {i, j} == {GULOSA, FLY}
                link(pen, pts[i], pts[j], px=1.2 + 6.0 * alpha[i, j] / amax,
                     color=INK if hot else INDIGO, z=3 if hot else 2,
                     alpha=1.0 if hot else 0.75)
    for p in pts:
        species(pen, *p, 13, "A")
    cv.text(40, 520, "The same guild, as a community", ha="left", va="baseline",
            fontsize=fs(FS_LABEL), fontweight="bold")
    cv.text(40, 495, "width of a link: how strongly the two compete", ha="left",
            va="baseline", fontsize=fs(FS_TINY), color=MUTED)
    mid = ((pts[GULOSA][0] + pts[FLY][0]) / 2, (pts[GULOSA][1] + pts[FLY][1]) / 2)
    cv.plot([mid[0], 36], [mid[1], 148], color=MUTED, lw=lw(1.2), zorder=1)
    cv.text(40, 130, "each link, three numbers", ha="left", va="center",
            fontsize=fs(FS_SMALL), fontweight="bold")
    for y, sym, line in [(102, r"$\alpha$", "competition"),
                         (76, r"$\beta$", "selection on the mean trait"),
                         (50, r"$\gamma$", "selection on its variance: niche breadth")]:
        cv.text(40, y, sym, ha="left", va="center", fontsize=fs(FS_SMALL), color=INDIGO)
        cv.text(72, y, line, ha="left", va="center", fontsize=fs(FS_TINY), color=MUTED)

    # ---- selection against competition, and what it looks like as overlap ---------
    X0, WAX = 640, 470
    cv.text(X0 - 100, 520, "More overlap, more competition: what it selects for",
            ha="left", va="baseline", fontsize=fs(FS_LABEL), fontweight="bold")
    iu = np.triu_indices(n, 1)
    a_ = alpha[iu] / amax
    mu = np.array([70 + 80.0 * c for _, c, _ in POLL])
    sd = np.array([80.0 * h / 1.9 for _, _, h in POLL])
    b_typ = float(np.median((1.0 / (sd[:, None] ** 2 + sd[None, :] ** 2))[iu]))
    ta, tb, tg = theory_curves(b_typ)
    bmax, gmax = np.abs(beta[off]).max(), np.abs(gamma[off]).max()
    a_crit = np.exp(-0.5)                       # where gamma changes sign (s = 1)
    rs = (float(np.corrcoef(np.r_[a_, a_], np.r_[beta[iu], -beta[iu]])[0, 1]),
          float(np.corrcoef(a_, np.abs(beta[iu]))[0, 1]),
          float(np.corrcoef(a_, gamma[iu])[0, 1]))
    print("  [check] corr(alpha, beta) = %.2f, corr(alpha, |beta|) = %.2f, corr(alpha, gamma) = %.2f" % rs)
    assert abs(rs[0]) < 1e-9 and rs[1] > 0.2
    k0 = int(np.argmin(np.abs(ta / ta.max() - a_crit)))
    assert abs(tg[k0]) < 0.03 * np.abs(tg).max() and tg[0] > 0 and tg.min() < 0
    panels = [(388, 92, np.abs(beta[iu]) / bmax, tb / bmax, r"$|\beta|$",
               "push on the mean"),
              (250, 116, gamma[iu] / gmax, tg / gmax, r"$\gamma$", "selection on breadth")]
    for y0, hh, yv, tc, sym, words in panels:
        ax = px_axes(fig, X0, y0, WAX, hh)
        ax.axhline(0, color=LINE, lw=lw(1.2), zorder=1)
        ax.axvline(a_crit, color=FAINT, lw=lw(1.2), ls=(0, (2, 2)), zorder=1)
        ax.plot(ta / ta.max(), tc, color=MUTED, lw=lw(2.0), zorder=2)
        ax.plot(a_, yv, ls="none", marker="o", ms=6.5, mfc=INDIGO, mec=PAPER, mew=lw(0.9),
                zorder=3, alpha=0.9)
        ax.set_xlim(-0.03, 1.05)
        ax.set_ylim(min(-0.12, tc.min() - 0.12, yv.min() - 0.1), max(1.1, tc.max() + 0.1))
        ax.set_xticks([])
        ax.set_yticks([0])
        cv.text(X0 - 14, y0 + hh / 2 + 12, sym, ha="right", va="center",
                fontsize=fs(FS_LABEL), color=INDIGO)
        cv.text(X0 + 10, y0 + hh - 10, words, ha="left", va="top", fontsize=fs(FS_TINY),
                color=MUTED)
        if sym.endswith("gamma$"):
            ax.text(1.03, 0.45 * ax.get_ylim()[1], "broader", ha="right", va="center",
                    fontsize=fs(FS_TINY), color=INK)
            ax.text(0.30, 0.62 * ax.get_ylim()[0], "narrower", ha="center", va="center",
                    fontsize=fs(FS_TINY), color=INK)
    # the axis they share, drawn as niche overlap
    # the shared axis, named at its left end; each cartoon sits exactly under its
    # value of alpha, joined to the axis by a marker and a straight guide
    arrow(pen, (X0, 224), (X0 + WAX, 224), px=1.6, color=MUTED, head=9)
    cv.text(X0 - 12, 224, "competition $\\alpha$", ha="right", va="center",
            fontsize=fs(FS_SMALL))
    to_x = lambda a: X0 + WAX * (a + 0.03) / 1.08
    for s_, breadth, push, line in [(3.6, 0, 0.0, "apart:\nno effect"),
                                    (1.35, -1, 1.0, "overlap: pushed apart,\nless variance pays"),
                                    (0.35, 1, 0.0, "same niche: nowhere to go,\nmore variance pays")]:
        a_here = float(np.exp(-s_ ** 2 / 2))
        xc = to_x(a_here)
        _niche_pair(fig, cv, pen, xc, 112, s_, breadth, push)
        cv.plot([xc], [224], marker="o", ms=7, mfc=INK, mec=PAPER, mew=lw(1.2), zorder=6)
        cv.plot([xc, xc], [218, 194], color=MUTED, lw=lw(1.2), ls=(0, (1.5, 2)), zorder=2)
        for y0, hh, *_ in panels:                      # the same value, up through both panels
            cv.plot([xc, xc], [y0, y0 + hh], color=FAINT, lw=lw(1.0), ls=(0, (1.5, 2)), zorder=1)
        cv.text(xc, 100, line, ha="center", va="top", fontsize=fs(FS_TINY), color=INK,
                linespacing=1.2)

    # ---- the approximation behind the curves: many species, a dense web ----------------
    rng = np.random.default_rng(4)
    cd, Rd, nd = (470, 392), 50, 34
    th = np.linspace(0, 2 * np.pi, nd, endpoint=False) + 0.1
    pd_ = np.c_[cd[0] + Rd * np.cos(th), cd[1] + Rd * np.sin(th)]
    for _ in range(150):
        i, j = rng.choice(nd, 2, replace=False)
        cv.plot([pd_[i, 0], pd_[j, 0]], [pd_[i, 1], pd_[j, 1]], color=INDIGO, lw=lw(0.5),
                alpha=0.35, zorder=2)
    cv.plot(pd_[:, 0], pd_[:, 1], ls="none", marker="o", ms=4.6, mfc=INDIGO, mec=PAPER,
            mew=lw(0.5), zorder=3)
    arrow(pen, (366, 372), (410, 384), px=2.2, color=NAVY, head=10)
    cv.text(cd[0], 324, "high-richness approximation", ha="center", va="center",
            fontsize=fs(FS_TINY), fontweight="bold", color=NAVY)
    cv.text(cd[0], 296, "many species, a dense web:\nfollow the statistics of\nthe links, not each link",
            ha="center", va="top", fontsize=fs(FS_TINY), color=MUTED, linespacing=1.2)
    status(cv, "schematic",
           "example guild of slides 10\u201311 (dots: its pairs); grey: Week et al. 2021, J. Theor. Biol., Eq. 35, one niche width; their results use many species")
    save(fig, "s11c_circle")


def main():
    frame_pair()
    frame_guild(babiana=False)
    frame_guild(babiana=True)
    frame_network()
    frame_within()
    frame_niche()
    frame_circle()


if __name__ == "__main__":
    main()
