---
title: ""
output: 
  html_document:
    theme: cosmo
    css: style.css
---

# Drift, Dispersal and Coevolution in 2-Dimensional Space

<div align="middle">
<iframe src="https://www.openprocessing.org/sketch/396443/embed/?plusEmbedHash=MDBiMzUzOTEzMzg5YThlNTE5MjdlYjY4OGNjNGZlYTU5MGRmY2VjNjI3ZGU2MzJjM2U2ZmMzODIyYTAyZDc1YzFiZjViZThmYjE5NTU1ODZiNjUyYmRiMDA1ODNlYjkyNDY0MzlhNjU0ZjVmZjY3YWQzNTY5YmNlNWYxMDgzZjBFOTI1V014ak8wQ0tJa0ZSYXJpMnhQMkdBeGlVNkJCMzNXNEJ2WXZnREVFNTE0b1d1dTdWY3llSS9YdERCTWRjTWhCU24zNGNYOW1JOUJYang5UjBrZz09&plusEmbedFullscreen=true" width="850" height="650"></iframe>
</div>

<p align=justify style="background-color:#2E2E2E;
border-radius:4px;
font-size:16px;
padding:15px;
margin:5px;"><b>
Here three species coevolve across a two dimensional grid approximating continuous geographic space. One species is colored blue, one red and one green. The trait values that evolve are brightness. To summarize these properties within each pixel, a weighted average of red, blue and green is computed, weighted by the mean brightness of each species within that pixel. The result is a colorful, evolving grid. The interactions between the three species can be thought of as a circular trophic system where each level consumes the next level and is consumed by the previous level. This rock-paper-scissors dynamic leads to an oscillating coevolutionary chase where the green species chases the blue species, the blue species chases the red species and the red species chases the green species.
</b>
</p>
