permalink: /:categories/:title/
url: "http://example.com"
full_name: "| MATHEMATICALLY GUIDED EVOLUTIONARY AND ECOLOGICAL INQUIRY"
first_name: "BOB"
last_name: "WEEK"
blog_title: "Bob Week"
author_img_name_path: "/images/users/me.jpg"
disqus_shortname: "example"
copyright_year: "2017"
google_analytics_code: ""
aboutme: "I smoke the dankest weed."
