---
title: "Branching"
output: 
  html_document: 
    toc: true
    toc_float: true
    theme: cosmo
    css: style.css
---

<!--
output: 
  html_document:
    toc: true
    toc_float: true
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}

## Setup

An individual is represented by its type $z$ which belongs to a type-space $T$. This space can simply be a finite set such as $\{$small, medium, large$\}$ which provides a rough characterization of sizes, or perhaps this space can be a set of $n$ genotypes $\{A_1,\dots,A_n\}$. The space $T$ can also be identified with $\R$ or $\R_+$ in the case of quantitative traits taking either any real value or any positive value, respectively. More complicated examples involve product spaces so that a type is multivariate, where each component space need not be identical. For example, we might want to consider both the genotype and a quantitative trait of an individual.

The nature of fecundity and death differ across the various life-histories observed in nature. I'd like to leave this part general so that many life-histories can be captured with this approach. In fact, my hope is to set this framework up so that life-histories can be allowed to evolve. To do so, I'll consider birth and death rates $\beta(\tau,z)$ and $\delta(\tau,z)$ that are functions of both the individuals age $\tau$ and its type. Assuming the type is heritable, we can easily achieve evolving birth and death rates. Note, that unlike in birfurcating processes such as those used in phylogenetics, I am not assuming an individual either birhts or dies, but that each individual may have multiple birth events before its death. Finally, at each birth event multiple offspring may be produced. The realized number can be captured by a random variable governed by the law $p_k(\tau,z)$ where $p_k$ is the probability that $k$ offpsring are produced.

For inheritance I'll include another variable $x$ that represents an abstract analogue of what quantitative geneticists call a breeding-value. This breeding-value encodes the intrinsic trait of the individual passed on to its offspring, not the expressed trait upon which selection likely acts. An offspring of this individual will inherit a breeding value that has been mututated from $x$ by some (random) operator $\mu$. In the case of real-valued types, we can take $\mu(x)=x+y$ where $y$ is normally distributed with a mean of zero. In the case of a genotype $g\in T=\{A_1,\dots,A_n\}$ we can have $\mu(g)$ taking some random value in $T$. Once the breeding value $x'=\mu(x)$ of an offspring is determined, its expressed type can be generated by yet another operator $\varepsilon$. Returning to the case of a real-valued type, we can have $z'=\varepsilon(x')=x'+e$ with $e$ being another normally distributed random variable with a mean of zero and a variance of $\sigma_s^2$. This variance is called the segregation variance. Note, however, for genotypes we will likely consider $\varepsilon=\iota$, that is, $\varepsilon(x')=x'$, the identity map.

We can also incorporate environmental factors into the above considerations so that $\varepsilon$ or $\delta$, for example, can depend on the environment.