---
title: "Adapting G. Coop's work for coevolutionary inference"
output: 
  html_document:
    theme: cosmo
    css: style.css
---


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { 
    TagSide: "left",
    equationNumbers: { autoNumber: "AMS" } 
  }
});
</script>

\newcommand{\C}{\mathbb{C}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\ra}{\rightarrow}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\logit}{\mathrm{logit}}

## Coop et al 2010

### Notation

  - $L$ unlinked biallelic loci (breaking the unlinked assumption could be very useful)
  - $K$ populations
  - $\pmb n=(n_{kl})$, counts of allele one in locations $k$ at locus $l$ 
  - $\pmb m=(m_{kl})$, counts of allele two in locations $k$ at locus $l$ 
  - $\pmb x=(x_{kl})$, frequency of allele one in location $k$ at locus $l$
  - $x_l$, vector of $k$ allele frequencies at locus $l$ treated as a random variable across space
  - $\pmb\theta_l$, a normally distributed random vector s.t. $x_{kl}=\theta_{kl}$ when $\theta_{kl}\in[0,1]$.
    - $\pmb\theta_l\sim\mathscr{N}_K(\pmb\varepsilon_l,\varepsilon_l(1-\varepsilon_l)\Omega)$
    - $\varepsilon_l$ is a scalar (each location has the same mean)
    - $\varepsilon_l(1-\pmb\varepsilon_l)$ is the variance of a Bernoulli rv with mean $\varepsilon_l$
    - is $\Omega$ a correlation matrix and not a covariance matrix????

### Model

Coop assumes approximate normality of $x_l$ across space. Hence, this is a spatially implicit model. However, the point of this work is to correct for relatedness due to correlated environments and gene-flow which are both likely to be more significant for nearby populations. Instead of using explicit spatial information (coordinates of each location), dispersion kernels and measurements of environmental correlations, Coop uses $\Omega$ to capture pairwise correlations between locations. This is purely phenomenological but significantly reduces the number of parameters and information required to implement this method. It is assumed that $\Omega$ can be inferred using a random subset of loci (the training data). Inference is done using an MCMC to generate posteriors.

An alternative model is then formulated by assuming

$$\theta_l\sim\mathscr{N}_K(\varepsilon_l+\beta Y,\varepsilon_l(1-\varepsilon_l)\Omega)$$

where $Y$ represents an environmental variable standardized with mean zero and variance one. Priors are placed on $\beta,\Omega,\varepsilon_l$ and a Bayes factor is formed with the "likelihood" of the alternative in the numerator and the "likelihood" of the null in the denominator (note the similarity to likelihood-ratios). This Bayes factor is computed for all control loci and aggregated into an empirical distribution from which the Bayes factors for the SNPs of interests are compared. This can be used the exact same way one calculates a $p$-value from likelihood ratio statistics.

### Potential pitfalls

seems like this method will be very sensitive to priors chosen for $\beta$ and each of the $\varepsilon_l$.

### Amendments

I suggest using the logit-normal distribution instead. That is,

$$\logit(x_{kl})=\ln\left(\frac{x_{kl}}{1-x_{kl}}\right)\sim\mathscr{N}.$$

This prevents the awkward truncating of truly normally distributed random variables. Unfortunately, given then mean and variance of each $x_l$, there is no analytical formula relating such moments to the mean and variance of $\logit(x_{kl})$. However, it would be straightforward and not too time costly to implement a numerical method for these calculations.

Another model to consider is the Beta distribution, which has ML solutions given in terms of the digamma function. 

Using a more analytically tractable approach (where numerical integration is necessary only to implement the digamma function, etc) we may be able to skip the need for MCMC. Posteriors can be formed numerically by doing this inversion for randomly drawn parameters from their priors. 

### Coevolution

The obvious approach here is to consider $y_l$ to be a random vector of allele frequencies across the $K$ locations at locus $l$ in an interacting species. We'll have two $\Omega$'s to be inferred separately for each species. The Bayes factor (or likelihood ratio) can then be computed for each location and each species. Locations where where this quantity is significant for both species are locations where these loci are given evidence to be coevolving.

### Comparison to the MLC

In Coop's approach they consider pairwise correlations between loci. In the MLC we only considered the correlation among locations. That is, while Coop models locations $1,\dots,K$ and assumes the allele frequency at each location is normally distributed with different means across space, we assume the mean trait at each location is independent and identically distributed.

However, we also derive this from a model (that ignores gene-flow), while Coop et al's approach is purely phenomenological.

  - realization: MLC does not capture sampling error within locations. this can account for additional variance, increasing the values of the selection strengths.
    - in particular, both toju & sota as well as pauw et al report sample sizes per location. these can be used to simulate sampling error.

## G&uuml;nther & Coop 2013

In this paper they provide the equation

$$P(n_{kl}|\varepsilon_l,n_{kl}+m_{kl})=\left(\begin{matrix}n_{kl} \\ n_{kl}+m_{kl}\end{matrix}\right){\varepsilon_l}^{n_{kl}}(1-\varepsilon_l)^{m_{kl}}$$

I'm questioning whether or not this model requires assumptions of pop size or HW eq...

### Basing this method on a model

We can assume that $\varepsilon_l$ evolves by some population genetic model. Suppose individuals homozygous of allele one have fitness $W_{11}$ and those homozygous of allele two have fitness $W_{22}$ and heterozygous individuals have fitness $W_{12}=W_{21}$. We linearize popgen models using the logit and then capture drift by Brownian motion.

Starting with a haploid asexual model...

$N=n_1+n_2$

$$\frac{dN}{dt}=m_1n_2+m_2n_2$$

$$\varepsilon=\frac{n_1}{N}\implies\frac{d\varepsilon}{dt}=(m_1-\bar m)\varepsilon=\left(m_1-m_1\varepsilon-m_2(1-\varepsilon)\right)\varepsilon$$

$$=(m_1-m_2)(1-\varepsilon_1)\varepsilon_1.$$

Let $z=\ln\left(\frac{\varepsilon}{1-\varepsilon}\right)$. Then

$$\frac{dz}{dt}=\frac{(1-\varepsilon)}{\varepsilon}\frac{(1-\varepsilon)(m_1-m_2)(1-\varepsilon)\varepsilon+\varepsilon(m_1-m_2)(1-\varepsilon)\varepsilon}{(1-\varepsilon)^2}$$

$$=(m_1-m_2)(1-\varepsilon)+(m_1-m_2)\varepsilon=m_1-m_2.$$

Adding stochasticity

$$d\varepsilon=(m_1-m_2)(1-\varepsilon)\varepsilon dt+\frac{(1-\varepsilon)\varepsilon}{\sqrt {N_e}} dB$$

use It&ocirc;'s lemma to determine $dz$...

$$z(\varepsilon)=\ln\left(\frac{\varepsilon}{1-\varepsilon}\right)$$

$$\frac{\partial^2z}{\partial\varepsilon^2}=\frac{\partial}{\partial\varepsilon}\frac{(1-\varepsilon)}{\varepsilon}\frac{(1-\varepsilon)+\varepsilon}{(1-\varepsilon)^2}=\frac{\partial}{\partial\varepsilon}\frac{1}{\varepsilon(1-\varepsilon)}$$

$$=\frac{-(1-2\varepsilon)}{\varepsilon^2(1-\varepsilon)^2}=\frac{\varepsilon-(1-\varepsilon)}{\varepsilon^2(1-\varepsilon)^2}=\frac{1}{\varepsilon(1-\varepsilon)}\left(\frac{1}{(1-\varepsilon)}-\frac{1}{\varepsilon}\right).$$

Thus,

$$dz=\left((m_1-m_2)\frac{\varepsilon(1-\varepsilon)}{\varepsilon(1-\varepsilon)}+\frac{\varepsilon^2(1-\varepsilon)^2}{2N_e}\frac{2\varepsilon-1}{\varepsilon^2(1-\varepsilon)^2}\right)dt$$

$$+\frac{\varepsilon(1-\varepsilon)}{\varepsilon(1-\varepsilon)}\frac{1}{\sqrt{N_e}}dB$$

$$=\left((m_1-m_2)+\frac{1}{N_e}\left(\varepsilon-\frac{1}{2}\right)\right)dt+\frac{1}{\sqrt{N_e}}dB$$

$$\frac{\varepsilon}{1-\varepsilon}=e^z\implies\frac{1}{\varepsilon}-1=e^{-z}$$

$$\implies\varepsilon=\frac{1}{1+e^{-z}}$$

$$\implies dz=\left(m_1-m_2+\frac{1}{2N_e}\frac{1-e^{-z}}{1+e^{-z}}\right)dt+\frac{1}{\sqrt{N_e}}dB$$

$$=\left(m_1-m_2+\frac{1}{2N_e}\tanh\left(\frac{z}{2}\right)\right)dt+\frac{1}{\sqrt{N_e}}dB.$$

  - NOTE: since $\tanh$ is bounded between $-1$ and $1$, we see the dynamics are approximately linear when $|m_1-m_2|\gg1$, ie, when selection is strong.
  
  - NOTE: we can also ignore $\tanh$ if $N_e$ is large enough. the stochastic effects remain since they disappear at a slower order.

Since this model ignores polyploidy, we can pose that there is some ideal value for $x$ being selected for by the environment. This represents potential selection for heterozygotes, frequency dependence, and other interesting polymorphic maintaining selective schemes. Let this optimal amount be denoted by $\theta$. Under this scheme, we can set

$$m_1(z)-m_2(z)=S(\theta-z).$$

where $S$ is the strength of selection for the polymorphism $\theta$. When $N_e$ is large enough so we can ignore $\tanh$, this reduces to an OU model.

#### Adding gene-flow

We focus on the deterministic aspect of gene-flow. In particular, consider $K$ populations, let $\omega_{ji}$ be the rate of gene-flow from population $j$ to population $i$. Then our model becomes

$$dz_i=\left(S(\theta-z_i)+\sum_j\omega_{ji}(z_j-z_i)\right)dt+\frac{1}{\sqrt{N_e}}dB$$

This remains and OU model, but now a multivariate one (in $K$ dimensions). This model can be simplified to


$$dz_i=\left(S(\theta-z_i)+\Omega_i(\mu_i-z_i)\right)dt+\frac{1}{\sqrt{N_e}}dB$$

where 

$$\Omega_i=\sum_j\Omega_{ji},\ \ \ \mu_i=\frac{1}{\Omega_i}\sum_j\omega_{ji}(z_j-z_i).$$

If we assume rates of migration are symmetric and equal across all pairs of populations, then $\mu=\mu_i=\mu_j$ and $\Omega=\Omega_i=\Omega_j$ for each $i,j$. Hence, we find

$$dz_i=\left(S(\theta-z_i)+\Omega(\mu-z_i)\right)dt+\frac{1}{\sqrt{N_e}}dB$$

and taking It&ocirc;'s lemma once more to find $d\mu$ and $dV$ (where $V=\Var(z)$), then I have successfully recreated the MLC for population genetics.

  - NOTE: to apply this to data, one would take the logit of the mean of allele frequencies across space (even though we model the mean of the logit). if this mean is one or zero, our method assume directional selection (no equilibrium).
  
  - this seems like a pretty useless method...
  
  - taking a few steps back, perhaps applying the logit is totally unneccessary, even though its cool. maybe we can get an equilibrium distribution of allele freq's across space using a regular pop-gen model. otherwise we run into problems with species that are fixed for an allele. on second thought, loci that are fixed species-wide tell us this is probably due to selection (or remnants of drift past), but contains zero information otherwise. there's no way to know how strong selection was (if indeed that was the agent) unless we had time-series data.
