---
title: "Crazy Ideas"
output: 
  html_document: 
    toc: true
    toc_float: true
    theme: cosmo
    css: style.css
---

<!--
output: 
  html_document:
    toc: true
    toc_float: true
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}

## Multivariate Types

Suppose each type $i$ has $K$ different components. In the case of discrete types we can denote a given type by $(c_1,\dots,c_K)$ where each $c_i$ belongs to some set $C_i$ that would be finite or countable. Then we would still be able to enumerate these types even with their $K$ components. We could then just use the index that enumerate them by to label each type. This wouldn't fundamentally change anything about the treatment of discrete types.

However, for continuous types this is not the case. Having $K$ components does create a fundamentally new situation. Let's start by assuming $K=2$ and label each component $z_1$ and $z_2$ and assume $z=(z_1,z_2)\in\R^2$. Fitness then becomes a bivariate function $W(z)=W(z_1,z_2)$ and the phenotypic density becomes the joint density $\phi_t(z)=\phi_t(z_1,z_2)$ (and since population density is just a scaled version of $\phi$ it too will be bivariate).

### Trait$\times$Species

Our type space can be $T\times S$ where $T$ represents the trait and $S$ represents the species. We could let $T=S=\R$ and assume adjacent species can hybridize and capture this process with diffusion. This adds another dimension through which populations can separate. Can we have random mating along the $T$ axis and, with bimodal selection, get divergence on the $S$ axis?

## Energy Partitioning

The proportion of energy intake allocated towards reproduction and survival over the lifetime of an individual is a trait of that individual. This number $p\in[0,1]$ will evolve to maximize fitness, the expected number of individuals left behind.

## How do we incorporate different life-spans into the theory?

## Fitness as a trait

Fitness usually evolves indirectly as the result of some other trait $z$. We can set the trait $z=W\in\R_{>0}$. If we assume that $W\sim\ln\mathcal{N}(\overline{\ln W},V_W)$ then

$$\Delta\overline{\ln W}=G_W\frac{\partial\ln\overline W}{\partial\overline{\ln W}}?$$

[I think](https://stats.stackexchange.com/questions/45924/expectation-of-an-exponential-function) $\overline W=\exp\para{\overline{\ln W}+V_W/2}$. Then

$$\Delta\overline{\ln W}=G_W.$$

Does this result contradict the constant additive genetic variance assumption of most quantitative genetic models? Typically $\bar z\rightarrow\theta$ and $\overline W\rightarrow\overline W_\max$. However, this result states that if there is additive genetic variance in fitness then $\overline W$ increases by this amount. But if there's additive genetic variance in $z$ and fitness is a Gaussian function of $z$ as usual AND we keep the assumption of constant additive genetic variance we arrive at a contradiction! But before we get too offended, we should compute the actual distribution of $W$ given that $W$ is a Gaussian function of $z$ and $z$ is normally distributed. It will be bounded to a finite interval and so cannot be $\ln\mathcal{N}$. What relationship between $W$ and $z$ allows for both $\ln W$ and $z$ to be normally distributed?

## Bayesian vs Frequentist

They're both wrong, but Bayesians are less wrong. No event has a probability ascribed to it by some existential force. Things happen or they don't happen$\dots$ with probability one. That is, events occur deterministically. I have yet to study the formal logic behind the next claim, but if for each event there is a causal chain of older events leading up to and triggering this event, then events occur deterministically. That is, if you knew the effect of every event (the set of events triggered by each single event) then you would be able to predict with certainty the unfoldings of future events. Then, for example, if I were to toss a coin and had this omniscient knowledge, I would be able to predict what side the coin would land on. Of course it is impossible to have such knowledge, even with the finest lazers and sensors on the market today, that confides absolute certainty. So it seems there is some stochasticity in our world. I argue this is not so, it is error in our ability to predict the future that makes the appearance of randomness and it is easier for us to chalk up surprising events to the word "chance" (even if we don't understand it) rather than constantly nodding our head to the infinitude of mystery that surrounds us in every moment of our existence.

The term stochastic comes from the Greek word "stokhastikos" which means to guess or aim at. So instead of thinking of something that is stochastic as something that is inherently random, the word stochastic should refer to something whose understanding is unclear or uncertain due to lack of information, but that this thing has an objective existence independent of our awareness of it.

## Drift is a cop-out, not a process

We model drift as random sampling of the (potentially) parental gene-pool. However, we know this process is not truly random but we treat as so to deal with idiosyncratic details that contribute to our uncertainty.

## Not-quite-semigroup definition of a species

THIS IS DUMB: A species is a pair $(S,R)$ where $S$ is a set and $R$ a binary operation s.t. $R:S\times S\rightarrow S$. That is, the only restriction is that $S$ is closed under $R$. For example, taking $S=\R$ and $R(x,y)=\frac{x+y}{2}$ we have that $(a,b)$ and $(c,d)$ form species when $a<b<c<d$ but $(a,b)\cup(c,d)$ do not since $R(b,c)\notin(a,b)\cup(c,d)$. Note that $\R$ forms a species and subsets of $\R$ that are also species can be called sub-species. 

$P($individual $x$ mates with individual $y)=f($mating behavior of $x$ and $y$, location/ethology of $x$ and $y$ and compatibility of physiology as well as gametes$)$

This probability is at least slightly different for every pair of individuals in a population.

