---
title: "Stochastic partial differential equations"
output: 
  html_document: 
    toc: true
    toc_float: true
    toc_depth: 1
    theme: cosmo
    css: style.css
---

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\V}{\mathrm{Var}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\W}{\mathscr{W}}
\newcommand{\Q}{\mathscr{Q}}
\newcommand{\U}{\mathscr{U}}
\newcommand{\L}{\mathscr{L}}
\newcommand{\O}{\mathscr{O}}



# Motivation

Consider a biological population where each individual has a real valued trait $z$. Let $\mathfrak{n}_t(z)$ denote the abundance density of the trait value $z$ at time $t$. The total abundance of the population $n_t$ is given by $n_t=\int\mathfrak{n}_t(z)dz$. For each fixed $z\in \R$ let $\mathfrak{n}_t(z)$ be a real valued stochastic process satisfying the SDE

$$d\mathfrak{n}_t(z)=m(z)\mathfrak{n}_t(z)dt+\eta\mathfrak{n}_t(z)dB_t(z), \ \ \mathfrak{n}_0(z)>0.$$

The function $m\in L^\infty(\R)$ maps the trait value $z$ to the Malthusian fitness of individuals with trait $z$. The number $0\leq\eta<\infty$ denotes the magnitude of demographic stochasticity and $B_t(z)$ is a one dimensional Brownian motion for each fixed $z\in\R$. For now we assume perfect heritability which may be implied by the more specific assumptions that the population is asexually reproducing and the effects of mutation and epigenetics are absent. This means the set of processes $\{\mathfrak{n}_t(z)\}$ are independent.

The solution to this SDE $d\mathfrak{n}_t(z)$ can be found in &Oslash;ksendal, example 5.1.1, which is repeated here:

The dependency on $z$ is suppressed for clarity. Rearranging, we have

$$\frac{d\mathfrak{n}_t}{\mathfrak{n}_t}=mdt+\eta dB_t$$

and thus

$$\int_0^t\frac{d\mathfrak{n}_s}{\mathfrak{n}_s}ds=mt+\eta B_t.$$

Using the finite dimensional It&ocirc; formula on the function $g(t,x)=\ln x, \ x>0$, we get

$$d(\ln \mathfrak{n}_t)=\frac{1}{\mathfrak{n}_t}d\mathfrak{n}_t+\frac{1}{2}\left(-\frac{1}{\mathfrak{n}_t}\right)(d\mathfrak{n}_t)^2$$

$$=\frac{d\mathfrak{n}_t}{\mathfrak{n}_t}-\frac{1}{2}\eta^2dt.$$

Combining these results, we find $\mathfrak{n}_t=\mathfrak{n}_0\exp((m-\frac{1}{2}\eta^2)t+\eta B_t)$, which is a geometric Brownian motion. Since we assumed perfect heritability and that fitness for each trait is constant in time, the solution $\mathfrak{n}_t(z)$ has been found for each $z$. We can rewrite $n_t$ as

$$\int_\R\mathfrak{n}_t(z)dz=\int_\R\mathfrak{n}_0(z)\exp((m(z)-\frac{1}{2}\eta^2)t+\eta B_t(z))dz.$$

Since $\mathfrak{n}_t(z)>0$ for $t\geq0, \ z\in\R$, we can use Tonelli's theorem to justify

$$\E n_t=\int_\R\E\mathfrak{n}_t(z)dz.$$

Using the properties of geometric Brownian motion, we know that $\mathfrak{n}_t(z)$ is a log-normal random variable with mean $\E(\mathfrak{n}_0(z))e^{m(z)t}$. Writing $p_t(z)=\mathfrak{n}_t(z)/n_t$, we have

$$\E n_t=\E\int_\R\mathfrak{n}_0e^{mt}dz=\E\int_\R n_0p_0e^{mt}dz$$

$$=\E\left(n_0\int_\R p_0e^{mt}dz\right).$$

Assuming the random numbers $n_0$ and $p_0$ are independent, we have

$$\E n_t=\E(n_0)\E\overline{e^{mt}}^{(0)}$$

where $\overline{e^{mt}}^{(s)}=\int_\R p_s(z)e^{m(z)t}dz$. We could use a similar approach to find the variance of $n_t$. However, it would be useful to calculate the SDE $dn_t$ and the associated $dp_t$.

Note that 

$$\mathfrak{n}_0(z)\in L^1(\R)\cap L^\infty(\R)$$

since we require 

$$\|\mathfrak{n}_0\|_1\equiv\int|\mathfrak{n}_0(z)|dz=n_0<\infty$$

and 

$$\|\mathfrak{n}_0\|_\infty\equiv\sup_{z\in\R}|\mathfrak{n}_0(z)|<\infty.$$

Hence, H&ouml;lder's inequality implies

$$\|\mathfrak{n}_0^2\|_1\leq\|\mathfrak{n}_0\|_1\|\mathfrak{n}_0\|_\infty<\infty.$$

In particular, $\|\mathfrak{n}_0^2\|_1^{1/2}=\left(\int|\mathfrak{n}_0(z)|^2dz\right)^{1/2}=\|\mathfrak{n}_0\|_2<\infty$ so that $\mathfrak{n}_0\in L^2(\R)$. Because of this we can view $n_t$ as a linear functional on $L^2(\R)$. Therefore, to calculate $dn_t$ from $\mathfrak{n}_t$ we will need an infinite dimensional extension of It&ocirc;'s formula. Developing the theory for this extension will also allow us to work with actual SPDE where, for example, the set of SDE $\{\mathfrak{n}_t(z)\}$ no longer evolve independently. In particular, we'll be able to develop models accounting for imperfect heritability, sexual preference, frequency and density dependent selection, migration and so forth.

# Notation

  - $\L(X)$... the law of the random variable $X$.
  - $E,F,G$... Banach spaces
  - $E^*$... the dual of $E$
  - $H$... a Hilbert space with inner product $\left<\cdot,\cdot\right>$
  - $U$... a separable Hilbert space $\iff$ $U$ admits a countable orthonormal basis
    - $U_1,U_2,\dots$ will also denote separable Hilbert spaces
    - $\U$... denotes a separable Hilbert space that can be interpreted as $L^2(U)$
  - $\mathscr{O}$... a subset of $\R^d$
  - $\mathscr{B}(E)$... the Banach $\sigma$-algebra of a space $E$
  - $L(E,F)$... Banach space of linear bounded operators from $E$ to $F$.
  - $L_1(E,F)$... Banach space of nuclear operators
  - $L_2(U_1,U_2)$... separable Hilbert space of Hilbert-Schmidt operators
  - $L_2^0=L_2(U_0,U_1)$... the space of all Hilbert-Schmidt operators from $U_0$ to $U_1$
  - $W:[0,\infty)\rightarrow U$... a $U$-valued Wiener process
  - $\W$... a generalized Wiener process
  - $Q\in L_1(U)$... covariance operator of a $U$-valued Wiener process
  - $\Q\in L(U)$... covariance operator of a generalized Wiener process
  - $U_0=Q^{1/2}(U)$... the reproducing kernel of a $U$-valued Wiener process
  - $\U_0=\Q^{1/2}(U)$... the reproducing kernel of a generalized Wiener process
  - $\triangle$... denotes the end of a statement 

# 4.1 Wiener processes

- __Def 4.1__ A real valued stochastic process $W(t), \ t\geq0$, is called a __Wiener process__ if

  1. $W$ has continous trajectories and $W(0)=0$.
  2. $W$ has independent increments and
  
$$\L(W(t)-W(s))=\L(W(t-s)), \ t\geq s\geq0.$$  

  3. $\L(W(t))=\L(-W(t)), \ t\geq0. \ \triangle$

- __Def__ (extension to a general linear (topological) space $K$ with $\sigma$-algebra $\mathscr{B}(K)$) A $K$-valued stochastic process $W(t), \ t\geq0$ satisfying 1.-3. is a __Wiener process__ in $K$. $\triangle$

## 4.1.1 Hilbert space valued Wiener processes 

Let $W$ be a $U$-valued Wiener process. Then $\left<W(t),u\right>, \ t\geq0,$ is a real valued Wiener process and $\L(W(t))$ is a Gaussian measure with mean 0. Furthermore, for any $u,v\in U, \ t,s\geq0,$

$$\E[\left<W(t),u\right>\left<W(s),u\right>]=(t\wedge s)\E[\left<W(1),u\right>^2]$$

and

$$\E[\left<W(t),u\right>\left<W(s),v\right>]=(t\wedge s)\E[\left<W(1),u\right>\left<W(1),v\right>]$$

$$=(t\wedge s)\left<Qu,v\right>$$

where $Q$ is the covariance operator of the Gaussian measure $\L(W(1))$. The operator $Q$ is of trace class and for each distribution $\L(W(1))$, there is a trace class $Q$ that completely characterizes it.

- __Def 4.2__ A $U$-valued stochastic process $W(t), \ t\geq0$ is a __$Q$-Wiener__ process if

  1. $W(0)=0$.
  2. $W$ has continuous trajectories.
  3. $W$ has independent increments.
  4. $\L(W(t)-W(s))=\mathscr{N}(0,(t-s)Q), \ t\geq s\geq0$. $\triangle$

Because of our assumptions about $Q$ and since $U$ has a complete orthonormal system $\{e_k\}\subset U$, there exists a bounded sequence of nonnegative real numbers $\{\lambda_k\}$ s.t. $Qe_k=\lambda_ke_k, \ k\in\mathbb{N}$.

- __Proposition 4.3__ If $W(t)$ is a $Q$-Wiener process, then

  1. $W$ is a Gaussian process on $U$ and
  
$$\E(W(t))=0, \ \Cov(W(t))=tQ, \ t\geq0.$$

  2. For any $t\geq0$, $W$ has the expansion
  
$$W(t)=\sum_j\sqrt{\lambda_j}\beta_j(t)e_j$$

where

$$\beta_j(t)=\frac{1}{\sqrt{\lambda_j}}\left<W(t),e_j\right>, \ j\in\mathbb{N}$$

are real valued Brownian motions mutually independent on $(\Omega,\mathscr{F},\mathbb{P})$ and the series expansion of $W(t)$ converges in $L^2(\Omega,\mathscr{F},\mathbb{P})$.

  - __Observation__ The expansion above is strikingly remeniscient of the Karhunen-Lo&egrave;ve (KL) expansion. However the above expansion is with respect to the Hilbert space in which $W(t)$ takes its values. The KL expansion, on the other hand, is with respect to time. Specifically, the KL expansion is defined for a zero-mean process $X(t)\in L^2(\Omega,\mathscr{F},\mathbb{P})$ with $t\in[a,b]$ and continuous $K(s,t)=\E(X(s)X(t))$. If $\{\lambda_k\}$ denotes the set of eigenvalues of $T:L^2([a,b])\rightarrow L^2([a,b])$ defined by $(Tf)(t)\equiv\int_a^b K(s,t)f(s)ds$, then the KL expansion of $X(t)$ is
  
$$X(t)=\sum_j\sqrt{\lambda_j}\beta_je_j(t)$$

where 

$$\beta_j=\frac{1}{\sqrt{\lambda_j}}\int_a^bX(t)e_j(t)dt, \ j\in\mathbb{N}$$

are uncorrelated zero-mean random variables with unit variance. The convergence of the KL expansion is in $L^2(\Omega)$, uniform in $t$. Notice that in Proposition 4.3, $e_j\in U$ are not functions of time, but the $\beta_j$ are. However, for the KL expansion the $\beta_j$ are not functions of time but the $e_j$ are.

## 4.1.2 Generalized Wiener processes over a Hilbert space

The primary reason for my study of SPDE is to formally treat PDE subjected to a specific kind of noise. In particular, the noise I wish to account for, denoted by $\W$ where $\W(x,t)\in\R$ for each $x\in U$ ($U$ is usually some subset of $\R^n$) and $t\in[0,\infty)$, should satisfy the following properties:

  1. For every $x\in U,0\leq s\leq t\in[0,\infty)$

$$\L(\W(x,t)-\W(x,s))=\L(\W(x,t-s))=\mathscr{N}(0,t-s).$$

  2. For any $x,y\in U$ and $t,s\in[0,\infty)$
  
$$\E(\W(x,t)\W(y,s))=(t\wedge s)\delta(x-y)=0.$$

That is, $\W(x,t)$ is a set of independent real valued Brownian motions indexed by $x\in U$. Previous definitions of the Wiener process are insufficient to capture this since $\W(t)=\{\W(x,t):x\in U\}$ is not valued in a convenient Hilbert space. In particular, my prefered Hilbert space is $L^2(\R^n)$, but, even for $n=1$, $\int_\R\W(t,x)dx$ is not finite wp1! To circumvent this, Da Prato & Zabczyk give the following definition 

- __Def__ Any transformation that maps $a\in\U$ to $W_a$, a real valued Wiener processes on $[0,\infty)$, that is continuous in the sense 

$$t\geq0, \{a_n\}\subset U_1, \lim_{n\rightarrow\infty}\|a_n-a\|_{U_1}=0\implies\lim_{n\rightarrow\infty}\E\left|W_a(t)-W_{a_n}(t)\right|^2=0.$$

is a __generalized Wiener process__ over $\U$. Note that the integral transformation given by $W_a(t)=\int_U a(x)\W(x,t)dx$ may qualify as such a mapping (for concreteness, I think of $U=\R^n$ and $\U=L^2(\R^n)$). With this in mind, I use the symbol $\W$ to also denote the mapping satisfying the above definition so I may refer to $\W$ as a generalized Wiener process.

This definition implies the existence of a bilinear form $K(a,b), \ a,b\in \U$ s.t.

$$\E[W_a(t)W_b(s)]=(t\wedge s) \ K(a,b), \ \ t,s\geq0, \ a,b\in\U.$$

The continuity condition gurantees that $K$ is continuous in $\U$ and hence there exists $\Q\in L(\U)$ s.t.

$$\E[W_a(t)W_b(s)]=(t\wedge s)\left<\Q a,b\right>, \ \ t,s\geq0, \ a,b\in\U.$$

This operator is self-adjoint and positive definite and is the __covariance__ of the generalized Wiener process $\W$. 

If $\Q$ is the identity operator,

$$\Q a=a, \ \ a\in \U$$

then $\W$ is called a __cylindrical Wiener process__ in $\U$. As mentioned in the primer on SPDE by Martin Hairer, it is unfortunate that $\W$ is referred to as a process in $\U$ since it is __not__ $\U$-valued. Hairer suggests that $\W$ should be called a cylindrical Wiener process over $\U$. 

At first glance, I feel there is an issue here. For my process $\W$ introduced at the beginning of this section, I mistakenly believe I need $K(a,b)=\delta(a-b)$. I'm not sure if there exists a $\Q$ that corresponds to this form. However, none of this is true. I'm forgetting that $a,b\in\U$ and what I'm thinking of are $a,b\R^n$. Note that if $a(x)=\delta(x-y)$ and $b=\delta(x-z)$, then (for $\Q=I$)

$$\E[W_a(t)W_b(s)]=(t\wedge s)\left<a,b\right>=(t\wedge s)\delta(y-z).$$

Thus, the above result is a generalization of condition (2.) on the process $B$ where $\E[\W(t,y)\W(s,z)]=(t\wedge s)\delta(y-z)$. Hence, everything is just fine.

- __Example__ Let $\W$ be a cylindrical Wiener process over $\U=L^2(\R)$. Then for any $u,v\in L^2(\R)$

$$\E[W_u(t)W_v(s)]=(t\wedge s)\int_\R u(x)v(x)dx.$$

This is the case that I will pay special attention to.

If $\U_0=\Q^{1/2}(\U)$ we call $\U_0$ the __reproducing kernel__ of the generalized Wiener process.

- Constructing a generalized Wiener process from an arbitrary self-adjoint and positive definite operator $\Q$:

Let $\{e_j\}$ be a complete orthonormal basis in $U_1$ and $\{\beta_j\}$ a sequence of independent real valued standard Wiener processes. Define

$$W_a(t)\equiv\sum_j\left<\Q^{1/2}e_j,a\right>\beta_j(t), \ \ t\geq0, \ a\in\U.$$

- __Proposition 4.8__ For every $a\in\U$ we have

$$W_a(t)=\sum_j\left<\Q^{1/2}e_j,a\right>W_{\Q^{1/2}e_j}(t).$$

This forms a generalized Wiener process with covariance $\Q$.

- __Intuitive result__ An arbitrary generalized Wiener process over $\U$ is a classical Wiener process taking values in some larger Hilbert space $\U'$. 

For example if $\U=L^2(\R)$ we could take $\U'=L^2_\rho(\R)$ which is the set of all real valued functions $u$ over $\R$ s.t. $\int_\R|u(x)|^2\rho(x)dx<\infty$ for some nonnegative fixed $\rho\in L^2(\R)$. Clearly $L^2_\rho=L^2(\R,\mathscr{B}(\R),\nu)$ where the measure $\nu$ is given by $\nu(A)=\int_A\rho(x)dx$. It is also clear that $L^2(\R)\subset L^2_\rho(\R)$ since for $v\in L^2(\R)$, we have $w=|v|^2\in L^2$ and hence the Schwartz inequality implies $\int_\R|v(x)|^2\rho(x)dx\leq\|w\|_2\|\rho\|_2<\infty$. 

If we set $\rho$ s.t. $\int\rho^2=1$ then we can think of a cylindrical Wiener process $\W$ over $L^2(\R)$ (so that $\W$ takes values in $L^2_\rho(\R)$) as a function of time which, for each $t$, returns an infinite set of mean zero normal random variables with variance $t$ that we can "sample" using $\rho$. That is,

$$\int_\R\W(t,x)\rho(x)dx=X(t)$$

is a well defined random variable for each $t$. Partly by definition of $\W$ it seems obvious that if $\rho^2$ is a probability density function, then $X(t)$ is a normally distributed random variable with mean zero and variance $t$. In fact, since $\E|W(x,t)|$ is finite for each $x\in\R$ and $t\geq0$, we have

$$\E\int_\R|\W(t,x)||\rho(x)|dx\leq\int_\R\rho(x)\E|\W(x,t)|dx<\infty$$

and therefore we may swap the order of Lebesgue integration to show

$$\E X(t)=0.$$

Note also that, for a fixed $t$, $\W(t,x)$ is white-noise wrt $x$. That is, $\W(t,x)$ is, in some sense, the derivative of a Brownian motion over $x\in\R$. Restricting our attention to the closed subset $[a,b]\subset\R$ we then have

$$\int_a^b\W(t,x)dx$$

is a mean zero normally distributed random variable with variance $(b-a)t$. Hence, by partitioning $\R$ into a finite set of intervals $\{[a_i,b_i]\}$ we can define $\rho$ as a simple function so that it is constant on each interval and

$$\int_\R\rho^2=\sum_i\rho_i^2(b_i-a_i)=1.$$

With $\rho$ defined in this manner we have

$$\V(X(t))=\V\left(\sum_i\int_{I_i}\W(t,x)\rho(x)dx\right)$$

$$=\sum_i\rho_i^2\V\left(\int_{a_i}^{b_i}\W(t,x)dx\right)=\sum_i\rho_i^2(b_i-a_i)t=t.$$

For the final step we simply note that any nonnegative measurable function can be approximated arbitrarily closely by a simple function. Using Lebesgue's dominated convergence theorem, we achieve our result.

Of course, this can be applied to nonnegative $\rho\in L^2(\R)$ where $\int\rho^2\neq1$. In this case, we simply get

$$\V(X(t))=\|\rho\|_2^2t.$$

## 4.1.3 Wiener processes over $\U=L^2(\mathscr{O})$

- The point of including this section is that it explicitly treats Brownian sheets.

Let $\U=L^2(\mathscr{O})$ and $W$ a $\U$-valued $Q$-Wiener process. Then $Q^{1/2}$ is Hilbert-Schmidt on $\U$ which implies it is the integral operator

$$Q^{1/2}\phi(x)=\int_\O r(x,y)\phi(y)dy, \ \ x\in\O, \ \phi\in L^2(\O)$$

where the kernel $r$ is square-integrable on $\mathscr{O}^2$ and hence so is $Q$

$$Q\phi(x)=\int_\O\int_\O r(x,z)r(z,y)\phi(y)dz dy, \ \ x\in\mathscr{O}, \ \phi\in L^2(\O).$$

The kernel of $Q$, $g(x,y)=\int_\O r(x,z)r(z,y)dz$, can be interpreted as the "spatial" correlation of $W$ in $L^2(\O)$. For all $t>0$, $W(t,\cdot)$ is an $L^2(\O)$-valued random variable and $W(\cdot,x)$ is a real valued random variable for a.a. $x\in\O$.

Assume the random field $W(t,x), \ t\geq0, \ x\in\O$ is measurable. For $\phi,\psi\in L^2(\O)$

$$\E[\left<W(t),\phi\right>\left<W(t),\psi\right>]=\E\left[\int_\O W(t,x)\phi(x)dx\int_\O W(t,y)\psi(y)dy\right]=\star.$$

Taking absolute values within the expectation, one can use the Schwartz inequality to justify changing the order of Lebesgue integration to get

$$\star=\int_\O\int_\O\phi(x)\psi(y)\E[W(t,x)W(t,y)]dxdy.$$

Since $W$ is a $\U$-valued Wiener process we have

$$\E[\left<W(t),\psi\right>\left<W(t),\phi\right>]=t\left<Q\phi,\psi\right>.$$

But from the beginning of this section we also have $Q\phi(x)=\int_\O g(x,y)\phi(y)dy$. Hence,

$$$$

This can be used to show $g(x,y)=\frac{1}{t}\E[W(t,x)W(t,y)]$ which is interpreted as the "spatial" correlation of the $Q$-Wiener processes $W$ in $L^2(\mathscr{O})$. If $\mathscr{O}$ is an open (closed) bounded subset of $\R^n$ and $g$ is bounded and continuous on $\mathscr{O}$, then $Q$ is a covariance operator on $U_1$ of trace class.

- __Example 4.9: Brownian sheets__ Let $\mathscr{O}=[0,\pi]$ and $g(x,y)=x\wedge y, \ x,y\in[0,\pi]$. Note that $g$ is continuous and, since for a one dimensional Wiener process $\beta$

$$x\wedge y=\E[\beta(x)\beta(y)]$$

$g$ is positive definite. The eigenvalues and eigenfunctions of the corresponding $Q$ are

$$\lambda_n=(n+\frac{1}{2})^{-2}, \ e_n=\sqrt{\frac{2}{\pi}}\sin\left[\left(n+\frac{1}{2}\right)x\right], \ x\in[0,\pi], \ n\in\N$$

hence

$$W(t,x)=\sum_n\frac{\beta_n(t)}{n+\frac{1}{2}}\sqrt{\frac{2}{\pi}}\sin\left[\left(n+\frac{1}{2}\right)x\right], \ t\geq0, \ x\in[0,\pi]$$

where the $\beta_n$ are independent real standard Brownian motions. From this we have

$$\E[W(t,x)W(s,y)]=(t\wedge s)(x\wedge y).$$

Fields $W$ with the above covariance are called __Brownian sheets__ on $[0,\infty)\times[0,\pi]$. $\triangle$

- __Proposition 4.10__ Given an arbitraty set $\O$, a function $g(x,y)$ is positive definite iff there exists a family of random variables $X(x)$ s.t. for distinct $x_1,\dots,x_j\in\O$ the random vector $X(x_1),\dots,X(x_j)$ is Gaussian with mean zero and 

$$g(x,y)=\E[X(x)X(y)], \ x,y\in\O. \ \triangle$$

- __Corr 4.11__ If $g_1$ and $g_2$ are positive definite on $\O_1$ and $\O_2$ then

$$g((x_1,x_2),(y_1,y_2))\equiv g_1(x_1,y_1)g(x_2,y_2), \ (x_1,y_1)\in\O_1, \ (x_2,y_2)\in\O_2$$

is positive definite on $\O_1\times\O_2$. $\triangle$

- __Example 4.12: Brownian sheets on $[0,\infty)\times\O$__ Let $\O\subset\R^n$ and $g$ a positive definite function on $\O$. By prop 4.11

$$(t\wedge s)g(x,y), \ (t,x),(s,y)\in[0,\infty)\times\O,$$

is also positive definite and there exists a Gaussian family $W(t,x), \ t\geq0, \ x\in\O$ s.t.

$$\E[W(t,x)W(s,y)]=(t\wedge s)g(x,y).$$

For each $x$, $W(\cdot,x)$ has all the properties of a real valued Wiener process except for the regularity of trajectories. To prove the existence of a proper modification requires additional properties of $g$. $\triangle$

## 4.1.4. Spatially homogeneous Wiener processes

- This section is included becuase it provides and explicit treatment of a cylindrical Wiener process on $L^2(\R^n)$.

- __Def__ If $\mu$ is a probability measure on $(E,\mathscr{B}(E))$, then the function $\hat\mu$ on $E^*$

$$\hat\mu(y)\equiv\int_Ee^{iy(x)}\mu(dx), \ \ y\in E^*$$

is the __characteristic function__ of $\mu$. If $E=H$ is a Hilbert space then

$$\hat\mu(\lambda)=\int_He^{i\left<\lambda,x\right>}\mu(dx), \ \ \lambda\in H.$$

- __Bochners theorem__ If $\phi:U\rightarrow\mathbb{C}$ is a characteristic function of a probability measure $\mu$ on $(U,\mathscr{B}(U))$ then

  1. $\phi$ is a continuous, positive definite function s.t. $\phi(0)=1$.
  2. For any $\epsilon>0$ there exists a nonnegative nuclear operator $S_\epsilon$ s.t.
  
$$1-\mathfrak{Re}\phi(\lambda)\leq\epsilon, \ \ \forall \ \lambda:\left<S_\epsilon\lambda,\lambda\right>\leq1.$$

Conversly, if $\phi$ satisfies 1. & 2., then it is a characteristic function of some probability measure on $U$. $\triangle$

Let $\mu$ be a finite nonnegative measure on $\R^n$ and

$$\Gamma(\lambda)\equiv\int_{\R^n}e^{i\left<\lambda,x\right>}\mu(dx), \ \lambda\in\R^n,$$

then $g(x,y)=\Gamma(x-y), \ x, \ y\in\R^n,$ is a continuous, bounded, positive definite function. Under some further (mild) conditions on $\mu$ one can show there exists a continuous random field $W(t,x)$ s.t. $W(t,\cdot)$ is a Wiener process in $L_\rho^2(\R^n)$, for an integrable weight $\rho$, s.t.

$$\E[W(t,x)W(s,y)]=(t\wedge s)\Gamma(x-y).$$

Then

$$\E\|W(t,\cdot)\|_{L_\rho^2}^2=\E\int_{\R^n}|W(t,x)|^2\rho(x)dx$$

$$=\int_{\R^n}\E|W(t,x)|^2\rho(x)dx=t\Gamma(0)\int_{\R^n}\rho(x)dx.$$

We now generalize. Let $\mathscr{S}_c(\R^n)$ denote the space of $\mathbb{C}$-valued infinitely differentiable functions $\psi$ on $\R^n$ for which each seminorm

$$|\psi|_{\alpha,\beta}=\sup_{x\in\R^n}|x^\alpha D^\beta\psi(x)|$$

is finite. The dual space $\mathscr{S}^*_c(\R^n)$ is the space of __tempered distributions__. The space $\mathscr{S}(\R^n)$ consists of real valued functions from $\mathscr{S}_c(\R^n)$. The space $\mathscr{S}^*(\R^n)$ consists of real valued functionals from $\mathscr{S}^*_c(\R^n)$. We suppress the dependency on $\R^n$.

For $\psi\in\mathscr{S}_c$ define $\psi_{(s)}\equiv\overline{\psi(-x)}, \ x\in\R^n.$ Denote $\mathscr{S}_{(s)}=\{\psi\in\mathscr{S}_c:\psi=\psi_{(s)}\}$ and $\mathscr{S}_{(s)}^*=\{u\in\mathscr{S}^*:(u,\psi)=(u,\psi_{(s)}s) \ \forall \ \psi\in\mathscr{S}_{(s)}\}$. For $\psi\in\mathscr{S}_c$ write $\hat\psi$ for the Fourier transform

$$\hat\psi(\lambda)=\left(\frac{1}{2\pi}\right)^{n/2}\int_{\R^n}e^{-2\pi i\left<\lambda,x\right>}\psi(x)dx.$$

For each $u\in\mathscr{S}_c^*$, $\hat u$ is given by $(\hat u,\hat\psi)=(u,\psi)$.

The distribution $\Gamma\in\mathscr{S}^*$ is positive definite if for each $\psi\in\mathscr{S}$

$$(\Gamma,\psi*\psi_{(s)})\geq0.$$

- __Theorem 4.13__ A distribution $\Gamma\in\mathscr{S}^*$ is positive definite if there exists a measure $\mu\in\mathscr{S}^*$ symmetric around 0 s.t. $\Gamma=\hat\mu$. Then $\mu$ is called the spectral measure of $\Gamma$.

- __Def__ An $\mathscr{S}^*$-valued continuous stochastic process $\W$ is called a Wiener process with covariance kernel $\Gamma$ if

  1. For each $\psi\in\mathscr{S}$ the process $(\W,\psi)$ is a real valued Wiener process
  2. For all $s,t\geq0,\phi,\psi\in\mathscr{S}$ we have
  
$$\E[(\W(t),\phi)(\W(s),\psi)]=(t\wedge s)(\Gamma,\phi*\psi_{(s)}).$$

- __Theorem 4.14__ For any positive definite distribution $\Gamma$ there exists a Wiener process $W$ with covariance kernel $\Gamma$. Furthermore, there is a Hilbert space $U_\Gamma$, continuously embedded in $\mathscr{S}^*$, s.t.

$$\L((\W(t),\psi))=\mathscr{N}(0,t\|\psi\|^2_{U_\Gamma}), \ \ \forall \ \psi\in\mathscr{S}.$$

- __Example 4.16__ Let $\mu=\delta_0$, the delta measure at 0, then

$$\Gamma=\hat\delta_0=\left(\frac{1}{2\pi}\right)^{n/2}\lambda_n,$$

where $\lambda_n$ denotes the Lebesgue measure on $\R^n$. The space $U_\Gamma$ is then one dimensional and consists of constant functions (so is it isomorphic to $\R$?). The process $\W$ is then of the form

$$\W=\left(\frac{1}{2\pi}\right)^{n/2}\beta(t)\lambda_n$$

where $\beta(t)$ is a standard Brownian motion. $\triangle$

- __Example 4.17__ Let $\mu=\lambda_n$, then

$$\Gamma=\hat\lambda_n=(2\pi)^{n/2}\delta_0.$$

For any $\phi,\psi\in\mathscr{S}$ we then have

$$(\Gamma,\phi*\psi_{(s)})=(2\pi)^{n/2}\int_{\R^n}\phi(-x)\psi_{(s)}(x)dx$$

$$=(2\pi)^{n/2}\int_{\R^n}\phi(-x)\psi(-x)dx=(2\pi)^{n/2}\int_{\R^n}\phi(x)\psi(x)dx$$

Hence, if $\W=(2\pi)^{-n/2}\beta(t)\delta_0$ then $(2\pi)^{n/2}\W$ is a cylindrical Wiener process on $L^2(\R^n)$. $\triangle$

## 4.1.5 Complements on a Brownian sheet

- The point of including this section is that it connects Brownian sheets on $[0,\infty)\times\R^n$ (as developed in 4.1.3) with cylindrical Wiener processes on $L^2(\R^n)$ (as developed in 4.1.4).

This section shows that the distributional derivative of a Brownian sheet $B$ on $[0,\infty)\times\R^n$ is "eqaul" to the cylindrical Wiener process $\W$ on $L^2(\R^n)$. That is

$$\frac{\partial^n}{\partial x_1\cdots\partial x_n}B(t,x)=\W(t,x), \ x\in\R^n.$$

- __Def__ A Brownian sheet $B$ on $[0,\infty)\times[0,\infty)^n$ is a Gaussian random field with correlation function

$$(t\wedge s)\prod_j(x_j\wedge y_j), \ \ t,s,x_j,y_j\geq0.$$

Now let $B_l$ be a family of independent Brownian sheets on $[0,\infty)\times[0,\infty)^n$ indexed by the family of all sequences $l=\{l_i\}$ where each $l_i\in\{0,1\}$. Then, for any $t\geq0$ and $x=(x_1,\dots,x_n)\in\R^n$, we define

$$B(t,x)\equiv B_l(t,(-1)^{l_1}x_1,\dots,(-1)^{l_n}x_n)$$

when each $(-1)^{l_i}x_i\geq0$. The resulting object $B$ is called the __Brownian sheet__ on $[0,\infty)\times\R^n$. The Kolmogorov continuity test allows us to assume each realization of $B$ is continuous. Furthermore, $B$ can be thought of as an $L^2_\rho(\R)$-valued Wiener process with weight $\rho$ s.t.

$$\int_{\R^n}|x_1|\cdots|x_n|\rho(x_1,\dots,x_n)dx_1\cdots dx_n<\infty.$$

- __Proposition 4.19__ If $B$ is a Brownian sheet on $[0,\infty)\times\R^n$ then, for any $\phi,\psi\in\mathscr{S}(\R^n)$,

$$\E\left(\frac{\partial^n}{\partial x_1\cdots\partial x_n}B(t),\phi\right)\left(\frac{\partial^n}{\partial x_1\cdots\partial x_n}B(t),\psi\right)=(t\wedge s)\int_{\R^n}\phi(x)\psi(x)dx.$$

# 4.2 Definition of the stochastic integral

The development of the infinite dimensional stochastic integral is analogous to the development of the stochastic integral for finite dimensional stochastic processes. We begin with a definition for elementary processes and progressively extend this definition until it is sufficiently general.

Consider the $U$-valued $Q$-Wiener process $W(t)$ in $(\Omega,\mathscr{F},\mathbb{P})$ and the normal filtration $\{\mathscr{F}_t\}_{t\geq0}$ in $\mathscr{F}$. Assume that

  1. $W(t)$ is $\mathscr{F}_t$-measurable
  2. $W(t+h)-W(t)$ is independent of $\mathscr{F}_t, \ \ \ \ \forall \ h\geq0, \ \ \forall \ t\geq0.$

Then $W(t)$ is called a __$Q$-Wiener process with respect to $\{\mathscr{F}_t\}_{t\geq0}$__. Fix $T<\infty$. 

- __Def__ An $L=L(U,H)$-valued process $\Phi(t), \ t\in[0,T]$ taking only a finite number of values is said to be __elementary__ if $\exists$ a partition $0=t_0<\dots<t_k=T$ and a sequence $\Phi_0,\dots,\Phi_{k-1}$ of $L$-valued random variables s.t. the $\Phi_m$ are $\mathscr{F}_{t_m}$-measurable and bounded (in the sense that $\|\Phi_m\|_L$ is a bounded random variable for each $m$) and $\Phi(t)=\Phi_m$ for $t\in(t_m,t_{m+1}]$, $m=0,\dots,k-1$. For elementary processes $\Phi$ the stochastic integral is defined by

$$\int_0^t\Phi(s)dW(s)\equiv\sum_{m=0}^{k-1}\Phi_m(W_{t_{m+1}\wedge t}-W_{t_m\wedge t})$$

and is denoted by $\Phi\cdot W(t), \ t\in[0,T]$. 

- __Comparison to SDE__ The only difference is that $W(t)$ is a real valued standard Wiener process (so that $Q=1$) and the $\Phi_m$ are real valued random variables. $\triangle$

The subspace $U_0\equiv Q^{1/2}(U)$ of $U$, endowed with the inner product

$$\left<u,v\right>_0\equiv\sum_k\frac{1}{\lambda_k}\left<u,e_k\right>\left<v,e_k\right>=\left<Q^{-1/2}u,Q^{-1/2}v\right>, \ \ u,v\in U_0$$

is a Hilbert space. The space of all Hilbert-Schmidt operators $L_2^0\equiv L_2(U_0,H)$ is a separable Hilbert space with the norm

$$\|\Psi\|_{L_2^0}^2\equiv\sum_{h,k}\left|\left<\Psi \sqrt{\lambda_h}e_h,f_k\right>\right|^2=\sum_{h,k}\lambda_h|\left<\Psi e_h,f_k\right>|^2$$

where $\{\sqrt{\lambda_j}e_j\}$, $\{e_j\}$ and $\{f_j\}$ are complete orthonormal bases in $U_0$, $U$ and $H$ respectively. Let $\Phi(t), \ t\in[0,T]$ be a measurable $L_2^0$-valued process. Define the norms

$$\|\Phi\|_t\equiv\left[\E\int_0^t\|\Phi(s)\|_{L_2^0}^2ds\right]^{1/2}$$

$$=\left[\E\int_0^t\mathrm{Tr}[(\Phi(s)Q^{1/2})(\Phi(s)Q^{1/2})^*]ds\right]^{1/2}, \ \ t\in[0,T].$$

- __Proposition 4.20__ If a process $\Phi$ is elementary and $\|\Phi\|_T<\infty$ then the process $\Phi\cdot W$ is a contiunous square integrable $H$-valued martingale on $[0,T]$ and

$$\E|\Phi\cdot W(t)|^2=\|\Phi\|_T^2, \ \ 0\leq t\leq T.$$

- __Comparison to SDE__ This is analogous to the It&ocirc; isometry which states that if $\Phi(t)$ is elementary in the sense of SDE and if there exists $M>0$ s.t. $|\Phi_m(\omega)|<M$ for each $\omega\in\Omega, \ m=0,\dots,k-1$, then

$$\E\left[\left(\int_0^T\Phi(t)dW(t)\right)^2\right]=\E\left(\int_0^T[\Phi(t)]^2dt\right).$$

Since $\R$ 

- __Remark 4.21__ The stochastic integral is a linear transformation from the space of all elementary process with the norm $\|\cdot\|_T$ into the space $\mathscr{M}_T^2(H)$ of $H$-valued martingales.

The integrands of stochastic intregrals can be regarded as random variables defined on $\Omega_\infty\equiv[0.\infty)\times\Omega$ (or $\Omega_T\equiv[0,T]\times\Omega$) with the $\sigma$-field $\mathscr{B}([0,\infty))\times\mathscr{F}$ (or $\mathscr{B}([0,T])\times\mathscr{F}$). The product of the Lebesgue measure on $[0,\infty)$ (or, $[0,T]$) and the probability measure $\mathbb{P}$ is denoted by $\mathbb{P}_\infty$ (or $\mathbb{P}_T$).

Taking into account the adaptability of processes we choose the $\sigma$-field generated by the adapted simple process ($\mathscr{P}_\infty$ or $\mathscr{P}_T$). The class of processes proper as integrands of stochastic integrals are predictable processes with values in $L_2^0$. That is, they are measurable mappings from $(\Omega_\infty,\mathscr{P}_\infty)$ (or $(\Omega_T,\mathscr{P}_T)$) into $(L_2^0,\mathscr{B}(L_2^0))$.

- __Proposition 4.22__

  1. If a mapping $\Phi$ from $\Omega_T$ into $L$ is $L$-predictable then $\Phi$ is also $L_2^0$-predictable. Hence, elementary processes are $L_2^0$-predictable
  
  2. If $\Phi$ is an $L_2^0$-predictable process s.t. $\|\Phi\|_T<\infty$ then there exists a sequence of elementary processes $\{\Phi_n\}$ s.t. $\|\Phi-\Phi_n\|_T\rightarrow0$ and $n\rightarrow\infty$.

This allows us to extend the stochastic integral to any $L_2^0$-predictable process $\Phi$ s.t. $\|\Phi\|_T<\infty$. These processes form a Hilbert space denoted $\mathscr{N}_W^2(0,T;L_2^0)$ (or just $\mathscr{N}_W^2(0,T)$, or even $\mathscr{N}_W^2$) and by the above proposition, the elementary processes form a dense set in $\mathscr{N}_W^2$. From proposition 4.20, the stochastic integral $\Phi\cdot W$ is an isometry from that dense set into $\mathscr{M}_T^2(H)$. Hence, the definition of the integral ca be extended to all of $\mathscr{N}_W^2$. Furthermore, $\E|\Phi\cdot W(t)|^2=\|\Phi\|_t^2, \ 0\leq t\leq T$ holds true. As a final step, the integral is extended one step further to $L_2^0$-predictable processes satisfying the even weaker condition

$$\mathbb{P}\left(\int_0^T\|\Phi(s)\|^2_{L_2^0}ds<\infty\right)=1.$$

Any such process is called __stochastically integrable__ on $[0,T]$. They form a linear space denoted by $\mathscr{N}_W(0,T;L_2^0$ (or $\mathscr{N}_W(0,T)$, or even $\mathscr{N}_W$). The extension is carried by the __localization procedure__.

- __Lemma 4.24__ Assume that $\Phi\in \mathscr{N}_W^2$ and $\tau$ is an $\mathscr{F}_\tau$-stopping time s.t. $\mathbb{P}(\tau\leq T)=1$. Then

$$\int_0^tI_{[0,\tau]}(s)\Phi(s)dW(s)=\Phi\cdot W(\tau\wedge t), \ \ \ t\in (0,T], \ \mathbb{P}\text{-a.s.} \ \triangle$$

Assuming the above weak condition, define

$$\tau_n\equiv\inf\left\{t\in[0,T]:\int_0^t\|\Phi(s)\|_{L_2^0}^2ds\geq n\right\}$$

with the convention that the infimum of the empty set returns $T$. Then $\{\tau_n\}$ is a sequence s.t.

$$\E\int_0^t\|I_{[0,\tau_n)}(s)\Phi(s)\|_{L_2^0}^2ds<\infty.$$

This implies that stochastic integrals $I_{[0,\tau_n]}\Phi\cdot W(t), \ t\in[0,T]$ are well defined for each $n$. If $n<m$ the $\mathbb{P}$-a.s.

$$I_{[0,\tau_n]}\Phi\cdot W(t)=(I_{[0,\tau_n]}(I_{[0,\tau_m]}\Phi)\cdot W(t))=(I_{[0,\tau_m]}\Phi)\cdot(\tau_n\wedge t), \ \ t\in [0,T].$$

Hence, one can assume the previous expectation holds for all $\omega\in\Omega, \ t\in[0,T], \ n<m$. For any $t\in[0,T]$ define

$$\Phi\cdot W(t)\equiv I_{[0,\tau_n]}\Phi\cdot W(t)$$

where $n$ is an arbitrary natural number s.t. $\tau_n\geq t$. If also $\tau_m\geq t$ and $m>n$ then

$$(I_{[0,\tau_m]}\Phi)\cdot W(t)=(I_{[0,\tau_m]}\Phi)\cdot W(t)(\tau_n\wedge t)=I_{[0,\tau_n]}\Phi\cdot W(t)$$

and thus the above definition is consistent. 

## 4.2.1 Stochastic integral for generalized Wiener processes

Here the definition of the stochastic integral is extended for processes where $Q$ is not necessarily of trace-class.

# 4.4 The It&ocirc; formula

  - Verbatim from the text:

Assume that $\Phi$ is an $L_2^0$-valued process stochastically integrable in $[0,T]$, $\phi$ a $H$-valued predictable process Bochner integrable on $[0,T]$, $\mathbb{P}$-a.s., and $X(0)$ a $\mathscr{F}_0$-measurable $H$-valued random variable. Then the following process

$$X(t)=X(0)+\int_0^t\phi(s)ds+\int_0^t\Phi(s)dW(s), \ t\in[0,T]$$

is well defined. Assume that a function $F:[0,T]\times H\rightarrow\R^1$ and its partial derivatives $F_t,F_x,F_{xx}$, are uniformly continuous on bounded subsets of $[0,T]\times H$.

- __Theorem 4.32__ _Under the above conditions_, $\mathbb{P}$-a.s., _for all_ $t\in[0,T]$

$$F(t,X(t))=F(0,X(0))+\int_0^t\left<F_x(s,X(s)),\Phi(s)dW(s)\right>$$

$$+\int_0^t\Big{\{}F_t(s,X(s))+\left<F_x(s,X(s)),\phi(s)\right>$$

$$\left.+\frac{1}{2}\mathrm{Tr}[F_{xx}(s,X(s))(\Phi(s)Q^{1/2})(\Phi(s)Q^{1/2})^*]\right\}ds$$

- __Interpretation__ The process $X(t)$ is some $H$-valued process. For concreteness $H$ might be the familiar $\R^n$ or $L^2(\R^n)$. However, recall the cylindrical Wiener process takes values in a "higher" Hilbert space (such as $L^2_\rho(\R^n)$). So if $X(t)$ belongs to one of our familiar Hilbert spaces, but we're integrating against a cylindrical Wiener process, we need some transformation $\Phi$ that maps the "misbehaved" cylindrical Wiener process into something more manageable (something $H$-valued in particular). This way both integrals above return $H$-valued processes and, thus, their sum is also an $H$-valued process. This is consistent with the statement that $X(t)$ is $H$-valued. For each $t$, the function $F(t)$ takes values from $H$ and maps them to $\R$ in a sufficiently smooth manner. This allows us to use the "change of variables" formula above (It&ocirc;'s formula). Note that the inner product in this formula is with respect to $H$.

- __Example __ Let $B$ be a Brownian sheet on $[0,\infty)\times\R$. Then, obviously, $B(t)=\int_0^tdB(s)$. Given a nonnegative $\psi\in L^2(\R)$ define $F:L_\psi^2(\R)\rightarrow \R$ by $F(u)=\int_\R \psi(x)u(x)dx$. We should get

$$W(t)=F(B(t))=\int_\R\psi(x)B(t,x)dx,$$

a one dimensional Wiener process. This is obviously the case from the above definition of a Brownian sheet. However, for the sake of applying It&ocirc;'s formula, we note $F_t=0$ and set $\|v\|_{L_\psi^1}\equiv\int v(x)\psi(x)dx$ so that $F_u, F_{uu}$ are given by

$$F_u(v)\equiv \lim_{\epsilon\rightarrow0}\frac{1}{\|\epsilon v\|_{L_\psi^1}}(F(u+\epsilon v)-F(u))$$

$$=\lim_{\epsilon\rightarrow0}\frac{1}{\|\epsilon v\|_{L_\psi^1}}\int_\R\epsilon \psi(x)v(x)dx=1,$$

$$F_{uu}(v)\equiv \lim_{\epsilon\rightarrow0}\frac{1}{\|\epsilon v\|_{L_\psi^1}}(F_u(u+\epsilon v)-F_u(u))=0$$

for each $v\in L_\psi^2$. In this case $X(t)$ is a cylindrical Wiener process and is hence $L_\psi^2$ valued. Also, since $F$ is mapping objects from $L_\psi^2$ to $\R$, we know the inncer product in It&ocirc;'s formula is with respect to $L_\psi^2$. Therefore, applying It&ocirc;'s formula, we get 

$$F(B)=F(B(0))+\int_0^t\left<F_u(B(s)),dB(s)\right>_{L_\psi^2}+\frac{1}{2}\mathrm{Tr}(F_{uu}(B(s))I)ds$$

$$=\int_0^t\left<1,dB(s)\right>_{L_\psi^2}=\int_0^t\int_\R\psi(x)dB(s,x)dx=\int_\R\psi(x)\int_0^tdB(s,x)dx$$

$$=\int_\R\psi(x)B(t,x)dx$$

as desired. $\triangle$

- __Another example __ Now suppose we are working with

$$\mathfrak{n}(t,z)=m(z)\mathfrak{n}(t,z)dt+\eta\mathfrak{n}(t,z)dB(t,z).$$

In this case $\mathfrak{n}(0)=X(0)$ and $\mathfrak{n}(t)=X(t)$ are $L^2(\R)$-valued, $\phi(t)=m\mathfrak{n}(t)$ is also $L^2(\R)$-valued and $\Phi(t):L^2_{\mathfrak{n}(t)}(\R)\rightarrow L^2(\R)$ defined by $B\mapsto\eta\mathfrak{n}(t)B$ for each $t$ converts the cylindrical Wiener process $B(t,z)$ into a $L^2(\R)$-valued random variable. We define $F:L^2(\R)\rightarrow\R$ by $F(v)=\int_\R |v(x)|dx$ so that $F_t=0$ and

$$F_u(v)=\lim_{\epsilon\rightarrow0}\frac{1}{\|\epsilon v\|_1}(F(u+\epsilon v)-F(u))$$

$$=\lim_{\epsilon\rightarrow0}\frac{1}{\|\epsilon v\|_1}\int_\R|\epsilon v(x)|dx=1, \ F_{uu}(v)=0.$$

Then, applying It&ocirc;'s formula,

$$F(\mathfrak{n}(t))=F(\mathfrak{n}(0))+\int_0^t\left<1,\eta\mathfrak{n}(t) dB(s)\right>_{L^2}+\int_0^t\left<1,m(z)\mathfrak{n}(s)\right>ds$$

$$=n(0)+\eta\int_0^tn(s)\int_\R p(s,z)dB(s,z)+\int_0^tn(t)\int_\R m(z)p(s,z)ds$$

$$=n(0)\int_0^tn(s)\overline{m}^{(s)}ds+\eta\int_0^tn(s)\overline{dB(s)}^{(s)}.$$

Thus, the real valued process $n(t)$ satisfies the sde

$$dn=n\tilde{m}(t)dt+\tilde\eta(t) ndW$$

where $W$ is a standard one dimensional Brownian motion, $\tilde m(t)$ is the Malthusian fitness of the whole population (which is the average Malthusian fitness across $z$ at time $t$) and $\tilde\eta(t)$ takes into account that $\overline{dB(t)}^{(t)}$ has variance proportional to $t$, evolving in time. Because of this, $n(t)$ is __not__ a geometric Brownian motion as intuition might suggest.

$$PART \ II: \ SOLUTIONS \ OF \ SPDE$$

# 6 Linear equations with multiplicative noise

## 6.1 Strong, weak, and mild solutions

Let $H$ ($=L^2(\R)$) and $U$ ($=L^2_\rho(\R)$) be Hilbert spaces, $Q$ a self-adjoint nonnegative operator on $U$ and $W$ a $Q$-Wiener process on $U_1$ ($=L^2_\rho(\R)$) $\supset U$ and $U_0=Q^{1/2}U$.

$$\left\{\begin{matrix}dX(t)=AX(t)dt+B(X(t))dW(t) \\ X(0)=\xi\end{matrix}\right.$$

$A:D(A)\subset H\rightarrow H$ the infitesimal generator of a strongly continuous semigroup $S(\cdot)$, $\xi$ an $H$-valued random variable and $B:D(B)\subset H\rightarrow L_2^0=L_2(U_0,H)$.

$$APPENDIX$$

# A.C Nuclear & Hilbert-Schmidt operators

Let $L(E,G)$ be the Banach space of all linear bounded operators from $E$ into $G$ with the supremum norm

$$\|T\|\equiv\sup_{x\in E}\frac{\|Tx\|}{\|x\|}.$$

- __Def__ $T\in L(E,G)$ is __nuclear__ or __trace class__ if there exists sequences $\{a_j\}\subset G, \ \{\phi_j\}\subset E^*$ s.t.

$$\sum_{j=1}^\infty\|a_j\|\|\phi_j\|<\infty$$

and $T$ has the representation $Tx=\sum_ja_j\phi_j(x), \ x\in E$. $\triangle$

The space of all nuclear operators with the norm

$$\|T\|_1\equiv\inf\left\{\sum_j\|a_j\|\|\phi_j\|:Tx=\sum_ja_j\phi_j(x)\right\}$$

is a Banach space denoted as $L_1(E,G)$ or $L_1(E)$ if $E=E$. Let $K$ be another Banach space. If $T\in L_1(E,G)$ and $S\in L_1(G,K)$, then $TS\in L_1(E,K)$ and $\|TS\|_1\leq\|T\|_1\|S\|_1$. If $T\in L_1(U)$ and $\{e_k\}$ is a complete orhonormal system in $U$, then we define

$$\mathrm{Tr}T\equiv\sum_j\left<Te_j,e_j\right>$$

- __Proposition C.3__ A nonnegative operator $T\in L(H)$ is of trace class iff there exists an orthonormal basis $\{e_k\}$ on $H$ s.t.

$$\sum_j\left<Te_j,e_j\right><\infty.$$

When this occurs $\mathrm{Tr}T=\|T\|_1$. $\triangle$

- __Def__ For two separable Hilbert spaces $U_1$ and $U_2$ with complete orthonormal bases $\{e_k\}\subset U_1$ and $\{f_k\}\subset U_2$, a linear bounded operator $T:U_1\rightarrow U_2$ is said to be __Hilbert-Schmidt__ if

$$\sum_k|Te_k|^2<\infty. \ \triangle$$

The space of all Hilbert-Schmidt operators from $U_1$ to $U_2$, equipped with the norm

$$\|T\|_2\equiv\left(\sum_k|Te_k|^2\right)^{1/2}$$

is a separable Hilbert space with the scalar product

$$\left<S,T\right>\equiv\sum_k\left<Se_k,Te_k\right>.$$

- __Notation__ (outer product) For any vectors $a\in U_1$ and $b\in U_2$, the operation $b\otimes a$ denotes the linear operator defined by

$$b\otimes a:U_1\rightarrow U_2, \ h\mapsto \left<a,h\right>b, \ \ h\in U_1. \  \triangle$$

The double sequence $\left\{f_j\otimes e_k\right\}_{j,k\in \mathbb{N}}$ is a complete orthonormal basis in $L_2(E,F)$.

- __Proposition C.4__ Let $U_1,U_2,U_3$ be separable Hilbert spaces. If $T\in L_2(U_1,U_2)$ and $S\in L_2(U_2,U_3)$ then $ST\in L_1(U_1,U_3)$ and

$$\|ST\|_1\leq\|S\|_2\|T\|_2. \ \triangle$$
