---
title: "The Definition of Diffuse Coevolution: novel insights to an old problem"
output: 
  html_document: 
    toc: false
    toc_float: true
    theme: cosmo
    css: style.css
---

<!--
output: 
  html_document:
    toc: true
    toc_float: true
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}


### The distinction between ongoing coevolution and coevolved species/traits

### The evolution of $B_{ij}$

The selection strength $B_{ij}$ that mediates the amount of selection imposed by species $j$ onto species $i$ can vary in time and space. Spatial variation is known as a Thompsonian gradient. This number $B_{ij}(x)$, the strength of biotic selection at location $x$, is a property that corresponds to both species $i$ and species $j$ and is subject to evolution. What determines the evolution of this abstract parameter and how that mechanism can be captured mathematically is not clear as of this moment. This parameter controls the sensitivity of fitness effects to trait differences. Thus, to understand it, we must dive deeper into the life histories and physiologies of the individuals involved on both sides of the interaction.