---
title: "Stochastic Calculus"
author: "Durret"
output: 
  html_document:
    theme: cosmo
    css: style.css
---

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\F}{\mathcal{F}}
\newcommand{\RR}{\mathcal{R}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\ra}{\rightarrow}

# 1. Brownian motion

### _Theorem 1.4_

Let $\Omega_0=\{\omega:[0,\infty)\overset{\omega}{\ra}\R\}$ and $\F_0$ be the $\sigma$-field generated by the finite dimensional sets $\{\omega:\omega(t_i)\in A_i,i=1,\dots,n\}$ where $A_i\in\RR$. For each $x\in\R$ there is a unique probability measure $\nu_x$ on $(\Omega_0,\F_0)$ s.t. $\nu_x(\{\omega:\omega(0)=x\})=1$ and when $0<t_1<\dots<t_n$

$$\nu_x(\{\omega:\omega(t_i)\in A_i\})=\mu_{x,t_1,\dots,t_n}(A_1\times\cdots\times A_n).$$

- Note: $C[0,\infty)\notin\F_0$.

#### 1.1

- Claim: $A\in\F_0$ iff there is a sequence of times $t_1,t_2,\dots\in[0,\infty)$ and a $B\in\RR^{\{1,2,\dots\}}$ s.t. $A=\{\omega:(\omega(t_1),\omega(t_2),\dots)\in B\}$. That is, every event in $\F_0$ depends only on countably many coordinates.




