---
title: "Harmonic Analysis 03-29-19"
output: 
  html_document: 
    toc: false
    toc_float: true
    theme: cosmo
    css: style.css
---

\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\<}{\left<}
\newcommand{\>}{\right>}
\newcommand{\ra}{\rightarrow}
\newcommand{\sinc}{\mathrm{sinc}}
\newcommand{\supp}{\mathrm{supp}}

# From MRA to wavelets:

Need a family $\{\psi_{j,k}\equiv2^{j/2}\psi(2^jx-k)\}_{j,k\in\Z}$ that is an ONB of $L^2(\R)$. This comes from an MRA: 

$$\dots\subset V_{-1}\subset V_0\subset V_1\subset\dots$$

with a scaling function $\varphi$ s.t. $\{\varphi(x-k)\}_{k\in\Z}$ is an ONB of $V_0$. This means that $\{\varphi_{j,k}\}_k$ is an ONB of $V_j$. Furthermore $V_{j+1}=V_j\oplus W_j$; for each $\varphi$ there is a corresponding $\psi$ s.t. $\{\psi_{j,k}\}_k$ is an ONB of $W_j$. Considering all possible $j$; $L^2(\R)=\overline{\bigoplus_j W_j}$ and $\{\psi_{j,k}\}_{j,k}$ is an ONB of $L^2(\R)$.

__Question:__ what is the relationship between $\varphi$ and $\psi$?

__Comment:__ we may think Fourier analysis is outdated given all this modern wavelet stuff. however, the Fourier transform is essential for constructing wavelets.

By the requirements of $\varphi$, we have

$$\int_\R\varphi(x-k)\varphi(x-l)dx=\delta_{kl}.$$

This is equivalent to $\sum_{k\in\Z}|\hat\varphi(\gamma+k)|^2=1$ (for any $\gamma\in\R$) since

__Lemma:__ Let $f\in L^2(\R)$. The family $\{f(x-k)\}_k$ is orthonormal iff

$$\sum_{k\in\Z}|\hat f(\gamma+n)|^2=1, \ \gamma\in\R$$

__Proof:__ Set $\tau_k$ the translation by $k$ operator so that $\tau_k f=f(x-k)$. By change of variables (and translation invariance of Lebesgue integration)

$$\left<\tau_kf,\tau_mf\right>=\left<\tau_{k-m}f,f\right>$$

The orthonormality of $\{\tau_kf\}$ is equivalent to 

$$\left<\tau_kf,f\right>=\delta_0(k)$$

$$=\left<\mathscr F(\tau_kf),\mathscr F(f)\right>=\int_\R\mathscr{F}(\tau_kf)\overline{\mathscr{F}(f)}d\gamma$$

$$=\int_\R e^{-2\pi ik\gamma}\hat f\overline{\hat f}d\gamma=\int_\R e^{-2\pi i k\gamma}|\hat f|^2d\gamma$$

$$=\sum_{n\in\Z}\int_n^{n+1}e^{-2\pi i k\gamma}|\hat f|^2d\gamma=\star$$

Let $\nu=\gamma-n$ for each interval $(n,n+1)$ in the partition of $\R$:

$$\star=\sum_n\int_0^1 e^{-2\pi i k(\nu+n)}|\hat f(\nu+n)|^2d\nu$$

$$=\sum_n\int_0^1 e^{-2\pi i k\nu}|\hat f(\nu+n)|^2d\nu$$

$$=\int_0^1e^{-2\pi i k\nu}\sum_n|\hat f(\nu+n)|^2d\nu=\star$$

The function $F(\nu)\equiv\sum_n|\hat f(\nu+n)|^2$ is 1-periodic and $\star$ calculates the $k$th Fourier coeff of $F(\nu)$ and is equal to $\delta_0(k)$.

Let $h\equiv1$ on $[0,1)$:

$$\hat h(k)=\int_0^1 e^{-2\pi ikt}dt=\left.\frac{e^{-2\pi ikt}}{-2\pi ik}\right|_0^1$$

$$=\frac{1-e^{-2\pi ik}}{2\pi ik}=\delta_0(k)$$

Thus $F=h$ (ae) by the uniqueness of Fourier transform. $\square$

#### Two important properties the scaling function must hold

  i. $\sum_{n\in\Z}|\hat\varphi(\gamma+n)|^2=1$
  
  ii. there is $\{h_k\}$ s.t. $\sum_{k\in\Z}|h_k|^2<\infty$ and
  
  $$\varphi(x)=\sqrt 2\sum_kh_k\varphi(2x-k)=\sum_k h_k\varphi_{1,j}$$

This is because $\varphi\in V_0\subset V_1$ and $\{\varphi_{1,k}\}$ is an ONB of $V_1$. Note $h_k=\left<\varphi,\varphi_{1,k}\right>$.

Take the Fourier transform of $\varphi$

$$\hat\varphi(\gamma)=\sum_k h_k\hat\varphi_{1,k}$$

$$\hat\varphi_{1,k}=\sqrt{2}e^{-2\pi ik\gamma/2}\frac{1}{2}\hat\varphi(\gamma/2)$$

$$=\frac{e^{-2\pi ik\gamma/2}}{\sqrt 2}\hat \varphi(\gamma/2)$$

and thus

$$\hat\varphi(\gamma)=\hat \varphi(\gamma/2)H(\gamma/2)$$

where $H(\gamma)=\frac{1}{\sqrt 2}\sum_kh_ke^{-2\pi ik\gamma}$ is a 1-periodic function, a trigonometric function. This is the transfer function of a low pass filter. This is just property ii. and only requires $\varphi\in V_1$ and thus holds for any $f\in V_1$. The following depends also on property i.

__Lemma:__ Given an MRA with scaling function $\varphi$ and a corresponding filter $H$:

$$|H(\gamma)|^2+|H(\gamma+1/2)|^2=1, \ \ \ \gamma\in\R.$$

__Proof:__  From i. we have $1=\sum_n|\varphi(\gamma+n)|^2$ which is

$$=\sum_n|H(\frac{\gamma+n}{2})|^2|\hat\varphi(\frac{\gamma+n}{2})|^2$$

$$=\sum_{n\text{ odd }}|H(\frac{\gamma+n}{2})|^2|\hat\varphi(\frac{\gamma+n}{2})|^2+\sum_{n\text{ even }}|H(\frac{\gamma}{2})|^2|\hat\varphi(\frac{\gamma}{2}+\frac{n}{2})|^2$$

period 1

$$=|H(\frac{\gamma}{2}+\frac{1}{2})|^2\sum_{n\text{ odd}}|\hat\varphi(\frac{\gamma}{2}+\frac{n}{2})|^2+\sum_{k\in\Z}|H(\gamma/2)|^2|\hat\varphi(k+\gamma/2)|^2$$

$$=|H(\frac{\gamma}{2}+\frac{1}{2})|^2\sum_{k\in\Z}|\hat\varphi(\frac{\gamma+2k+1}{2})|^2+\sum_{k\in\Z}|H(\gamma/2)|^2|\hat\varphi(k+\gamma/2)|^2$$

$$=|H(\frac{\gamma}{2}+\frac{1}{2})|^2\sum_{k\in\Z}|\hat\varphi(\frac{\gamma+1}{2}+k)|^2+\sum_{k\in\Z}|H(\gamma/2)|^2|\hat\varphi(k+\gamma/2)|^2$$

$$=|H(\gamma/2+1/2)|^2+|H(\gamma/2)|^2 \ \ \square$$

Let $f\in V_1$, by the previous argument for $\varphi$

$$\hat f(\gamma)=m_f(\gamma/2)\varphi(\gamma/2)$$

where $m_f$ is of period 1.

__Lemma:__ $f\in W_0$ iff there is $v(\gamma)$ of period one s.t.

$$\hat f(\gamma)=e^{i\pi\gamma}\overline{H(\gamma/2+1/2)}\hat\varphi(\gamma/2)$$

__Proof sketch:__ $f\in W_0$ iff $f\in V_1$ and $f\in {V_0}^\perp$.

  i. since $f\in V_1$, we need to show that the filter $m_f(\gamma)$ satisfies
  
$$m_f(\gamma)=e^{2\pi i\gamma}\sigma(\gamma)\overline{H(\gamma+1/2)}$$

where $\sigma$ is a function of period $1/2$.

  ii. $f\perp V_0$ iff $\left<f,\varphi(x-k)\right>=0$ for $k\in\Z$
  
  $$0=\left<\hat f,\hat \varphi(x-k)\right>=\int_\R\hat f(\gamma)e^{2\pi ik\gamma}\overline{\hat\varphi(\gamma)}d\gamma$$

$$=\int_\R m_f(\gamma/2)\hat\varphi(\gamma/2)\overline{H(\gamma/2)} \ \overline{\hat\varphi(\gamma)}d\gamma$$

$$\dots \ \square$$

__Want:__ to find $\psi$ (the wavelet) s.t. $\{\psi_{j,k}\}$ is an ONB of $L^2(\R)$. Since $\psi\in W_0$, we have

$$\hat\psi(\gamma)=m_\psi(\gamma/2)\hat\varphi(\gamma/2)$$

where $m_\psi(\gamma)=e^{2\pi i \gamma}\sigma(\gamma)\overline{H(\gamma+1/2)}$ where $\sigma$ has period $1/2$.

Applying an above lemma to $m_\psi$ (instead of $H$) we have

$$|m_\psi(\gamma)|^2+|m_\psi(\gamma+1/2)|^2=1.$$

That is, 

$$|\sigma(\gamma)|^2|H(\gamma+1/2)|^2+|\sigma(\gamma+1/2)|^2|H(\gamma)|^2=1.$$

Then $\sigma$ must have modulus $1$. The MRA is given, so $H$ is determined. Pick $\sigma\equiv 1$ and define $\psi\in W_0$ as

$$\hat\psi(\gamma)=m_\psi(\gamma/2)\hat\varphi(\gamma/2)$$

where $m_\psi(\gamma)=e^{2\pi i \gamma}\overline{H(\gamma+1/2)}$.

$$\hat\psi_{0,k}=e^{-2\pi ik\gamma}m_\psi(\gamma/2)\hat\varphi(\gamma/2)$$

and $\psi_{0,k}$ is also in $W_0$ for each $k$.

Let $f\in W_0\implies \ \exists \ v(\gamma)$ of period one s.t.

$$\hat f(\gamma)=v(\gamma)e^{\pi i \gamma}\overline{H(\gamma/2+1/2)}\hat\varphi(\gamma/2)$$

$$v(\gamma)=\sum_{k\in\Z}a_ke^{-2\pi ik\gamma}$$

$$\hat f(\gamma)=\sum_k a_ke^{-2\pi ik\gamma}\hat\psi(\gamma)$$

$$\hat f(\gamma)=\sum_k a_k\hat\psi_{0,k}(\gamma)$$

and thus, $f(x)=\sum_k a_k\psi_{0,k}$ when $f\in W_0$. If $f$ belongs to some other space $W_j$, then $f$ can be written as $f=\sum a_k\psi_{j,k}$.

# 4-10-2019: Expansion using Haar wavelets

__Thm__ Let $f:[0,1]\rightarrow\R$ be cont. Then 

$$f(x)=\left<f,\chi_{[0,1)}\right>\chi_{[0,1)}+\sum_{j=0}^\infty\sum_{k=0}^{2^j-1}\left<f,\psi_{j,k}\right>\psi_{j,k}$$

__Proof:__ THe approximation of $f$ at level $J$ is

$$f_J(x)=a\chi_{[0,1)}(x)+\sum_{j=0}^{J-1}\sum_kd_{j,k}$$

(where the $d_{i,j}$ were found in the previous lecture, which I missed) and

$$a=\int_0^1 f(x)dx=\left<f,\chi_{[0,1)}\right>$$

$$d_{j,k}=\frac{a_{j+1,2k}-a_{j+1,2k+1}}{2}$$
 
and the $a_{j,k}=\int_{k2^{-j}}^{(k+1)2^{-j}}f(x)dx$, which is a sort of average. Then

$$d_{j,k}=\frac{2^{j+1}}{2}\left[\int_{2k2^{j+1}}^{(2k+1)2^{-(j+1)}}f(x)dx-\int_{(2k+1)2^{j+1}}^{(2k+2)2^{-(j+1)}}f(x)dx\right].$$
$$=2^{j/2}\int_{k2^{-j}}^{(k+1)2^{-j}}f\psi_{j,k}(x)dx=2^{j/2}\left<f,\psi_{j,k}\right>.$$

this just comes from $0\leq 2^jx-k<1/2\implies k2^{-j}\leq x<(k+1/2)2^{-j}$ etc. Thus,

$$f_J=\left<f,\chi_{[0,1)}\right>\chi_{[0,1)}+\sum_{j=0}^{J-1}\sum_{k=0}^{2^j-1}2^{j/2}\psi(2^jx-k).$$

Since this is being done on a compact set, $f$ cont implies unif cont. Thus, we simply take the limit $J\rightarrow\infty$.

__Notes:__

  - For Haar wavelets, the lower level of resolution at a discontinuity is equal to the average of the next level of resolution as that discontinuity.

  - This result can be extended from $[0,1]$ to $\R$ simply by taking the lower bounds on $j$ and $k$ in the above sums from $0$ to $-\infty$.
  
  - $j$ represents freq, $k$ represents location (time)




