---
title: "Miscellaneous"
output: 
  html_document: 
    toc: true
    toc_float: true
    theme: cosmo
    css: style.css
---

<!--
output: 
  html_document:
    toc: true
    toc_float: true
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}


These notes are the result of the interplay between my background in mathematics and my development as a theoretical biologist. I have placed them here primarily for my own reference. As I continue to learn and explore I will update these notes with my findings.

## Some Quantitative Genetics

Here I set out to elucidate the mathematics underlying a calculation of mean fitness. This apparently clandestine calculation is the linchpin of a landmark paper in evolutionary theory (Lande 1976). Developing a solid understanding of it will undoubtedly add a handy trick to ones toolkit. I'll admit right here that I leave out some of the finer technical details, but the motivated reader can fill this gap or find the proof elsewhere.

Gaussian functions play a central role in evolutionary theory. Arguably the most successful equation describing the evolution of a population, the breeder's equation, requires a normal phenotypic distribution. Typical notation is $z$ for the phenotype of an individual, $\bar z$ for the mean phenotype of the population, $\sigma^2$ for the phenotypic variance and $\phi$ for the phenotypic density. This provides

$$\phi(z)=\frac{1}{\sqrt{2\pi\sigma^2}}\exp\left(-\frac{(z-\bar z)^2}{2\sigma^2}\right).$$

If there's selection being imposed on the trait then the fitness $W(z)$, which denotes the average fitness of an individual with trait $z$, will not be identically constant. To find the response in mean phenotype to an episode of selection we use the breeder's equation $\Delta\bar z=G\frac{\partial\ln\overline W}{\partial\bar z}$ where $G$ is the additive genetic variance and $\overline W=\int\phi(z)W(z)dz$ is the mean fitness of the population. However, in order to do so we must first calculate $\overline W$. In the case of stabilizing selection, this can be done quite nicely by assuming $W$ is also a Gaussian function of $z$. That is

$$W(z)=\frac{1}{\sqrt{2\pi\omega^2}}\exp\left(-\frac{(z-\theta)^2}{2\omega^2}\right)$$

with $\theta$ being the phenotypic optimum and $\omega^2$ the phenotypic tolerance of selection, which should be thought of as the inverse of the strength of selection. The reason why this calculation is easier with a Gaussian fitness is due to the algebra that Gaussian functions obey. Specifically, the product of two Gaussians is yet another Gaussian. For example

$$W(z)\phi(z)=\frac{C}{\sqrt{2\pi\tilde\sigma^2}}\exp\left(-\frac{(z-\tilde z)^2}{2\tilde\sigma^2}\right),$$

$$\text{where} \ \tilde\sigma^2=\frac{\sigma^2\omega^2}{\sigma^2+\omega^2}, \ \tilde z=\frac{\sigma^2\theta+\omega^2\bar z}{\sigma^2+\omega^2}$$

and $C$ is some constant. What's interesting here is to note that the new parameter $\tilde z$ is a weighted average of $\theta$ and $\bar z$, weighted by the tolerance and variance. It should also be noted that $\tilde\sigma^2<\sigma^2$. One can show that as $\omega^2\rightarrow\infty$, $\tilde z\rightarrow\bar z$ and $\tilde\sigma^2\rightarrow\sigma^2$, in agreement with the concept of $\omega^2$ being the inverse of the strength of selection. With this result we see that $\overline W$ is just the integral of the above product over the whole real line. However, this product is just a scaled version of a probability density, scaled by $C$. Hence, $\overline W=C$. Then we need to calculate $C$, and for this I very briefly introduce the binary operation known as convolution.

The concept of a convolution can be readily captured graphically by visualizing the graphs of two functions $g_1(z)$ and $g_2(z)$ sliding across each other horizontally. We parameterize this sliding by $\tau$ which lives on the real number line. We'll let $g_2$ remain still and slide $g_1$. As $\tau$ runs from each end of the number line visualize the graph of $g_1$ sliding across $g_2$. As this sliding occurs, we accumulate the product of these two functions with an integral in such a way that we integrate out $\tau$. At this point I recommend taking a peek at the <a href="https://en.wikipedia.org/wiki/Convolution">wikipedia</a>. In symbols we denote the convolution between $g_1$ and $g_2$ by $$g_1 \ast g_2$$ and define it as

$$(g_1*g_2)(z)\equiv\int g_1(\tau-z)g_2(z)d\tau.$$

It turns out that $\overline W$ can be seen as the convolution of two functions. Namely $\phi_0(\bar z)\equiv\phi(0)$ and $W_0(\bar z)\equiv W(\bar z)$, the phenotypic density evaluated at zero and the fitness function evaluated at the population mean phenotype respectively. Although $\phi(0)$ and $W(\bar z)$ are technically constants, both of the resulting functions are sensitive to the value of $\bar z$. We could take care by rigorously defining these objects but I'll leave the mathematical formalities out of this discussion. Instead, observe

$$\phi_0*W_0=\int\phi_0(\bar z-\tau)W_0(\tau)d\tau=\star.$$

If we use $z$ instead of $\tau$, this gives

$$\star=\int\phi_0(\bar z-z)W_0(z)dz$$

$$=\int\left[\frac{1}{\sqrt{2\pi\sigma^2}}\exp\left(-\frac{(\bar z-z)^2}{2\sigma^2}\right)\right]
\left[\frac{1}{\sqrt{2\pi\omega^2}}\exp\left(-\frac{(z-\theta)^2}{2\omega^2}\right)\right]dz$$

$$=\int\phi(z)W(z)dz=\overline W.$$

Okay, so $\overline W$ can be written as a convolution, so what? Well it turns out that Gaussian probability densities are closed under convolutions, which is to say that a convolution of two Gaussian densities is yet another Gaussian density. Specifically, if $g_1(z)$ is a Gaussian probability density with mean $\mu_1$ and variance $\sigma_1^2$ and similarly with $g_2(z)$, then $$(g_1 \ast g_2)(z)=g_3(z)$$ is another Gaussian probability density with the mean $\mu_3=\mu_1+\mu_2$ and variance $\sigma_3^2=\sigma_1^2+\sigma_2^2.$ Noting that, as probability densities, $\phi_0$ has mean zero and variance $\sigma^2$ and $W_0$ has mean $\theta$ and variance $\omega^2$, we now calculate $\overline W$ as

$$\overline W=\int\phi(z)W(z)dz=(\phi_0*W_0)(\bar z)$$

$$=\frac{1}{\sqrt{2\pi(\sigma^2+\omega^2)}}\exp\left(-\frac{(\bar z-\theta)^2}{2(\sigma^2+\omega^2)}\right).$$

Denoting the additive genetic variance by $G$, we obtain the response in mean phenotype to $W$ using the breeder's equation

$$\Delta\bar z=G\frac{\partial\ln\overline W}{\partial \bar z}$$

$$=G\frac{\partial}{\partial\bar z}\left[\ln\left(\frac{1}{\sqrt{2\pi(\sigma^2+\omega^2)}}\right)-\frac{(\bar z-\theta)^2}{2(\sigma^2+\omega^2)}\right]$$

$$=G\frac{\theta-\bar z}{\sigma^2+\omega^2}.$$

To summarize the properties of products and convolutions of Gaussians:

$$g_1(z)g_2(z)=Cg_3(z), \text{ where } \mu_3=\frac{\sigma_1^2\mu_2+\sigma_2^2\mu_1}{\sigma_1^2+\sigma_2^2},
 \ \sigma_3^2=\frac{\sigma_1^2\sigma_2^2}{\sigma_1^2+\sigma_2^2},$$ 
 
$$C=\int g_1g_2dz=\frac{1}{\sqrt{2\pi(\sigma_1^2+\sigma_2^2)}}\exp\left(-\frac{(\mu_1-\mu_2)^2}{2(\sigma_1^2+\sigma_2^2)}\right).$$

 
$$\prod_{i=1}^{n-1}g_i(z)=C'g_n(z), \text{ where } C'=\int\prod_{i=1}^{n-1}g_idz,$$

$$\mu_n=\frac{\sum_{i=1}^{n-1}\mu_j\prod_{j\neq i}\sigma_j^2}{\sum_{i=1}^{n-1}\prod_{j\neq i}\sigma_j^2}, \ 
\sigma_n^2=\frac{\prod_{i=1}^{n-1}\sigma_i^2}{\sum_{i=1}^{n-1}\prod_{j\neq i}\sigma_j^2}$$
 
$$(g_1*g_2)(z)=g_3(z), \text{ where } \mu_3=\mu_2+\mu_1, \ \sigma_3^2=\sigma_1^2+\sigma_2^2.$$


## Linearization of a Pop Gen Model

Here I cover a way to linearize a simple model of genetic selection. We assume a haploid population with two alleles, $A_1$ and $A_2$, having the frequencies $p$ and $q=1-p$ and fitnesses $W_1$ and $W_2$ respectively. Then $\overline W=pW_1+qW_2$ and the change in allele frequency of $A_1$ is (ignoring all other processes)

$$\Delta p=pq\frac{\partial\ln\overline W}{\partial p}, \ \text{with} \ \overline W=pW_1+qW_2$$

The resulting dynamics are clearly nonlinear, but are they truly nonlinear or is this due to the fact that the state space is restricted to the open unit interval? If we stretch the unit interval across the whole real line, maybe the dynamics will become linear. To find out we define $x\equiv\ln\left(\frac{p}{q}\right)$ ($x$ is called the [logit](https://en.wikipedia.org/wiki/Logit) of $p$) and calculate $\Delta x$. For clarity I will write $D_p$ in place of $\frac{\partial}{\partial p}$.

$$\Delta x=x'-x=\ln\left(\frac{p'}{q'}\right)-\ln\left(\frac{p}{q}\right)=\ln\left(\frac{p'q}{q'p}\right)$$

$$\implies\exp(\Delta x)=\frac{p+\Delta p}{q-\Delta p}\frac{q}{p}=\frac{1+qD_p\ln\overline W}{1-pD_p\ln\overline W}$$

$$=\frac{\overline W+qD_p\overline W}{\overline W-pD_p\overline W}=\frac{\overline W+(1-p)\left(W_1-W_2\right)}{\overline W-p\left(W_1-W_2\right)}=\frac{W_1}{W_2}$$

$$\implies \Delta x=\ln\left(\frac{W_1}{W_2}\right).$$

Hence, the dynamics stretched onto the whole real line are not only linear, but constant.
