---
title: "Evolution"
output: 
  html_document: 
    toc: false
    toc_float: true
    theme: cosmo
    css: style.css
---

<!--
output: 
  html_document:
    toc: true
    toc_float: true
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\n}{\mathfrak{n}}

In the first half of this document we assume asexual reproduction and perfect heritability in order to simplify our derivations. It turns out that many of the results proven extend to identical, or very similar, results for the cases of sexual reproduction and imperfect heritability.

## Populations of Types

In terms of modelling, a population can be very abstract. Its concept is not restricted to a set of living things, as in the biological concept of a population. Here a population can be a set of biological populations, a set of species, replicating molecules, franchises, languages and so on. The members of the population may not be uniform, but can consist of various different types. For example, we can consider populations of individuals categorized by their phenotype or populations of species categorized by clades. We now derive how the distribution of types within a population fluctuates due to differential fitness, ie, selection.

### A finite number of types

#### Dynamics in continuous time

Consider a population of $T$ different types, each type $\gamma$ with $\n_t(\gamma)$ individuals at time $t$. If we denote $\phi_t(\gamma)$ to be the proportion of individuals within the whole population of type $\gamma$ at time $t$ among the population, we have $\phi_t(\gamma)=\frac{\n_t(\gamma)}{n_t}$ where $n_t=\sum_{\gamma=1}^T\n_t(\gamma)$. Denote the expected fitness of each individual of type $\gamma$ as $W_t(\gamma)$ and assume individuals of type $\gamma$ only produce other individuals of type $\gamma$. That is, the type of an individual is a perfectly heritable trait. Then, assuming reproduction events are distributed uniformly across generations, focusing on expected dynamics and adopting the notation $D_t$ in place of $\frac{d}{dt}$, we have (from our notes on population dynamics)

$$D_tn_t=D_t\sum_\gamma\n_t(\gamma)=\sum_\gamma\n_t(\gamma)\ln W_t(\gamma)=\overline{\ln W_t}n_t.$$

$$D_t\phi_t(\gamma)=D_t\frac{\n_t(\gamma)}{n_t}=\frac{n_tD_t\n_t(\gamma)-\n_t(\gamma)D_tn_t}{n_t^2}$$

$$=\frac{\n_t(\gamma)\ln W_t(\gamma)-\n_t(\gamma)\overline{\ln W_t}}{n_t}=\phi_t(\gamma)\para{\ln W_t(\gamma)-\overline{\ln W_t}}.$$

From here I will use the notation $m_t(\gamma)=\ln W_t(\gamma)$ and $\bar m_t=\overline{\ln W_t}$. Using these symbols, we have

$$D_t\phi_t=\phi_t(m_t-\bar m_t)$$

which is known as the _replicator equation_ in evolutionary game theory (see [Nowak & Page 2002](https://doi.org/10.1006/jtbi.2002.3112)). In general, we can solve for $\phi_t(\gamma)$ using

$$\phi_t(\gamma)=\phi_0(\gamma)\exp\left(\int_0^t m_s(\gamma)-\bar m_sds\right).$$

Just as a sanity check, we have

$$D_t\n_t=n_tD_t\phi_t+\phi_tD_tn_t$$

$$=n_t\phi_t\para{m_t-\bar m_t}+\phi_tn_t\bar m_t=n_t\phi_tm_t=\n_tm_t.$$

#### Dynamics in discrete time

$$n_{t+1}=\sum_\gamma \n_{t+1}(\gamma)=\sum_\gamma W_t(\gamma)\n_t(\gamma)=\frac{n_t}{n_t}\sum_\gamma W_t(\gamma)\n_t(\gamma)$$

$$=n_t\sum W_t(\gamma)\frac{\n_t(\gamma)}{n_t}=n_t\sum W_t(\gamma)\phi_t(\gamma)=n_t\overline{W}_t$$

$$\phi_{t+1}(\gamma)=\frac{\n_{t+1}(\gamma)}{n_{t+1}}=\frac{\n_t(\gamma)W_t(\gamma)}{n_t\overline{W}_t}=\phi_t(\gamma)\frac{W_t(\gamma)}{\overline{W}_t}$$

$$\implies\phi_{t+1}(\gamma)-\phi_t(\gamma)=\para{\frac{W_t(\gamma)}{\overline{W}_t}-1}\phi_t(\gamma)$$

- Neat Observation 1: Compare the above to the Bayesian update; Given a hypothesis $H_n(x)$ and a likelihood $L(x)$, Bayes theorem provides the updated hypothesis $H_{n+1}$ as

$$H_{n+1}(x)=\frac{H_n(x)L(x)}{\int H_n(x)L(x)dx}=H_n(x)\frac{L(x)}{\overline L}$$

- Neat Observation 2: The fundamental theorem of calculus states

$$\int_{t_0}^{t_1}D_sn_sds=n_{t_1}-n_{t_0}.$$

Thus

$$\Delta n_t=n_{t+1}-n_t=\int_t^{t+1}D_sn_sds$$

$$=\int_t^{t+1}\bar m_sn_sds.$$

### Infinite number of types

We now consider dynamics in the case where the set of types is identified with the real line $\R$. Since each individual is associated with one value in $\R$, a finite population will be reflected by a finite subset of $\R$. Since we are not yet considering processes that generate new types, the situation reduces to a population with a finite number of types. We must therefore treat the case of an uncountably infinite population where each value in $\R$ has a density (as opposed to abundance) in the population. In this case we denote the types by $z\in\R$ (as opposed to $\gamma$) and their density by $\phi_t(z)$ at time $t$. Since the result

$$D_t\phi_t(z)=\phi_t(z)(m_t(z)-\bar m_t)$$

is independent of the population size $n_t$, this formula holds for $n_t\rightarrow\infty$. In what follows, the above equation is the key tool for deriving our formulas of evolutionary dynamics.

## Response in Mean and Variance

For the sake of simplicity, we begin with results for a continuum of types taking values in $\R$ (and hence $n_t=\infty$). Any quantity $Q(z)$ that satisfies

$$\int_\R |Q(z)|\phi_t(z)dz<\infty$$

is said to have a finite populational average. We denote this average by

$$\overline{Q}_t\equiv\int_\R Q(z)\phi_t(z)dz.$$

We will always assume both Wrightian and Malthusian fitnesses have finite populational averages. We denote by $\bar z_t$ the average value of the population at time $t$ and $\sigma_t^2$, an exception to our notation, the variance of values at time $t$. That is, we make the following definitions

$$\bar z_t\equiv\int_\R z\phi_t(z)dz, \ \ \ \sigma_t^2\equiv\int_\R(\bar z_t-z)^2\phi_t(z)dz.$$

Clearly, we will be assuming the mean and variance remain finite in our populations. Using this notation along with the above results and assumptions we can derive dynamics for the mean and variance of values in a population as follows

### Continuous Time

$$D_t\bar z_t=D_t\int_\R z\phi_t(z)dz=\int_\R z D_t\phi_t(z)dz=\int_\R z(m_t(z)-\bar m_t)\phi_t(z)dz$$

$$=\overline{zm_t}-\bar z\bar m_t=\boxed{\Cov(z,m_t)}$$

$$D_t\sigma_t^2=D_t\int_\R (\bar z_t-z)^2\phi_t(z)dz=\int_\R 2(\bar z_t-z)\phi_t(z)D_t\bar z_t+(\bar z_t-z)^2D_t\phi_t(z)dz$$

$$=\int_\R(\bar z_t-z)^2(m_t(z)-\bar m_t)\phi_t(z)dz=\overline{(\bar z_t-z)^2m_t}-\overline{(\bar z_t-z)^2}\bar m_t$$

$$=\boxed{\Cov((\bar z_t-z)^2,m_t)}.$$

#### _Gaussian population_

We have

$$\phi_t(z)=\frac{1}{\sqrt{2\pi\sigma_t^2}}\exp\left(-\frac{(\bar z_t-z)^2}{2\sigma_t^2}\right).$$

With this information we can use Fubini's theorem (since $\int|m_t\phi_t|<\infty$) to state

$$\frac{\partial\bar m_t}{\partial\bar z_t}
=\int_\R\frac{\partial}{\partial\bar z_t}m_t(z)\phi_t(z)dz$$

$$=\int_\R m_t\frac{\partial\phi_t}{\partial\bar z_t}+\frac{\partial m_t}{\partial\bar z_t}\phi_tdz$$

$$=\int_\R m_t\frac{z-\bar z_t}{\sigma_t^2}\phi_tdz+\overline{\frac{\partial m_t}{\partial\bar z_t}}$$

$$=\frac{\overline{m_tz_t}-\bar m_t\bar z_t}{\sigma_t^2}+\overline{\frac{\partial m_t}{\partial\bar z_t}}$$

$$=\frac{1}{\sigma_t^2}\Cov(z,m_t)+\overline{\frac{\partial m_t}{\partial\bar z_t}}$$

$$=\frac{1}{\sigma_t^2}\frac{d\bar z_t}{dt}+\overline{\frac{\partial m_t}{\partial\bar z_t}}.$$

Hence, for Gaussian populations,

$$\boxed{\frac{d\bar z_t}{dt}=\sigma_t^2\left(\frac{\partial\bar m_t}{\partial\bar z_t}-\overline{\frac{\partial m_t}{\partial\bar z_t}}\right)}.$$

We can perform a similar maneuver to find

$$\frac{\partial\bar m_t}{\partial\sigma_t^2}
=\int_\R m_t\frac{\partial\phi_t}{\partial\sigma_t^2}+\frac{\partial\bar m_t}{\partial\sigma_t^2}\phi_tdz$$

$$=\int_\R m_t\frac{(z-\bar z_t)^2-\sigma_t^2}{2\sigma_t^4}\phi_tdz
+\overline{\frac{\partial m_t}{\partial\sigma_t^2}}$$

$$=\frac{\Cov((z-\bar z)^2,m_t)}{2\sigma_t^4}+\overline{\frac{\partial m_t}{\partial\sigma_t^2}}$$

$$=\frac{1}{2\sigma_t^4}\frac{d\sigma_t^2}{dt}+\overline{\frac{\partial m_t}{\partial\sigma_t^2}}$$

which implies

$$\boxed{\frac{d\sigma_t^2}{dt}=2\sigma_t^4\left(\frac{\partial\bar m_t}{\partial\sigma_t^2}
-\overline{\frac{\partial m_t}{\partial\sigma_t^2}}\right)}.$$

These results are very convenient, and often times natural populations obey normality, although a suitable transformation may be required (especially a log-transform for non-negative traits such as height). However, to follow mathematical rigor, there is no gurantee that the distribution remains Gaussian after selection has acted. In fact, we can show that this only only holds when $W_t(z)$ is either Gaussian or exponential with respect to $z$. That is, $W$ is either of the form

$$W_t(z)=C_t\exp\left(-\frac{(z-\theta_t)^2}{2\omega_t^2}\right)$$

or

$$W_t(z)=C_t\exp\left(\nu_t z\right).$$

The latter choice has the disadvantage of not being bounded, but makes a decent candidate for unconstrained directional selection. For the first option, one finds

$$\bar m_t=\int_\R \ln C_t-\frac{(z-\theta_t)^2}{2\omega_t^2}\phi_tdz$$

$$=\ln C_t-\frac{(\bar z_t-\theta_t)^2+\sigma_t^2}{2\omega^2}.$$

Hence

$$\frac{d\bar z_t}{dt}=\frac{\sigma_t^2}{\omega_t^2}(\theta_t-\bar z_t)$$

$$\frac{d\sigma_t^2}{dt}=-\frac{\sigma_t^2}{\omega_t^2}\sigma_t^2.$$

Repeating for the model of directional selection, one finds

$$\bar m_t=\int_\R \ln C_t+\nu_t z\phi_tdz=\ln C_t+\nu_t\bar z_t$$

$$\frac{d\bar z_t}{dt}=\sigma_t^2\nu_t$$

$$\frac{d\sigma_t^2}{dt}=0.$$

Thus, we have some first results showing qualitative differences in the dynamics of variation.

These results depend on more than the assumptions of Gaussian populations and fitness taking one of the two forms mentioned above. They also require perfect heritability so that phenotypic variation and additive genetic variation are equivalent. Along these lines, mutation is also ignored, which explains why these results indicate phenotypic variance never increases. We will relax these assumptions later using the notion of a breeding value for continuous characters. Depending on the mating structure, distribution of mutations and so on, we will gain a more complete picture of the dynamics of the distribution of phenotypes within a population. For now, we conclude our results focusing solely on selection with analogs in discrete time.

### Discrete Time

$$\Delta\bar z_t=\bar z_{t+1}-\bar z_t=\int_\R z\phi_{t+1}(z)dz-\int_\R z\phi_t(z)dz=\int_\R z\para{\frac{W_t(z)}{\overline{W}_t}-1}\phi_t(z)dz$$

$$=\boxed{\frac{1}{\overline {W}_t}\Cov(z,W_t)}$$

$$\Delta\sigma_t^2=\sigma^2_{t+1}-\sigma^2_t=\int_\R (z-\bar z_{t+1})^2\phi_{t+1}(z)dz-\int_\R (z-\bar z_t)^2\phi_t(z)dz$$

$$=\int_\R \para{(z-\bar z_{t+1})^2\frac{W_t(z)}{\overline{W}}-(z-\bar z_t)^2}\phi_t(z)dz$$

$$=\int_\R \para{(z-\bar z_t-\Delta\bar z_t)^2\frac{W_t(z)}{\overline{W}}-(z-\bar z_t)^2}\phi_t(z)dz=\star$$

$$(z-\bar z_t-\Delta\bar z_t)^2\frac{W_t(z)}{\overline{W}}-(z-\bar z_t)^2$$

$$=(z-\bar z_t)^2\para{\frac{W_t(z)}{\overline{W}_t}-1}+\para{(\Delta\bar z_t)^2-2(z-\bar z_t)\Delta\bar z_t}\frac{W_t(z)}{\overline{W}_t}$$

$$\star=\frac{1}{\overline W}\Cov\left\}(\bar z_t-z)^2,W_t\right\}+(\Delta\bar z_t)^2-2\Delta\bar z_t\para{\frac{\overline{z W_t}}{\overline{W_t}}-\bar z_t}$$

$$=\frac{1}{\overline W}\Cov\left\{(\bar z_t-z)^2,W_t\right\}+(\Delta\bar z_t)^2-2\Delta\bar z_t\para{\frac{\Cov(z,W_t)+\bar z_t\overline{W}_t}{\overline{W_t}}-\bar z_t}$$

$$=\boxed{\frac{1}{\overline W}\Cov\left\{(\bar z_t-z)^2,W_t\right\}-(\Delta\bar z_t)^2}$$

#### _Gaussian population_

$$\frac{\partial\ln\overline{W}_t}{\partial\bar z_t}=\frac{1}{\overline{W}_t}\frac{\partial \overline{W}_t}{\partial \bar z_t}$$

$$=\frac{1}{\overline{W}_t}\int_\R W_t\frac{\partial\phi_t}{\partial\bar z_t}+\frac{\partial W_t}{\partial\bar z}\phi_tdz$$

$$=\frac{1}{\overline{W}_t}\left(\int_\R W_t\frac{z-\bar z_t}{\sigma_t^2}\phi_tdz+\overline{\frac{\partial W_t}{\partial\bar z_t}}\right)$$

$$=\frac{1}{\overline{W}_t}\left(\frac{\Cov(z,W_t)}{\sigma_t^2}+\overline{\frac{\partial W_t}{\partial\bar z_t}}\right).$$

$$=\frac{1}{\sigma^2}\Delta\bar z_t+\frac{1}{\overline{W}_t}\overline{\frac{\partial W_t}{\partial\bar z_t}}$$

Hence

$$\boxed{\Delta\bar z_t=\frac{\sigma_t^2}{\overline{W}_t}\left(\frac{\partial\overline{W}_t}{\partial\bar z_t}-\overline{\frac{\partial W_t}{\partial\bar z_t}}\right)}.$$

Now for $\sigma_t^2$

$$\frac{1}{\overline{W}_t}\frac{\partial\overline{W}_t}{\partial\sigma_t^2}
=\frac{1}{\overline{W}_t}\int_\R W_t\frac{\partial\phi_t}{\partial\sigma_t^2}+\frac{\partial W_t}{\partial\sigma_t^2}\phi_tdz$$

$$=\frac{1}{\overline{W}_t}\left(\int_\R W_t\frac{(\bar z-z)^2-\sigma_t^2}{2\sigma_t^4}dz+\overline{\frac{\partial W_t}{\partial\sigma_t^2}}\right)$$

$$=\frac{1}{\overline{W}_t}\left(\frac{\Cov\left\{(\bar z-z)^2,W\right\}}{2\sigma_t^4}+\overline{\frac{\partial W_t}{\partial\sigma_t^2}}\right)$$

$$=\frac{\Delta\sigma_t^2+(\Delta\bar z_t)^2}{2\sigma_t^4}+\frac{1}{\overline{W}_t}\overline{\frac{\partial W_t}{\partial\sigma_t^2}}$$

Hence

$$\boxed{\Delta\sigma_t^2=\frac{2\sigma_t^4}{\overline{W}_t}\left(\frac{\partial\overline{W}_t}{\partial\sigma_t^2}-\overline{\frac{\partial W_t}{\partial\sigma_t^2}}\right)-(\Delta\bar z_t)^2}$$

Showing connection between cont and disc times

Assuming $\sigma_t^2=\sigma^2$, $\theta_t=\theta$ and $\omega_t^2=\omega^2$

$$\Delta\bar z_t=\int_t^{t+1}\frac{d\bar z_s}{ds}ds=\frac{\sigma^2}{\omega^2}($$

## The inseparability of evolution and ecology

As we saw, the evolutionary dynamics of a population were derived from the demographic dynamics of the various types within that population. The two sets of dynamics are entangled via fitness. The population as a whole grows as a function of mean fitness while evolution occurs due to the structure of fitness across types, which in turn manipulates mean fitness and hence the dynamics of demography. Hence, one cannot, in general, have evolution without ecology. Of course, in the case of infinite populations, this argument in vacuous. However, I know of no such populations.

## Reproduction

So far I have assumed that inheritance is perfect so that offspring resemble their parents exactly. The existence of sex in the above theory is ambiguous. One could hold the perspective that individuals reproduce asexually or that individuals only mate with only other individuals of their exact type, creating $2\W$ offspring, one set for each member of the mating pair. Yet another way to look at this theory is that it tracks just one gender so that, for example, daughters resemble their mothers perfectly and their fathers make no contribution to their type. Here I will explicitly model sexual reproduction by beginning with random mating. I will first focus on discrete time dynamics for a continuum of types indexed by $\R$. Later I will extend these results to continuous time dynamics and a more general mating pattern that encompasses everything from absolutely assortative mating to random mating to absolutely disassortative mating.

### Pure Random Mating

Consider a population of $N$ hermaphroditic individuals with traits $\{z_1,\dots,z_N\}$. The trait of an offspring $z_o$ will be its midparent. Because the population is finite, there is a finite number $k$ of possible midparents. Denote this set of midparents by $M=\{m_1,\dots,m_k\}$. Each midparent has a particular probability of occuring which is the probability of choosing two parents whose average is equal to that midparent. Denote $w_i$ for the probability of midparent $m_i$. Assuming perfect heritability, the offspring trait distribution will have $w_i$ as its distribution.

Our goal is calculate a formula for $w_i$. Let $P_i$ be the set of all parental phenotypes whose average with some parental phenotype (possibly itself) is $m_i$. If we think of $m_i$ as the result of drawing two random parents (with replacement) then the $m_i$ will be distributed as a multinomial with $N$ categories and 2 trials. Writing $\phi_p(z)$ as the frequency of trait $z$ in the parental distribution we have

$$w_i=2\sum_{\substack{z\in P_i}}\phi_p(z)\phi_p(2m_i-z).$$

To simplify our calculations, assume an infinite population so that the set of possible midparents becomes uncountably infinite and their distribution becomes continuous instead of discrete. We will adjust our notation to reflect this so that $w(m)$ is the probability density for the offspring trait $m$ (which in this case is equivalent to the midparent, hence the $m$) whose domain is now all of $\R$. The above summation becomes the integral

$$w(m)=2\int_\R \phi_p(z)\phi_p(2m-z)dz.$$

Assuming the parental population is distributed normally with mean $\mu$ and variance $\sigma^2$, we have

$$w(m)=2\int_\R
\frac{1}{\sqrt{2\pi\sigma^2}}\exp\para{-\frac{(\mu-x)^2}{2\sigma^2}}
\frac{1}{\sqrt{2\pi\sigma^2}}\exp\para{-\frac{(\mu-(2m-x))^2}{2\sigma^2}}
dx$$

$$=2\int_\R
\frac{1}{\sqrt{2\pi\sigma^2}}\exp\para{-\frac{(\mu-x)^2}{2\sigma^2}}
\frac{1}{\sqrt{2\pi\sigma^2}}\exp\para{-\frac{((2m-\mu)-x)^2}{2\sigma^2}}
dx$$

$$=2\int_\R
\frac{1}{\sqrt{4\pi\sigma^2}}\exp\para{-\frac{(2\mu-2m)^2}{4\sigma^2}}
\frac{1}{\sqrt{2\pi\sigma^2}}\exp\para{-\frac{(m-x)^2}{2\sigma^2}}
dx$$

$$=\frac{1}{\sqrt{\pi\sigma^2}}\exp\para{-\frac{(\mu-m)^2}{\sigma^2}}.$$

Hence, with just random mating $\Delta\mu=0$ and $\Delta\sigma^2=-\frac{\sigma^2}{2}$.

### Assortative and Negative Mating

The key here is to define assortative mating as a positive correlation between the types of mating pairs. We might jump to disassortative mating as a negative correlation between the types of mating pairs but this is not quite right. If mating pairs are negatively correlated, then when the phenotype of one member of the pair tends to be large, the phenotype of the other member tends to be small. So this is a restricted notion of disassortative mating. I'll attempt to work out a more general picture of disassortative mating in the next section. For now, instead of referring to the situation of negative correlation disassortative mating, I'll refer to it as negative mating. I'll use $\rho$ to denote the correlation between types of mating pairs.

Let $X$ and $Y$ denote the phenotypes of a randomly chosen mating pair. I'll write $\bar z$ as the mean phenotype of their distribution and $\sigma^2$ for the phenotypic variance. If we assume it's offspring $Z$ is the midparent then $Z=\frac{X+Y}{2}$. The mean of the offpsring population will be $\E(Z)=\frac{1}{2}(\E(X)+\E(Y))=\bar z$. Hence, this model of mating does not perturb the mean phenotype. However 

$$\Var(Z)=\frac{1}{4}\para{\Var(X)+\Var(Y)+2\Cov(X,Y)}=\frac{1}{2}\para{\sigma^2+\Cov(X,Y)}$$

Since $\Cov(X,Y)=\rho\sigma^2$ we have $\Var(Z)=\frac{\sigma^2}{2}(1+\rho)$. When $\rho=0$ mating between types occurs at random and we get the same result as above. When $\rho=1$, we have perfectly assortative mating and the phenotypic variance remains the same. When $\rho=-1$ the variance disappears as each mating pair will consist of exactly complementary types and thus all offspring will have the same phenotype.

We can use this result to derive dynamics of the phenotypic distribution $\phi_t$, but before we dive into the general case, let's consider the case where both parental and offspring phenotypic distributions are normal. Then, knowing from statistics that the normal distribution is [self-conjugate](https://en.wikipedia.org/wiki/Conjugate_prior), we can hypothesize the dynamics to take the form

$$\phi_{t+1}=\frac{\psi\phi_t}{\int_\R\psi\phi_tdz}$$

where $\psi$ is a normal density. If $\psi$ has mean $\mu$ and variance $\nu^2$, then we can use the handy fact that $\phi_{t+1}$ will be a normal density with the respective mean and variance

$$\frac{\nu^2\bar z+\sigma^2\mu}{\nu^2+\sigma^2}, \ \frac{\nu^2\sigma^2}{\nu^2+\sigma^2}.$$

Since we know the mean doesn't change under this model of reproduction it must be that $\mu=\bar z$. We also know the offspring variance and setting it equal to the above result gives

$$\frac{\sigma^2}{2}(1+\rho)=\frac{\nu^2\sigma^2}{\nu^2+\sigma^2}.$$

Solving for $\nu^2$ provides

$$\frac{2}{1+\rho}=1+\frac{\nu^2}{\sigma^2}\implies\frac{1-\rho}{1+\rho}\sigma^2=\nu^2.$$

The continuous time version of the above Bayesian update is the replicator equation;

$$\frac{d\phi_t}{d t}=\phi_t(\ln\psi_t-\overline{\ln\psi_t}).$$

#### Incorporating Heritability

Use breeding values.

### Other Mating Patterns

Including disassortative mating.

### Mating Pattern as Phenotype

Mating preference could be a trait that evolves within a population.

### Dioecy

I've been assuming these populations are hermaphroditic. Would about a two-sex system?

### Particulate Inheritance

A little excerpt from [Warren J. Ewens](http://www.springer.com/us/book/9780387201917):

"It is the the 'quantal' nature of the gene that leads to the stability behavior described by the Hardy-Weinberg law. It is thus interesting that the year in which the Mendelia theory was rediscovered, 1900, was the same year as the introduction of the quantum theory in physics. Both theories have been fundamental and crucial in their respective spheres. One can even claim that if there is intelligent life, that is, life that has evolved via natural selection, elsewhere in the universe, the hereditary mechanism involved must be a quantal, maybe a Mendelian, one, since otherwise it is not clear how the variation necessary for evolution by natural selection can be maintained."

From this very insightful quote we see one enormous gap in the thoery developed here; it lacks a mechanism of particulate inheritance. In fact, the engine driving the result of reproduction here is blending inheritance. However, it is widely known that the combination of blending inheritance and random mating reduces the variance of a population far too quickly.

<!--

So far I have been using a model of blending inheritance to calculate the phenotype of the offspring. This model of inheritance has been argued against from it's inception going back to the days of Darwin. Yet it remains at the core of the modern evolutionary theory of continuous traits, quantitative genetics. The main issue with this model is that, under pure random mating, the variance of a phenotype in a population is halved each generation, causing rapid degradation in diversity. One can combat this decay by incorporating mutation, as done below. However, this requires a rate of mutation that is far too rapid than what has been observed empirically. This problem is said to have been solved independtly by G.H. Hardy and Wilhelm Weinberg in 1908. In their particulate theory of inheritance diversity is maintained in a randomly mating population. It seems to me that most phenotypes can be described with a continuum and are more explicitly the target of natural selection as opposed to the genotype. On the other hand, since sexual reproduction inevitably involves the combination of gametes, it seems that the genotype generally has more power in this realm over the phenotype. Here I'll begin my naive attempt to combine these two insights. This is a first pass, writing down my thoughts as they form, so you may wish to look away until this section has reached maturity.

My efforts here will focus on diploids. Let $\Z^2$ be the index set for all possible genotypes and $\R$ for all possible phenotypes. Each individual $i$ is represented by a genotype-phenotype pair $(\gamma_i,z_i)\in\Z^2\times\R$. Note that $\gamma_i$ itself has two unordered components, which I denote by $\gamma_i^1$ and $\gamma_i^2$ and define $\dot\gamma_i\equiv\frac{\gamma_i^1+\gamma_i^2}{2}$. This allows us to capture genotype of a diploid with a single number that can then be related to the phenotype. I assume a linear genotype phenotype map such that $z_i\sim\mathcal{N}(\alpha\dot\gamma_i+\beta,\eta^2)$ for some fixed $\alpha,\beta\in\R$. Since it is certainly possible that the relationship between the phenotype and genotype can change depending on the environment (plasticity) and even evolve with time (so that $\alpha$ and $\beta$ are themselves phenotypes that may or may not be predicted by genotypes) this assumption would need to be relaxed for a more satisfying theory. But let's keep things simple for now.

Denote by $(\Gamma,Z)$ a random genotype-phenotype pair distributed across the population so that $\omega$ represents the individual and $\Omega$ is the set of all individuals $(N=|\Omega|)$. If $\Gamma$ significantly correlates with $Z$, I'll say that $Z$ is a heritable trait. For the mating pair of individuals $i$ and $j$ I'll denote their offspring genotype by $\gamma_{ij}$, which will be uniformly distributed over the four possible pairs $(\gamma_i^1,\gamma_j^1)$, $(\gamma_i^1,\gamma_j^2)$, $(\gamma_i^2,\gamma_j^1)$ and $(\gamma_i^2,\gamma_j^2)$. 

Now that the basic rulese have been set in place, let's play a little game. Let's pretend that we're alien scientists and on our world the genotypes of living things translate directly to elements of $\Z^2$. Suppose for some reason we know $\alpha$ and $\beta$ precisely and that genotypes tend to be easier to observe than phenotypes. Say we go out and sample a population and estimate the distribution of $\Gamma$. From this knowledge we can predict the distribution of $Z$. 

$$\E(Z)=\frac{1}{N}\sum_i(\alpha\dot\gamma_i+\beta)=\frac{\alpha}{2N}\sum_{ij}\gamma_i^j+\beta$$

$$p(x,y)=p(y,x)=\frac{\text{number of individuals with genotype} \ (x,y)}{N}$$

$$p(x,\cdot)=\frac{\text{ number of individuals with at least one } x \text{ haplotype }}{N}$$

$$p(x,\neg y)=\frac{\text{ number of individuals with } x \text{ as one haplotype and anything other than }y\text{ as the other }}{N}$$

$$p'(x,x)=p(x,x)^2+\frac{1}{2}p(x,\neg x)p(x,x)+\frac{1}{4}p(x,\neg x)^2=\para{p(x,x)+\frac{1}{2}p(x,\neg x)}^2$$

$$\E(z)=\alpha\E(\dot \gamma)+\beta=\alpha\para{\sum_{i\in\Z}i\sum_{j\in\Z}p(i,2j-i)}+\beta$$

$$\phi(z)=\sum_{i\in\Z}\frac{\exp\para{-\frac{(z-\alpha i-\beta)^2}{2\eta^2}}}{\sqrt{2\pi\eta^2}}\sum_{j\in\Z}p(i,2j-i)$$

$$p_\infty(x,x)=\para{p_0(x,x)+\frac{1}{2}p_0(x,\neg x)}^2$$

$$p_\infty(x,\neg x)=2\para{p_0(x,x)+\frac{1}{2}p_0(x,\neg x)}\para{p_0(\neg x,\neg x)+\frac{1}{2}p_0(x,\neg x)}$$

$$p_\infty(\neg x,\neg x)=\para{p_0(\neg x,\neg x)+\frac{1}{2}p_0(x,\neg x)}^2$$

$$\dots$$

-->

<!--
If the interest is speciation I know we need at the very least some isolating mechanism, whether temporal, spatial, behavioural, or physical. For example, in sympatry (both time and space), hybrid depression is not enough, the population must evolve behaviour that avoids hybridization or else the population will probably just crash.

Can further assume that the probability that gametes $x$ and $y$ produce a viable offspring depends on $|x-y|$.
-->

### Mutation

From my perspective, mutation is a force that causes imperfect replication. That is, the offspring of an individual may not resemble their parent perfectly and this difference is called mutation. This fits the general sense of the word which is alteration, change, or to vary. However, in biology the word mutation refers to a very specific process involving the permament substitution of nucleotide base-pairs. Since I operate at a more abstract level, I will abuse this custom and use the word mutation as described above, referring to imperfect replication. My goal is not to reproduce the minutiae of molecular detail, but to capture the process of imperfect heritability in a tractable way. I believe this will lead me to a leaner, more general theory.

Finally, before we dive in, I just would like to remind myself that the following is not restricted to common phenotypes such as height, toxicity, etc, but also to location. We can think of the different types as either discrete locations or a continuum of geographical space. In this case mutation is nothing more than dispersion.

Returning to a population of $T$ types, let's now suppose that there is a probability $P_t(i,j)$ that an individual of type $i$ produces an offspring of type $j$. Then, if $W(i)$ is the expected fitness of an individual of type $i$, this individual will on average produce $W(i)P_t(i,j)$ individuals of type $j$ and $W(i)P_t(i,i)$ individuals of type $i$. The expected dynamics for each type is then

$$n_{t+1}(i)=\sum_{j=0}^TP_t(j,i)W(j)n_t(j)$$

If we write $\mathbf{n}_t$ as a row vector denoting the sizes of each type and $\tilde P$ for a matrix whose entries are $W_{t+1}(j)P_t(i,j)$, we have

$$\mathbf{n}_{t+1}=\mathbf{n}_t \tilde P.$$

From here we can generate all sorts of madness by conjuring up quirky combinations of $W$ and $P$. My interest, however, lies in something more docile. I'm primarily interested in continuously varying traits. The above only works for at most a countable number of types. For a continuum suppose an individual with trait $z\in\R$ produces offspring with traits distributed normally with mean $z$ and variance $\eta^2$. Assuming no selection or any process other than mutation, if $\phi_t$ is the distribution of traits in one generation then

$$\phi_{t+1}(z)=\int_\R\phi_t(\zeta)\frac{\exp\para{-\frac{(z-\zeta)^2}{2\eta^2}}}{\sqrt{2\pi\eta^2}}d\zeta.$$

In the language of math, we say that mutation acts as a [mollifier](https://en.wikipedia.org/wiki/Mollifier) on the phenotypic density. The equivalent continuous time version of this is diffusion, that is,

$$\frac{\partial\phi_t}{\partial t}=\eta^2\frac{\partial^2\phi_t}{\partial z^2}.$$

The above discrete time dynamics of $\sigma^2$ with random mating and mutation become $\Delta\sigma^2=\eta^2-\frac{\sigma^2}{2}$. One way to show this is to take the same approach as above but assume the offpsring phenotypic density takes the form

$$\phi_o(z)=\sum_iw_i\frac{1}{\sqrt{2\pi\eta^2}}\exp\para{-\frac{(m_i-z)^2}{2\eta^2}}.$$

Another way would be to assume $\phi_t$ is normal and integrate the equation $\partial_t\phi_t=\eta^2\partial_{zz}\phi_t+\phi(\ln\phi_t-\overline{\ln\phi_t})$ over a single unit of time. I leave the details to the motivated reader.

Returning to the perspective of dispersal as geographic mutation, we can replace $\eta$ with $m$, where I'm now using $m$ to represent the standard deviation in location between offspring and parent.

### Breeding Value as a Trait

I think this will be the most effective way at capturing imperfect inheritance.

What happens if the mean offspring trait of an individual is allowed to evolve so that it is not always the trait of the parental individual?

### Population Dynamics

We need to return to considering the effects of mating on the population dynamics.

## Drift

Note that we have already obtained results for stochastic demographic dynamics [here](https://bobweek.github.io/notes-fitness.html#returning_to_stochastics). Can we use these results to obtain a model for drift? Or are the stochastic dynamics of random reproductive ability somehow inherently distinct from drift? Drift is commonly modelled as the random sampling of the adults that have survived viability selection to produce a gene pool. This of course only makes sense for a sexually reproducing population. Then does drift have no effect on clonally reproducing populations? Another odd point is that the variance due to demographic dynamics grows with population size. As each individual contributes some stochasticity to the total number of individuals in the next generation, it makes sense that the variance of this number grows with population size. But this is the opposite effect of drift, which decays with increasing population size. So then maybe the two really are distinct. In such a case we could incorporate an additional component to fitness, a Bernoulli random variable that decides whether the individual is included in the gene pool or not.

$$\W\delta,\ \W\sim\mathcal{P}(W_t), \ \delta\sim\mathrm{Bern}(p)$$

To satisfy the principle of maximum entropy we can set $p=0.5$, making $\E(N_e)=N_t/2$, where $N_e$ is the number of individuals chosen for the gene pool. If $N_e$ is an integer we can derive $\xi_t\sim\mathcal{N}(0,G/N_e)$ where $G$ is the additive genetic variance. Hand-waving may now occur to justify this result for any positive $N_e$. Note that as $N_e\rightarrow0$ bad things occur. But it doesn't make sense to have $N_e<1$ since our population would then be extinct.

<!--

Drift is modelled as a stochastic effect due to assembling the gene pool via random sampling of the population. The number of individuals drawn is called the effective population size, $N_e$. Hence drift transforms a possibly continuous distribution into a discrete one. However, the resulting distribution is uncertain. Let's denote the mass function of this random probability distribution by $\Xi$. Each point with positive mass $Z_i$ is drawn independently of one another, a basic assumption of the drifting process. Assuming that the population being sampled from has a continuous distribution we get $P(Z_i=Z_j)=0$ for each pair of points in the gene pool. If there's no diffusive mutation, then the next generations distribution will also be discrete and hence the disctribution will remain discrete for finite time. Random mating will create new point masses and depending on other processes these point masses can accumulate over time, causing the distribution to converge to some continuous distribution asymptotically. However, with diffusive mutation the populations distribution will remain continuous. How do we capture the effects of drift in continuous time? I think the answer lies in Gaussian processes. In particular, space-time white noise seems to be the most obvious candidate. Intuitively, white noise can be thought of as the time-derivative of Brownian motion, $\frac{dW_t}{dt}$. Space-time white noise can then be thought of as a line of points each following a white noise process. Denoting white noise by $\xi_t$ I am tempted to write the stochastic differential equation

$$\frac{d\phi_t}{d t}=\phi_t\xi_t=\phi_t\frac{dW_t}{dt}\implies d\phi_t=\phi_tdW_t\overset{?}{\implies}\phi_t=\frac{\phi_0\exp\para{W_t-\frac{t}{2}}}{\int_\R\phi_0\exp\para{W_t-\frac{t}{2}}dz}.$$

However, the $dW$ needs to be scaled appropriately to actually capture the effects of drift. This scaling is not immediately obvious to me. To develop some intuition I'm going to assume that $\phi_0$ is normal with mean $\bar z_0$ and variance $\sigma_0^2$. Then, I think,

$$\phi_1=\frac{\phi_0\para{\int_0^1e^{\xi_s}ds}}{\int_\Omega\int_\R\phi_0\para{\int_0^1e^{\xi_s}ds}dzP(d\omega)}=\phi_0\int_0^1e^{\xi_s}ds$$

Note that I'm taking exponentials due to some backwards (not badwarcks!) logic. Thinking about the relationship between a Bayesian update and its continuous time analog, it's natural to then use the exponential of white noise (assuming $\overline{\xi_t}=0$). This makes a connection to something called [Geometric Brownian Motion](http://www.randomservices.org/random/brown/Geometric.html). A classic result in evolutionary theory tell us that $\E(\bar z_1)=\bar z_0$ and $\Var(\bar z_1)=G/N_e)$. This provides a hint. At a given point in phenotypic space, we have (I think) $\E(\phi_1)=\phi_0$ and $\Var(\phi_1)=\phi_0\para{e^{?^2}-1}$. Since we don't have a deterministic component, apparently $\phi_t\rightarrow0$ a.s. This is sort of like a jagged diffusion, then. Hopefully

$$\int_\R z\phi_1dz=\bar z_1, \ \E(\bar z_1)=\int_\Omega\int_\R z\phi_1dzP(d\omega)=\int_\Omega\bar z_1P(d\omega)=\bar z_0,$$

$$\Var(\bar z_1)=\int_\Omega(\bar z_1-\bar z_0)^2P(d\omega)=\int_\Omega\bar z_1^2 P(d\omega)-\bar z_0^2$$

$$\equiv\frac{G}{N_e}.$$

Note that random sampling is not the only source of stochasticiy. Consider my definition of fitness.

-->

## Putting it all together

$$\frac{\partial\phi_t}{\partial t}=\phi(\ln W_t-\overline{\ln W_t})+\phi(\ln \psi_t-\overline{\ln\psi_t})+\eta^2\frac{\partial^2\phi_t}{\partial z^2}+m^2\frac{\partial^2\phi_t}{\partial x^2}+\phi_t\Xi_t$$

$$\frac{\partial\bar z}{\partial t}=\frac{\partial}{\partial t}\int z\phi(z)dz=\int z[\phi(\ln W_t-\overline{\ln W_t})+\phi(\ln \psi_t-\overline{\ln\psi_t})+\eta^2\frac{\partial^2\phi_t}{\partial z^2}+m^2\frac{\partial^2\phi_t}{\partial x^2}+\phi_t\Xi_t]dz$$

$$=\Cov_\phi(z,\ln W_t)+\Cov_\phi(z,\ln\psi_t)+\eta^2\int z\frac{\partial^2\phi_t}{\partial z^2}dz+m^2\frac{\partial^2}{\partial x^2}\int z\phi_tdz+\Cov_\phi(z,\Xi_t)$$

$$=\Cov_\phi(z,\ln W_t)+\Cov_\phi(z,\ln\psi_t)+\eta^2\Cov_\phi\para{z,\frac{\partial^2}{\partial z^2}}+m^2\frac{\partial^2\bar z}{\partial x^2}+\Cov_\phi(z,\Xi_t)$$

#### Stochastics

I focus on continuous time stochastic dynamics because it's difficult to tell what distribution $\overline{\W}_t$ has. If we are consistent with everything derived up until this point we run into some trouble. Namely, since the individual fitnesses $\W$ have been modelled as Poisson random variables, they can take the value zero with positive probability. Hence, $\ln\W$ can be negatively infinite with positive probability. Thus $\E(\ln\W)$ is undefined. We might be able to formally deal with this situation using a generalization of the central limit theorem that would lead us to the so called [stable distributions](https://en.wikipedia.org/wiki/Stable_distribution). Alternatively, we can sweep this dirt under the rug and assume that $\ln\W_t(i)$ is distributed normally with mean $\ln W_t(i)$ and variance $V_t(i)$. Then $\overline{\ln\W_t}\sim\mathcal{N}(\overline{\ln W_t},\overline{V_t})$ where

$$\overline{\ln W_t}=\sum_i\ln W_t(i)\phi_t(i), \ \overline{V_t}=\sum_iV_t\phi_t^2(i).$$

This leads to the SDE

$$d\phi_t(i)=(\ln W_t(i)-\overline{\ln W_t})\phi_t(i)dt+\sqrt{V_t(i)+\overline{V_t}}\phi_t(i)dB_t$$

which defines [geometric Brownian motion](http://www.randomservices.org/random/brown/Geometric.html).

Instead making the above assumptions, incorporating diffusive mutation into the mix can salvage the formality of the approach. Specifically, since diffusion has infinite propogation speed, if $\phi_t(z)>0$ for some $z$ at time $t=t_0$ and

$$\frac{\partial\phi_t}{\partial t}=\phi_t\para{\ln W_t-\overline{\ln W_t}}+\eta^2\frac{\partial^2\phi_t}{\partial z^2}$$

then $\phi_t>0$ for every $z$ and every $t>t_0$.
