---
title: "Proposal Outline"
output: 
  html_document: 
    toc: false
    toc_float: true
    theme: cosmo
    css: style.css
---

<!--
output: 
  html_document:
    toc: true
    toc_float: true
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}

## Cover Sheet

### Project Summary

Develop novel theoretical techniques to investigate the (co)evolution of ecological communities.

### Intellectual Merit

Synthesizes coevolutionary theory and community ecology.

### Broader Impacts

N/A

## Introduction

Introduce the fields of coevolution and community ecology and a breif statement of what I plan to contribute.

## Research Questions

  * How common is pairwise coevolution?
  * How does succession interact with coevolution?
  * How does invasion interact with coevolution?
  * Under what conditions do specialist species evolve?

## Previous Research, Hypotheses, and Methods

Here I describe what I'm about to describe.

### Coevolution and its measurement

Here I provide the definitions of pairwise and diffuse coevolution I will be using and describe the method I've developed to measure pairwise coevolution.

  * $\mathcal{A}\dots$ abiotic selection gradient
  * $\mathcal{B}\dots$ biotic selection gradient  

Potentially distinguish between the traditional idea of coevolution where traits have changed together for long periods of time and the idea I'm focusing on, the existence of significant reciprocal selection (and the response :: we could start be assuming constant $G$ so that there's always a response) even if traits don't change together.

  * Coevolution: The simultaneous response to reciprocal biotic selection in a set of species
  * Diffuse coevolution: When selection strengths among a set of coevolving species are of the same order.
  * Pairwise coevolution: When the selection strengths between a pair of coevolving species exceed the order of selection strengths exerted by peripheral species. 
      * Peripheral species: Non-focal coevolving species.
  * Mixed coevolution: When coevolution is neither diffuse nor pairwise.

### The structure and categorization of communities

Here I describe ways of categorizing communities and refer to Shipley when discussing my focus on traits and functions.

### Hypotheses

#### __Hypothesis 1: Pairwise coevolution is common in young and disturbed communities, but is washed away by diffuse coevolution in mature communities.__

Species don't need to interact for long periods of time to coevolve, they just need to exert significant reciprocal selection on one another (and respond to that selection). I hypothesize that in young and freshly disturbed communities there will be stronger selection being imposed through biotic interactions than through similar interactions taking place in older communties, where the frenzy of niche packing has settled down.

#### Method

I plan to develop a model that tracks the distribution of pairwise coevolution throughout a community. I'll assume the community is initiated at random and analyze the evolution of this distribution. By my defintion of diffuse coevolution, the community transitions from pairwise to diffuse if the distribution initially has a large variance that narrows over time.

#### __Hypothesis 2: Communities climax quicker with coevolution present.__

Three basic phases of succession have been described by ecologists: primary and secondary successions followed by the achievement of what has been called the climax community. The idea here is that this climax community will be reached quicker if coevolution acts to mold the traits of the commnunity members.

#### Method

I plan to extract some number measuring how far along the community has evolved towards its climax community. One potential value related to this transition is NPP, though some notion of entropy may be involved as well. Studying the asymptotic nature of this value, I can compare the rates at which this value converges or increases when coevolution is present versus when coevolution is not present.

#### __Hypothesis 3: Invasions are more successful in the presence of coevolution.__

There are two potential outcomes: 1) coevolved communities will have an increased resistance to invaders and 2) coevolved communities will be more likely to bend to the will of the invader.

#### Method

Begin with a climax community and bombard it with immigrants and see how many take. Find a way to measure this and figure out how this measurement changes between the situations with and without coevolution.

#### __Hypothesis 4: Specialization evolves as a result of competition (and spatial structure).__

As species compete for resources, this competition can drive the evolution of specialization.

#### Method

Use the inputs/outputs formalism to derive metrics of specialization/generalization and a distribution of these quantities across the community.

## Significance of Proposed Research

The proposed work will develop a set of theoretical approaches for understanding the evolution and potential coevolution of ecological communities. The goal is to synthesize ideas and theory in order to produce novel insights and a deepend understanding of the processes that shape the patterns we see in nature. This work can potentially be extended to include more idiosyncratic details that ties theory to data upon which methods of inference can be developed to assertain an explicit understanding of the empirical world. In a time of great flux, it is necessary that we work towards an understanding of the relationship between species and their environment (both abiotic and biotic) as well as our relationship to these species so we can best predict the outcomes of human development and climate change for the sake of the safety of future generations.

## Broader Impacts

I have none to declare.

## References






