---
title: "S2: Evaluating performance across population sizes and selection strengths in symmetric systems"
author:
  - name: Bob Week 
    url: https://bobweek.github.io
    affiliation: University of Idaho
    affiliation_url: https://ibest.uidaho.edu
  - name: Scott Nuismer
    url: https://leeef.org
date: "`r Sys.Date()`"
output:  
  distill::distill_article:
    toc: true
    toc_depth: 3
editor_options: 
  chunk_output_type: console
bibliography: bibliography.bib
---

\newcommand{\C}{\mathbb{C}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\V}{\mathbb{V}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\B}{\mathcal{B}}
\newcommand{\<}{\left<}
\newcommand{\>}{\right>}
\newcommand{\ra}{\rightarrow}

Our individual based simulations follow the same approach used in appendix S1 except for finite populations. That is, we assume each individual posses two traits, a genetic value and an expressed value. The genetic value is inherited as a normally distributed variable centered on the parental genetical value with variance $\eta^2$. The expressed phenotype is then distributed around the inherited genetic value normally with variance $\nu^2$. We assume each individual interacts with a binomially distributed number of individuals in the interacting species. Each individual is chosen at random with respect to their trait value. Net fitness of the individual is determined by calculating a geometric mean of the fitness effects caused by each interaction. The geometric mean is appropriate here since, as the number of interactions tends to infinity, this mean converges to the expected fitness of a trait in the infinite population approximation. To maintain constant population size $N_i$, genetic values are drawn, with repitition, from the parental population with each parental trait value weighted by fitness. To maintain relatively constant genetic variances we set the variance of the initial distribution equal to the equilibrium variance predicted by our model $G_i=\eta_i/\sqrt{B_i}$. This simulation repeats these steps for $\tt{its}$ iterations. Our code for this analysis is presented at the end of this document.

Introduce diff approx

Can also be used to determine relation to strength of selection. In particular, $N\times B$ contour plots of L2 norms.

### _R_ code

```{r, evol=F, echo=T}
nu1 <- .1
nu2 <- .1
eta1 <- .1
eta2 <- .1
d <- 5
p <- .5 # proportion of other species interacted with
NN <- 50
BB <- .01

B1 <- BB
B2 <- BB
N1 <- NN
N2 <- NN

fitness <- function(z1,z2,B,d){
  W <- exp(-B*(z2+d-z1)^2/2)
  return(W)
}

# draw initial genetic values
pop1g <- rnorm(N1)
pop2g <- rnorm(N2)

its <- 100
histz1 <- NULL
histz2 <- NULL
for(i in 1:its){
  
  # draw expressed traits
  pop1z <- NULL
  pop2z <- NULL
  for(i in pop1g){
    pop1z <- c(pop1z,rnorm(1,i,nu1))
  }
  for(i in pop2g){
    pop2z <- c(pop2z,rnorm(1,i,nu2))
  }
  
  # collect for later analysis
  histz1 <- c(histz1,mean(pop1z))
  histz2 <- c(histz2,mean(pop2z))

  # calculate fitnesses
  fit1 <- NULL
  for(i1 in pop1z){
    f <- NULL
    for(i2 in pop2z){
      f <- c(f,fitness(i1,i2,B1,d))
    }
    f <- prod(f)^(1/N2)
    fit1 <- c(fit1,f)
  }
  fit2 <- NULL
  for(i2 in pop2z){
    f <- NULL
    for(i1 in pop1z){
      f <- c(f,fitness(i2,i1,B2,d))
    }
    f <- prod(f)^(1/N1)
    fit2 <- c(fit2,f)
  }
  
  # sample parental population
  bbs1 <- sample(1:N1,N1,replace=T,prob=fit1)
  bbs2 <- sample(1:N2,N2,replace=T,prob=fit2)
  pop1g <- pop1g[bbs1]
  pop2g <- pop2g[bbs2]
  
  # draw offspring genetic values
  pop1bb <- NULL
  pop2bb <- NULL
  for(i in pop1g){
    pop1bb <- c(pop1bb,rnorm(1,i,eta1))
  }
  for(i in pop2g){
    pop2bb <- c(pop2bb,rnorm(1,i,eta2))
  }
  
}
```
