---
title: "The Coevolutionary Theory of Ecological Communities"
output: 
  html_document: 
    toc: false
    toc_float: true
    theme: cosmo
    css: style.css
---

<!--
output: 
  html_document:
    toc: true
    toc_float: true
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\argmax}{\mathrm{argmax}}
\newcommand{\argmin}{\mathrm{argmin}}
\newcommand{\CLAIM}{\bf{Claim}}
\newcommand{\PF}{\bf{Proof}}

## Cover Sheet

### Project Summary

This work aims to synthesize the theories of community ecology and coevolution. There are 7 specific goals. The first is to clarify discussion of the coevolutionary process by developing unambiguous definitions of coevolution, diffuse coevolution, pairwise coevolution, etc. Daniel Janzen and others have contributed to this goal, but there is still a need to further refine these concepts. The second goal is to develop a rigorous mathematical framework for unifying coevolutionary theory with community ecology. At the very least, a mean-field approach can be taken to derive dynamics of trait distributions across sets of interacting species. However, a more satisfying body of theory will incorporate demographic dynamics, species richness dynamics, spatial structure, speciation and phylogenetics. Each of these components has their own set of challenges and a true unifying framework of community ecology and coevolution would overcome all such challenges. With a sufficient framework developed the remaining goals can be met. These goals consist of answering specific biological questions. These questions are:

  * How common is pairwise coevolution?
  * Does coevolution increase the rate of community assembly?
  * Does coevolution decrease the invasibility of a community?
  * Under what conditions do specialist species evolve?
  * Is the evolution of specialist species associated with the evolution of nestedness?

### Intellectual Merit

Ecology has been described as the theatre through which the evolutionary play is held, that is, the ecology of species provides the platform for their evolution. However, as these species evolve their ecology changes. These changes may in turn manipulate the evolutionary dynamics. Since intimancy and significance of this feedback is poorly understood and interest in it has been demonstrated by the increased publication rate on so called "eco-evolutionary dynamics", the time is ripe for the proposed synthesis to be developed and dissimenated.

## Background

