---
title: "Roughgarden"
output: 
  html_document: 
    toc: true
    toc_float: true
    theme: cosmo
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\tr}{\mathrm{tr}}

## Page 519

### Beef 1

Who cares about the "niche position" and "nich width" if the resource utilization curve is multimodal?

### (Resolved) Beef 2

Equation (24.5a) alludes greatly to Hilbert space theory, but I'm not sure if I like its approach. The number $\int u_i(x)u_j(x)dx$ is an inner-product.  Shouldn't we be more interested in a distance between $u_i$ and $u_j$? Actually, now that I'm thinking about it, I like the inner-product for this. Think about a set of finite resources $R(1),\dots,R(n)$. Instead of $u_i(x)$ being defined for $x\in\R$, it's now defined for $x\in\{1,\dots,n\}$, that is $u_i\in\R^n$. Then if $u_i$ and $u_j$ are orthogonal, they utilize completely different resources.

However, I'm still not sure about dividing by the norm of the focal utilization curve.

### Thought 1

The utilization curve $u_i(x)$ here is considered fixed across a species, but this need not be restricted to an emergent property of a population or species. Individuals can have utilization curves and these curves can change as the distribution of resources change. That is, they can be plastic. Of course it would be better to assume canalized for each individual. Then their evolution can be modelled quite easily.

We can assume that an individual with phenotype $z$ will have the resource curve $u(x)=\frac{1}{\sqrt{2\pi\eta^2}}\exp\para{-\frac{(x-z)^2}{2\eta^2}}$ where $\eta^2$ is potentially heritable alongside $z$. This makes for a two dimensional phenotype. Note that $z$ and $x$ will need to be defined on the same space. The biological justification for this is that an animal is likely to use resources that match its phenotype such as beak and seed sizes. We can assume the amount of resources at time $t$ and location $x$ in niche-space is $R_t(x)$ and that

$$\frac{dR_t}{dt}=\lambda_t(K_t-R_t)-C_tR_t\text{ or }\Delta R_t=\lambda_t(K_t-R_t)-C_tR_t$$

so that $R_t$ converges to $K_t>0$ at a rate mediated by $\lambda_t$ when $C_t=0$. But $C_t$ will represent total per-capita consumption of the resource, so as long as there are species utilizing location $x$ at time $t$, $C_t(x)>0$.

The fitness of an individual in the absence of all other individuals may be written as $W=\int u(x)R(x)dx$. Drawing on the finite space example used above to obtain some intuition, we see that if the resources available do not co-occur with the resource utilization curve, then the fitness of the individual will be zero. However, if $u(x)=cR(x)$ for some positive constant $c$ then fitness is maximized.

#### Beginnings

Before we move on to multiple species, let's consider a population of $n$ individuals. Each of their utilization curves are denoted by $u_1(x),u_2(x),\dots,u_n(x)$. Then $C_t(x)=\sum_iu_i(x)$ so that

$$\Delta R_t=\lambda_t(K_t-R_t)-R_t\sum_i u_i\overset{?}{\rightarrow}\frac{dR_t}{dt}=\lambda_t(K_t-R_t)-R_tn_t\overline{u_t}$$

$$R_\infty=\frac{\lambda K}{1+n\bar u}\dots\text{ non-normal}\dots\text{ a necessary evil?}$$

If there was no capacity to $R$ so the resource can accumulate towards infinity (which I think is really dumb), then

$$R_\infty=\frac{\lambda}{n\bar u}\dots\text{ suggests diversifying selection}.$$

This is even dumber than I previously imagined!! Of course we get diversifying selection. If all resources are accumulating at a constant rate, then the population will disperse out so no individuals compete with one another. What a dumb model. We might be able to rectify the situation by assuming that $\lambda$ is Gaussian. In that case it could go either way, the population could explode and diversify off into infinity, or converge to a delta.

Let $n_t(z)$ be the population density of trait $z$ at time $t$. Then

$$\frac{dn_t}{dt}=\ln\para{\int u(x)R(x)dx}n_t.$$

We can assume $z\sim\mathcal{N}(\bar z,\sigma^2)$ and $\eta\sim\ln\mathcal{N}(\overline{\ln\eta},V_\eta)$. We can probably get

$$\frac{d\bar z}{dt}=\frac{\sigma^2}{\psi_z}(?-\bar z), \ \frac{d\overline{\ln\eta}}{dt}=\frac{V_\eta}{\psi_\eta}(?-\overline{\ln\eta}).$$

Or simplify things for now and assume $\eta$ is constant. If we assume $R_t=\frac{1}{\sqrt{2\pi\omega_t^2}}\exp\para{-\frac{(\theta_t-z)^2}{2\omega_t^2}}$ then 

$$W_i=\frac{1}{\sqrt{2\pi(\eta^2+\omega_t^2)}}\exp\para{-\frac{(z-\theta_t)^2}{2(\eta^2+\omega_t^2)}}$$

and

$$\overline{W_t}=\frac{1}{\sqrt{2\pi(\eta^2+\omega_t^2+\sigma^2)}}\exp\para{-\frac{(\bar z-\theta_t)^2}{2(\eta^2+\omega_t^2+\sigma^2)}}.$$

Hence

$$\frac{d\bar z_t}{dt}=\frac{\sigma^2}{\eta^2+\omega_t^2+\sigma^2}(\theta_t-\bar z_t).$$

Let's now set $K_t=\frac{1}{\sqrt{2\pi\omega_t^2}}\exp\para{-\frac{(\theta_t-z)^2}{2\omega_t^2}}$ instead of $R_t$ and for starters assume $\omega_t=\omega$ and $\theta_t=\theta$ so that $K_t$ is constant wrt $t$.

#### Clean it up

$$\frac{\partial R}{\partial t}=\lambda(K-R(x,t))-R(x,t)\sum_in_i(t)u_i(x)=\lambda(K-R(x,t))-R(x,t)N(t)\sum_i\phi_i(t)u_i(x)$$

$$=\lambda(K-R(x,t))-R(x,t)N(t)\bar u(x)$$

This is a non-homogenous linear first order differential equation with $\lambda K$ as the forcing function.

How about

$$=\lambda(K-R(x,t))-N(t)\bar u(x)\implies R^*=K-\frac{N^*\bar u}{\lambda}$$

$$\frac{\partial N}{\partial t}=(R\bar u-d)N\implies R^*=d/\bar u\implies N^*=\lambda\para{\frac{\bar uK-d}{\bar u^2}}$$

Note that $\int u_i(x)u_j(x)dx\leq\|u_i\|\|u_j\|$. Define 

$$\zeta_{ij}\equiv\frac{\int u_i(x)u_j(x)dx}{\|u_i\|\|u_j\|}.$$

* Orthogonal utilization curves... Hermite functions? If we assume that at equilibrium all species utilization curves must be orthogonal, then a Gaussian resource function will allow a countable number of species whose utilization curves will co-occur with the Hermite functions.

* I don't like that result. For one, I think that species are able to share resources, so their utilization curves will not necessarily be orthogonal at equilibrium.

Suppose the effect on fitness due to competition is constant for all interactions and denote this number by $0<W_c<1$. The max fitness of an individual of type $i$ is $M_i=\int u_i(x)R(x)dx$. The resulting fitness due to competition is then

$$W_i=M_iW_c^{\zeta_{ij}}.$$

For Gaussian $u_i,u_j$ we have

$$\zeta_{ij}=\frac{\sqrt{\sqrt{4\pi\eta_i^2}\sqrt{4\pi\eta_j^2}}}{\sqrt{2\pi(\eta_i^2+\eta_j^2)}}\exp\para{-\frac{(z_i-z_j)^2}{2(\eta_i^2+\eta_j^2)}}.$$

Assuming that $\eta_i=\eta_j=\eta$ we get $\zeta_{ij}=\exp\para{-\frac{(z_i-z_j)^2}{4\eta^2}}$. Let's go ahead and assume static $R$ as above for now. Then, again,

$$M_i=\frac{1}{\sqrt{2\pi(\omega^2+\eta^2)}}\exp\para{-\frac{(\theta-z_i)^2}{2(\omega^2+\eta^2)}}$$

and

$$\ln W_i=\ln M_i+\zeta_{ij}\ln W_c\dots$$

seems kinda crazy. I already have a model that can capture some aspects of this. The result would be 

$$W_c$$

$$\ln W_i=\ln M_i-pN\frac{(\bar z-z_i)^2}{2(2\eta^2+\sigma^2)}$$

$$\frac{d\bar z}{dt}=\frac{\theta-\bar z}{\omega^2+\sigma^2}$$

$$\frac{dN}{dt}=N\para{\sqrt{\frac{\omega^2}{\omega^2+\eta^2}}-\frac{(\theta-\bar z)^2}{2(\omega^2+\eta^2)}}-pN^2\frac{\sigma^2}{2(2\eta^2+\sigma^2)}$$

* All that other stuff is bleh. I'm forcing there to be some direct interaction term such as $\zeta_{ij}$ instead of letting one emerge.

Working backwords

$$\frac{dN}{dt}=(aR-d)N\implies W=e^{aR-d}$$

Each individual needs so many resources to reproduce, but no more. The more resources required, either the bigger the offspring or more offspring. So we can relate the number of resources gathered to reproductive output.

Say there's $R$ packets of resources available and each individual need 1 to reproduce. We can start by assuming all individuals have equal opportunnity so that the probability that an individual reproduces is equal to $\max(1,R/N)$. If differential opportunnity occurs because each individual has a different trait that gives them either more or less of an advantage, what is the probability for each individual that it reproduces? We can think of this as scaling the amount of resources needed. An individual with a trait that gives them an advantage scales the required number of resource packets to a lower number. This scaling could be:

$$s(z)=\exp\para{\frac{(\theta-z)^2}{2\omega^2}}$$

But it's not true that these individuals need more or less, just that they have a harder or easier time getting them.

Suppose the effeciency of individual is:

$$e(z_i)=\exp\para{-\frac{(\theta-z_i)^2}{2\omega^2}}$$

and the probability that this individual reproduces is

$$\frac{e(z_i)}{\sum_je(z_j)}$$

in the continuum

$$p_i=\frac{e(z_i)}{\int e(z)\phi(z)dz}$$

suppose each individual consumes $C$ amount of resources.

$$R_{t+1}=R_t+\lambda(K-R_t)-C\sum_ip_i$$

$$\frac{dN}{dt}=\overline{\ln(Wp)}N$$

$$\overline{\ln(Wp)}=\ln W-\frac{(\bar z-\theta)^2+\sigma^2}{2\omega^2}-\ln\sqrt{2\pi\omega^2}+\frac{(\bar z-\theta)^2}{2(\omega^2+\sigma^2)}
+\ln\sqrt{\frac{\omega^2}{\omega^2+\sigma^2}}$$

$$=\ln W+\frac{(\bar z-\theta)^2(\omega^2+\sigma^2)+\sigma^2(\omega^2+\sigma^2)-\omega^2(\bar z-\theta)^2}{2\omega^2(\omega^2+\sigma^2)}+\ln\sqrt{\frac{1}{2\pi(\omega^2+\sigma^2)}}$$

$$=\ln W+\frac{(\bar z-\theta)^2\sigma^2+\sigma^2(\omega^2+\sigma^2)}{2\omega^2(\omega^2+\sigma^2)}+\ln\sqrt{\frac{1}{2\pi(\omega^2+\sigma^2)}}$$

$$=\ln W+\frac{}{}+\ln\sqrt{\frac{1}{2\pi(\omega^2+\sigma^2)}}$$




## Crazy idea

The set of all polynomials provides a basis for the set of all smooth functions. The exponential of the such functions can then be written as the exponetional of the sum of polynomials. Can we transform the dynamics and work with polynomials instead? The Hermite polynomials provide a basis.