---
title: "The evolution and ecology of mutualistic communities"
output: 
  html_document: 
    toc: false
    toc_float: true
    theme: cosmo
    css: style.css
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\argmax}{\mathrm{argmax}}
\newcommand{\argmin}{\mathrm{argmin}}
\newcommand{\CLAIM}{\bf{Claim}}
\newcommand{\PF}{\bf{Proof}}

# Motivating Questions

## 1. How strong is coevolution?

## 2. What's with all the functional diversity across mutualistic networks?

Why is the mean phenotype pair of some pollination communities so exaggerated while the mean phenotype pair of other pollination communities is not even though it the same interaction structuring both communities?

  * Is it due to the network structure of the community?
  * Is it due to the distribution of coevolution in the community?
  * Is it due to the fine details of the mechanism mediating the interactions within each community?
  * Are these just different faces of the object? That is, is the distribution of coevolution, the network structure of the community and the mechanism mediating the interaction all required to develop  ?
  

## 3. 

# Stuff discussed with Scott

## Why are some mutualisms so exaggerated?

### 2. Is due to the mechanism of the interaction?

- Try a nonequlibrium approach. Let $\delta$ vary for each interaction throughout the community and observe the distribution of traits that emerges in finite time.

### 3. Is it due to the distribution of specialization in the community?

- Using the interaction distributions, do some cool stuff.

## 4. Why do some communities have many species with exaggerated traits, some a variability in exaggeration and yet other little to no variability?

# The stuff

Assumptions:

  * Two interacting guilds of species (e.g. plants and fly-pollinators).
  * A continuous trait mediates the interaction in both guilds (e.g. corolla and tongue lengths).
  * Individuals have a preference with whom they interact and this preference is trait based (e.g. we can assume the flys choose the flowers whose corolla depth would maximize their fitness on average but with some variance).


$$W_{fly}(x)=\int\frac{\iota_{fly}(x,y)\phi_{flower}(y)}{\int\iota_{fly}(x,y)\phi_{flower}(y)dy}W(x,y)dy$$

We could assume the distributions $\phi_i$ are over all the individuals within guild $i$.