---
title: "The Coevolutionary Theory of Community Ecology"
output: 
  html_document: 
    toc: true
    toc_float: true
    theme: cosmo
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\tr}{\mathrm{tr}}

## Cover Letter

Community ecology, the study of groups of interacting species, is a broad field that has provided insight to topics ranging from the microbiology of human health (citation, Forney) to the conservation of charismatic megafauna (citation, not sure if this is even true). The importance of this field stems from the fact that species tend to interact with other co-occuring species, potentially driving processes that produce the various patterns in diversity we witness today. Traditional community ecology has focused on the effects of interspecific interactions on demography and demographic stability in particular (citations, probably May and Abrams) as well as on the maintenance of biodiversity (typically in the form of species richness, cite Morin) and tend to ignore the potential role of evolution in shaping biological communities. Recently, phylogenetic perspectives have been incorporated into these studies in attempt to determine how much of the currently observed patterns of diversity within a given region are due to the history of that region and the clade(s) of organisms involved (Web et al 2002, Ruffley maybe too). However, this approach still holds the implicit assumption that microevolutionary processes are negligible and also has the drawback of classifying communities taxonomically instead of functionally (though it can be argued that closely related species tend to be functionally similar). Although trait-based approaches have been taken to investigate the interplay between (co)evolution and ecology (Roughgarden, Abrams), these approaches fall short in their ability to draw general conclusions because of their focus on idiosyncratic details and models that therefore become intractable when considering even a modest number of species. Here we propose a novel approach to coevolutionary community ecology that focuses on the evolution of the statistical distributions of traits within communities, instead of explicitly modelling the dynamics of each species. This methodology will be used to investigate the role of coevolution in succession and the evolution of specialists.



<!--

Deliminating communities in terms of their function (such as predator-prey or plant-pollinator communities) has the advantage of emphasizing the biotic processes that may explain the why these communities are structured so. Combining ecological mechanism with microevolutionary insights extends the domain of community ecology to include questions such as whether or not the stability of community is a property that has evolved. Such a mechanistic approach has begun to develop within the study of mutualistic networks (Nuismer et al 2013)

By coupling the mechanisms of ecological interactions with the theories of population and quantitative genetics, a well developed quantitative understanding of coevolution has emerged (Nuismer 2017). 

-->