---
title: "The Coevolutionary Theory of Community Ecology"
output: 
  html_document: 
    toc: true
    toc_float: true
    theme: cosmo
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\tr}{\mathrm{tr}}

## What is a community?

I accept the very broad and flexible description of a biological community provided in the classic book "Community Ecology" edited by Diamond and Case:

* "First, the site size may vary from an entire biogeographical region to a one-pint laboratory culture bottle. Second, the number of species may vary from a whole local biota to a tiny fraction of it. Finally, the fraction of the biota may be delineated in various ways: a taxonomic set of species, a life form set, a group of mutualists and their resources, a single trophic level, two interacting trophic levels, or a whole food web."

I will use the phrase "entire community" to refer to the entire set of biota occurring within a given region. Subsets of an entire community will be referred to by prefixing the word community with the object(s) of interest. For example the term competitive community would refer to a set of species competing for a common set of resources. Likewise a predator-prey community would refer to an extension of a competitive community where the set of resources are replaced with a set of prey species.

## Why community ecology?

In my mind, the entire community is the ultimate unit of study in evolution and ecology. We can model the evolution and ecology of a single species, incorporating a mind-numbing amount of detail about mating structure, genetic architecture, spatial dynamics and so on. But even with such a thorough investigation we typically cannot claim to have understood why this particular species is the way that it is because species do not exist in a vacuum. They co-occur with various other species and this geographic overlap inevitably leads to interspecific interactions. Of course there are models that have been developed to capture the evolutionary and ecological dynamics of interacting species. However, these models are typically limited to a small number of species even though we know entire communities do not generally consist of just a few species. Incorporating such facts into our methods can alter the conclusions drawn. To be certain that, for example, the abiotic environment is responsible for the diversity of a species or clade, this hypothesis should be tested against competing ones such as the hypothesis that the observed diversity is the result of interspecific interactions. Furthermore, to repeat a statement that has been made many times over, any reasonably observant individual who has spent a modest amount of time in natural environments will likely notice patterns such as the co-occurance of particular species of plants and fungi or the abrudt changes in species composition from one location to another. To understand why such patterns exist it is important to recognize that a pair of interacting species constitutes just one element in an enormous web of interactions across an entire community. How does the nature of each of these pairwise interactions structure the entire community and give rise to patterns commonly witnessed in nature?

## Questions

Here I provide a list of questions relating coevolution to community ecology.

* How common is pairwise coevolution?
    + Given an index of coevolutionary selection, what is the distribution of this index across a community?
    + How does this distribution change with respect to community type?

* How does succession interact with coevolution?
    + Can we expect coevolution to be rampant or rare during a succession?
        + Will succession select for or against coevolution?
    + How does coevolution manipulate patterns of succession?
    + How sensitive is a community to immigrant species?
        + Will the residents evolve in response or will the new species become "assimilated"?
    
* Under what conditions do specialist species evolve?
    + Specifically, in plant/pollinator communities, theory suggests that coevolution will result in a higher degree of 
    generalism which in turn makes for a more robust community. Then why do specialists evolve?
    + In many communities there are lots of boring species (species with common traits) and few species with exaggerated traits. 
    Can this pattern be explained by the joint distribution of coevolution and specialization in a community?
    
<!-- + If we start with a biologically vacant region that has some abiotic resources, give a regional pool of species, how will the community assemble? -->    
    
Note that the answer to the first question is relevant to answering both subsequent questions. Futhermore, there is significant interplay between the latter two questions. For example, the evolution of specialists during the colonization of a novel landscape can alter the pattern of succession. Conversly, some successional situations may amplify or attenuate selection for specialists.

## Scratching the surface

In this context there are three primary elements through which patterns can form: the distribution of traits in species across guilds, the network structure of interactions within and among guilds and the sizes of populations across guilds. Time together with space provide the medium through which patterns involving these elements can form, but I doubt I will be able to extend this work to the macroevolutionary setting before I graduate. Also, aside from microbes and the fossil record, most data relevant to this line of inquiry are cross-sectional. Hence, patterns in time will not play a significant role in the initial development of these ideas. Instead, I will focus on patterns in space, which I have already begun investigating in my soon-to-be first publication that uses spatial patterns in traits to measure coevolution.

I've identified two things acting to generate patterns across the aforementioned elements. Each of these things contain two complimentary components that can be thought to compete for control of the patterns we witness. I (tentatively) call these things scale (regional/local) and agent (biotic/abiotic). A given pattern might be explained in large part by some combination of these things. For example, consider a pattern in space such as the number of species in a clade across some region. Is this pattern due in large part to regional processes such as the immigration of species from some external locality or to local processes such as speciation (I never mentioned how large the region is so allopatric speciation is fair game)? In conjunction with scale, we can ask whether these patterns are due to abiotic or biotic agents. For example, plant immigration is abiotic when propogules are wind/water-dispersed, but biotic when animal-dispersed. For animals, the behavioral component of movement for an organism may interact with the heterogeneity of the landscape to determine how far and in what direction the organism will move. So this regional process may be equally due to biotic and abiotic agents. Likewise, speciation can have a biotic or abiotic explanation. A biotic explanation might involve the interaction of this clade with another clade, such as a set of parasites, that induces speciation through their interaction. Abiotically, speciation may be due to vicariance. Alternatively, speciation may be a result of intra-clade competition for non-living resources, an explanation that invokes both biotic and abiotic agents.

<!-- , dimension (time/space)  -->

## Structure of the approach    

The idea here does not deviate from traditional reductionist approaches. To analyze a community I plan to first tear it apart into appropriate subunits of study. The atoms of such a reduction are the individuals. By making assumptions about the life-cycle of individuals we can derive ecological and evolutionary dynamics of their population. This leads to an understanding of their metapopulation, their entire species, sets of species, sets of guilds and eventually the entire community.

#### Pairwise coevolution (2 species)

The theory developed for pairwise coevolution provides the backbone for all (or most) of these investigations. This theory has been constructed exactly as described above. We make certain assumptions at the individual level and have been able to derive the resulting dynamics for entire metapopulations. The case of fixed population sizes has been thoroughly investigated. However, since evolutionary and demographic dynamics are coupled through fitness and the form of fitness has already been specified, extending this work to fluctuating population sizes will be straightforward. In particular, for a pair of interacting species with mean traits $\bar z_1$, $\bar z_2$ and population sizes $n_1,n_2$, I expect to obtain dynamics of the form

$$\Delta\bar z_i=f_{z,i}(\bar z_1,\bar z_2,n_1,n_2), \ \Delta n_i=f_{n,i}(\bar z_1,\bar z_2,n_1,n_2).$$


#### Coevolutionary community modules (a few species)

These models extend the pairwise models to a set of 3 or 4 species and will be used to focus on particular aspects of the big picture. There may be some questions that are more appropiately answered by focusing on just a few species, but the point of these models is to provide not much more than a stepping stone to the amalgamation of many species. For $k$ species, I anticipate these models to be a literal extension of the pairwise models, taking the form

$$\Delta\bar z_i=f_{z,i}(\bar z_1,\dots,\bar z_k,n_1,\dots,n_k), \ \Delta n_i=f_{n,i}(\bar z_1,\dots,\bar z_k,n_1,\dots,n_k).$$

#### Diffuse coevolution (many species)

This will be the primary focus. Instead of explicitly modelling the dynamics of each species within the community I will take the so called mean-field approach by assuming population sizes and mean traits are iid within a guild. Parameters capturing interaction strengths can be held as fixed constants or also modelled as random variables. I hope that this approach will lead me to a natural way of quantifying the evolutionary stability of a community. This would in turn allow for rigorous investigations of, for example, effect of a species with a particular set of attributes immigrating into the community or how the community will respond to environmental changes. Even with this larger scale approach, I plan only to study subsets of entire communities, such as plant-pollinator or predator-prey-resource communities. 

In this framework the models will be composed of a set of stochastic processes $\{(\overline {Z}_t^{(i)},N_t^{(i)}):i=1,\dots,k\}$ with each pair representing the mean traits and population sizes of the species in guild $i$. To provide a more detailed picture, if there are $k$ guilds, each guild $i$ having a set of species denoted by $S_i$, then, in terms of probability theory, our sample space will be $\Omega=S_1\times\cdots\times S_k$ so that $\omega=(s_1,\dots,s_k)\in\Omega$ specifies a particular combination of species among the guilds. So $\{(\overline {Z}_t^{(i)},N_t^{(i)})\}(\omega)=\{(\overline {Z}_t^{(1)}(s_1),N_t^{(1)}(s_1)),\dots,(\overline {Z}_t^{(k)}(s_k),N_t^{(k)}(s_k))\}$ is a sample path representing the evolution of mean trait and population size for a specific set of species.

Probably a more accurate way of modelling $\Omega$ is by thinking of each element as a set of __potential__ species; species that may or may not actually exist. This side-steps having to assume infinite numbers of species in each guild and instead emphasizes the uncertainty of species' traits, abundance and relationship to other species. I believe this approach is more in line with the established conceptualization of a sample space. This works especially well if we think of a species as an object with properties such as population size, mean trait value, additive genetic variance and interaction strengths. Let's flesh this out a bit more:

A species can be specified by:

  * $\phi\dots$ the distribution of a trait
  * $G\dots$ a summary of the genetic architecture of that trait
  * $\alpha\dots$ something that represents how it interacts with other species in the community
  
If there were just a finite number of potential species then enumerating these species we could easily define $\alpha$ to be a vector of selection strengths. If offsets are involved we can expand $\alpha$ to a matrix with two columns, one for the strength and the other for the offset. For a countably infinite number of potential species, these vectors could be extended to their infinite dimensional counterparts. For an uncountable number we begin to lose traction. In such a case it would be better to instead of coming up with some arbitrary enumeration, to list species by their trait values and use some community wide distribution of trait values to describe where those species are likely to land. Then $\alpha$ would be a function where each $\alpha(x)$ is the density of selection strengths for this focal species around the trait value $x$.



Connecting back to the primary questions:

  * If we have an index $\alpha^{(ij)}_t$ representing the strength of coevolution between species of guilds $i$ and $j$ at time $t$ we can think of this index as a random process defined on the sample space $S_i\times S_j$. Computing the asymptotic distribution of $\alpha^{(ij)}_t$ provides a natural way to answer the first question.

  * If we have an index $\beta^{(ij)}_t$ representing the strength of __interaction__ between species of guilds $i$ and $j$ we may be able to use this index to compute another index representing the degree of specialization of species within guilds $i$ and $j$. Again, computing the asymptotic distribution of this index would lead to a nice way to answer the question on specialization.
  
  * Finally, we can use the set of stochastic processes $\{(\overline {Z}_t^{(i)},N_t^{(i)})\}$ in conjuction with a spatial component to develop a model of succession. Computing an index of coevolution for this model, we can investigate how coevolution and succession interact.




<!--


#### Other questions

* How many species can be maintained in different types of communities?
    + How does (co)evolution affect this number?
* What kind of trait distributions can we expect in different types of communities?
    + How does (co)evolution affect this distribution?
* What kind of abundance distributions can we expect in different types of communities?
    + How does (co)evolution affect this distribution?

* How does space interact with coevolution to produce community structure?
    + What determines the distribution of various species? Is it primarily abiotic or biotic?
    + Does distribution play a role in indirect interactions? For example, if two species do not co-occur, but both co-occur with a third species, ...

#### Tangential questions

* How does plasticity change the answers to each of the above questions?

* How does phylogenetic signal change the answers to each of the above questions?

* How does the genetic architecture of the traits involved change the answers to each of the above questions?

-->



<!--

## Specifics

#### How common is pairwise coevolution?

Now that I have developed method to infer the strength of coevolution between a pair of species, empiricists are prepared to investigate the prominence of coevolution nature. However, the question of the ubiquity of pairwise coevolution can be attacked from a theoretical approach. To do so I can develop a stochastic approach the determines the probability that a given species pair will coevolve. These probabilities will depend on the type of interaction and environmental context, including both biotic and abiotic components. The result of such an investigation will be to identify criteria that lead to a high probability of coevolution. If this criteria is stringent and not likely met in but very few species interactions, then we can hypothesize that coevolution is rare. However, if this criteria is quite laxed then we can hypothesize that coevolution is rampant. Conclusions will have to wait for empirical verification.

An alternative approach is to formulate an index of coevolutionary selection and to determine the distribution across the community.

* Need to go back to method and get the p-values of the $\beta$'s instead of the $B$'s. The $B$'s only represent the potential for coevolution, the $\beta$'s determine realization of coevolution.

#### How sensitive is a community to immigrant species?

#### Under what conditions do specialist species evolve?

-->

## Non-random encounters

Suppose we have two interacting populations whose interaction is mediated by a trait in each population, $z_1$ and $z_2$, each having distributions $\phi_1(z_1)$ and $\phi_2(z_2)$. If individuals meet randomly, but covary w.r.t. their traits by a correlation coefficient $\rho$, then we have to work with a multivariate distribution $\phi(z_1,z_2)$. Then

$$W_i(z_i)=\int_\R W_{i,j}(z_1,z_2)\phi(z_1,z_2)dz_j, \ j\neq i$$

$$\overline W_i=\int_{\R^2}W_{i,j}(z_1,z_2)\phi(z_1,z_2)dz_2dz_1$$

$$W_{i,j}(z_1,z_2)=\exp\para{-\frac{(z_1-z_2)^2}{2\omega^2}}$$

$$\phi(z_1,z_2)=\frac{1}{2\pi\sigma_1\sigma_2\sqrt{1-\rho^2}}\exp\para{-\frac{1}{1-\rho^2}\para{
\frac{(z_1-\bar z_1)^2}{2\sigma_1^2}+\frac{(z_2-\bar z_2)^2}{2\sigma_2^2}-\rho\frac{(z_1-\bar z_1)(z_2-\bar z_2)}{\sigma_1\sigma_2}
}}$$

$$=\hat\phi_1(z_1)\hat\phi_2(z_2)\hat\rho(z_1,z_2)$$

$$\hat\phi_i(z_i)=\frac{1}{\sqrt{2\pi\sigma_i^2(1-\rho^2)}}\exp\para{-\frac{(z_i-\bar z_i)^2}{2\sigma_i^2(1-\rho^2)}}$$

$$\hat\rho(z_1,z_2)=\sqrt{1-\rho^2}\exp\para{\frac{\rho}{1-\rho^2}\frac{(z_1-\bar z_1)(z_2-\bar z_2)}{\sigma_1\sigma_2}}$$

$$W_{i,j}\hat\phi_i=\sqrt{\frac{\omega^2}{\sigma_i^2(1-\rho^2)+\omega^2}}\exp\para{-\frac{(\bar z_i-\bar z_i)^2}{2(\sigma_i^2(1-\rho^2)+\omega^2)}}$$
$$\times\frac{1}{\sqrt{2\pi\tilde\sigma_i^2}}\exp\para{-\frac{(z_i-\tilde z_i)^2}{2\tilde\sigma_i^2}}$$


$$\tilde z_1=\frac{\sigma_1^2(1-\rho^2)z_2+\omega^2z_1}{\sigma_1^2(1-\rho^2)+\omega^2}$$

$$\tilde\sigma_1^2=\frac{\sigma_1^2(1-\rho^2)\omega^2}{\sigma_1^2(1-\rho^2)+\omega^2}$$

$$W_i(z_i)=\sqrt{\frac{\omega^2}{\sigma_1^2(1-\rho^2)+\omega^2}}\E_{\hat \phi_i}(\hat\rho)$$



