---
title: "The general framework"
output: 
  html_document: 
    toc: true
    toc_float: true
    theme: cosmo
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\para}[1]{\left( #1 \right)}
\newcommand{\cav}[1]{\left< #1 \right>}
\newcommand{\W}{\mathcal{W}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\tr}{\mathrm{tr}}
\newcommand{\PF}{\mathrm{Proof:}}
\newcommand{\CLAIM}{\mathrm{Claim:}}
\newcommand{\DEF}{\mathrm{Def:}}

Here I derive some general results for the dynamics of demography and evolution in ecological communities.

# Taxanomically structured communities

I start by exploring the dynamics of parameters describing the distribution of population size and trait distribution of species across the community. This approach is to be contrasted with the approach taken by ignoring species identity and focusing strictly on the distribution of traits of all individuals throughout the community.

## Notation

  * $N\dots$ the number of species within the community.
  * $n_i\dots$ expected population size of species $i\in\{1,\dots,N\}$.
  * $\eta=\sum_in_i\dots$ expected total number of individuals in community.
  * $n_i(z)\dots$ expected number of individuals of species $i$ of type $z\in\R$.
  * $\phi_i(z)\dots$ expected proportion of individuals of type $z$ in species $i$.
  * $\tau_i=n_i/\eta\dots$ expected proportion of individuals of species $i$ within the community.
  * $W_i(z)\dots$ expected Wrightian fitness of an individual of species $i$ of type $z$.
  * $m_i(z)\geq0\dots$ expected immigration rate of individuals of species $i$ of type $z$.
    + emmigration is captured within $W_i(z)$
    + $m_i=\int m_i(z)dz\dots$ total expected immigration rate for species $i$.
    + $M=\sum_im_i\dots$ total expected immigration rate of individuals for community.
  * $\overline{X_i}=\int X_i(z)dz\dots$ average of quantity $X_i$ over species $i$.
  * $\cav{X}=\sum_i\tau_iX_i\dots$ weighted average of quantity $X_i$ over the community weighted by numbers of individuals.
  * $\underline{X}=\frac{1}{N}\sum_iX_i\dots$ unweighted average of quantity $X_i$.
  * e.g. $\cav{\overline{\ln W}}$ is the community average of species-level malthusian fitness

## Fixed $N\in\N$

### Demographic dynamics of species $i$

$$\frac{dn_i}{dt}=\frac{d}{dt}\int n_i(z)dz=\int \frac{dn_i(z)}{dt}dz=\int n_i(z)\ln W_i(z)+m_i(z)dz$$

$$=n_i\int\frac{n_i(z)}{n_i}\ln W_i(z)dz+\int m_i(z)dz=n_i\int\phi_i(z)\ln W_i(z)dz+m_i$$

$$=n_i\overline{\ln W_i}+m_i$$

### Unweighted average demographic dynamics across the community

$$\frac{d\underline n}{dt}=\frac{d}{dt}\para{\frac{1}{N}\sum_in_i}=\frac{1}{N}\sum_i\para{n_i\overline{\ln W_i}+m_i}$$

$$=\frac{\eta}{N}\sum_i\frac{n_i}{\eta}\overline{\ln W_i}+\frac{1}{N}M$$

$$=\underline n\sum_i\tau_i\overline{\ln W_i}+\underline m=\underline n\cav{\overline{\ln W}}+\underline m$$

### Dynamics of $\eta$

$$\frac{d\eta}{dt}=\frac{d}{dt}\sum_in_i=\sum_i\para{n_i\overline{\ln W_i}+m_i}$$

$$=\eta\cav{\overline{\ln W}}+M$$

### Dynamics of $\tau_i$

$$\frac{d\tau_i}{dt}=\frac{d}{dt}\frac{n_i}{\eta}$$

$$=\frac{\eta\para{n_i\overline{\ln W_i}+m_i}-n_i\para{\eta\cav{\overline{\ln W}}+M}}{\eta^2}$$

$$=\tau_i\para{\overline{\ln W_i}-\cav{\overline{\ln W}}}+\frac{m_i-\tau_iM}{\eta}$$

Note that $\sum_i\frac{d\tau_i}{dt}=0$ as required to maintain $\sum_i\tau_i=1$.

### Weighted average demographic dynamics across the community

$$\frac{d\cav n}{dt}=\frac{d}{dt}\sum_i\tau_in_i=\sum_i\para{\tau_i\frac{dn_i}{dt}+n_i\frac{d\tau_i}{dt}}$$

$$=\sum_i\para{\tau_i\para{n_i\overline{\ln W_i}+m_i}+n_i\frac{d\tau_i}{dt}}$$

$$=\cav{n\overline{\ln W}}+\cav m+\sum_in_i\para{\tau_i\para{\overline{\ln W_i}-\cav{\overline{\ln W}}}+\frac{m_i-\tau_iM}{\eta}}$$

$$=\cav{n\overline{\ln W}}+\cav m+\cav{n\overline{\ln W}}-\cav n\cav{\overline{\ln W}}+\cav m-M\cav\tau$$

$$=2\cav{n\overline{\ln W}}-\cav n\cav{\overline{\ln W}}+2\cav m-M\cav\tau$$

### Evolution of species $i$

$$\frac{d\phi_i(z)}{dt}=\frac{d}{dt}\frac{n_i(z)}{n_i}=\frac{n_i(n_i(z)\ln W_i(z)+m_i(z))-n_i(z)(n_i\overline{\ln W_i}+m_i)}{n_i^2}$$

$$=\phi_i(z)\para{\ln W_i(z)-\overline{\ln W_i}}+\frac{m_i(z)-\phi_i(z)m_i}{n_i}.$$

Note that $\int\frac{d\phi_i(z)}{dt}dz=0$ as required to maintain $\int\phi_i=1$.

### Unweighted evolution of the community

$$\frac{d\underline\phi(z)}{dt}=\frac{d}{dt}\frac{1}{N}\sum_i\phi_i(z)$$

$$=\frac{1}{N}\sum_i\para{\phi_i(z)\para{\ln W_i(z)-\overline{\ln W_i}}+\frac{m_i(z)-\phi_i(z)m_i}{n_i}}$$

$$=\frac{\sum_i\phi_i(z)}{N}\sum_i\para{\frac{\phi_i(z)}{\sum_i\phi_i(z)}\para{\ln W_i(z)-\overline{\ln W_i}-\frac{m_i}{n_i}}}+\frac{1}{N}\sum_i\frac{m_i(z)}{n_i}$$

$$=\underline\phi(z)\sum\tau_i\para{\ln W_i(z)-\overline{\ln W_i}-\frac{m_i}{n_i}}+\underline{\para{\frac{m(z)}{n}}}$$

$$=\underline\phi(z)\cav{\ln W(z)-\overline{\ln W}-\frac{m}{n}}+\underline{\para{\frac{m(z)}{n}}}$$

Integrating $\frac{d\underline\phi(z)}{dt}$ wrt $z$ should return zero.

### Weighted evolution of the community

$$\frac{d\cav\phi(z)}{dt}=\frac{d}{dt}\sum_i\tau_i\phi_i(z)=\sum_i\para{\tau_i\frac{d\phi_i(z)}{dt}+\phi_i(z)\frac{d\tau_i}{dt}}$$

$$=\cav{\frac{d\phi_i(z)}{dt}}+\sum_i\phi_i(z)\para{\tau_i\para{\overline{\ln W_i}-\cav{\overline{\ln W}}}+\frac{m_i-\tau_iM}{\eta}}$$

$$=\cav{\frac{d\phi_i(z)}{dt}}+\cav{\phi(z)\overline{\ln W}}-\cav\phi(z)\cav{\overline{\ln W}}+\frac{1}{\eta}\para{\cav{m\phi(z)}-M\cav\tau}$$

$$=\cav{\phi(z)\para{\ln W(z)-\overline{\ln W}}+\frac{m(z)-\phi(z)m}{n}}$$

$$+\cav{\phi(z)\overline{\ln W}}-\cav\phi(z)\cav{\overline{\ln W}}+\frac{1}{\eta}\para{\cav{m\phi(z)}-M\cav\tau}$$

$$=\cav{\phi(z)\ln W(z)}-\cav\phi(z)\cav{\overline{\ln W}}+\cav{\frac{m(z)}{n}}-\cav{\frac{\phi(z)m}{n}}+\cav{\frac{\phi(z)m}{\eta}}-\frac{M}{\eta}\cav\tau$$

## Letting $N=N(t)$

  * $N\dots$ the expected number of species within the community.
  * $\psi\dots$ the speciation rate of the community
  * $\epsilon\dots$ the (local) extinction rate of the community
  * $\omega\geq0\dots$ the species-level migration rate of the community
  * $\eta=\sum_{i=1}^\infty n_i\dots$ the total expected number of individuals within the community

### Conceptual issues

Since we're tracking $N$ we can't assume an infinite number of species in the community. Recall that $n_i$ represents the __expected__  number of individuals of species $x$. The actual number will surely be a non-negative integer. So there's no obvious contradiction between assuming a finite number of species and yet having $n_i>0$ for every $i$. 

One thing we will have to assume is that $\eta<\infty$ so that the sum $\sum n_i$ converges. This also requires $M<\infty$.

Note that since $i=1,2,\dots$ then $m_i>0$ represents rate of invasion if $n_i=0$.

We might be able to avoid a lot of this hassle if we simply track the density $\phi(z)$ of the trait $z$ for __all__ individuals in the community. We can assume species interact with one another based only on their trait value and not on their identity as a species.

### Dynamics of $\psi$

For now we should set $\psi\equiv0$.

### Dynamics of $\epsilon$

We can assume and ambient distribution of traits represented by the density $\Phi(z)$. We can assume that invaders will have traits drawn from this distribution. The probability of invasion is merely the probability that at least one invader leaves at least one offspring. Hence, this probability and therefore the rate of invasion will depend on the fitness of the invader.

### Dynamics of $N$

$$\frac{dN}{dt}=(\psi-\epsilon)N+\omega$$

### Unweighted average demographic dynamics across the community 

$$\frac{d\underline n}{dt}=\frac{d}{dt}\para{\frac{1}{N}\eta}$$

$$=\frac{1}{N^2}\para{N\para{\eta\cav{\overline{\ln W}}+M}-\eta\para{(\psi-\epsilon)N+\omega}}$$

$$=\underline n\cav{\overline{\ln W}}+\underline m-\eta\para{\frac{\psi-\epsilon}{N}+\frac{\omega}{N^2}}$$

No assumptions have been made about the mode of interaction between individuals. Then why should extinction increase the growth of the number of individuals while speciation and immigration reduces it? Note that as the number $N$ increases $\underline n$ will decrease assuming the $n_i$ remain constant. This accounts for what seemed pathological.

### Weighted average demographic dynamics across the community

$$\frac{d\cav n}{dt}=\frac{d}{dt}\sum_i\tau_in_i=\sum_i\para{\tau_i\frac{dn_i}{dt}+n_i\frac{d\tau_i}{dt}}$$

It appears this quantity will remain unchanged.

# Functionally structured communities

Here I ignore the identity of species and focus on the evolution of the distribution of traits across all individuals within the community. First I focus on the absence of functional structure by which I mean a single intra-interactive set of individuals. I will then develop the analogous results for a pair of interacting guilds.

## Single guild

### Primary assumptions

  * Every individual has the same trait and interactions are mediated entirely through the values of these pairs of traits.

### The Derivation

Assuming individuals with trait $x$ have the interaction distribution (or distribution of preference)

$$\iota(x,z)=\frac{1}{\sqrt{2\pi o^2}}\exp\para{-\frac{(\kappa-z)^2}{2o^2}}$$

we have a the normally distributed random variable $Z\sim\mathcal{N}(\kappa,o^2)$ that models the value of the trait with which this individual prefers to interact. We can assume everyone interacts with a random number of iid individuals. The fitness outcome for each interaction can be captured with 

$$W_B(x,z)=\frac{C}{\sqrt{2\pi\beta^2}}\exp\para{-\frac{(x-z-\delta)^2}{2\beta^2}}.$$

We can take this a step further and assume the $\kappa$, $\delta$, $o$, $\beta^2$, and $C$ are random variables to capture the effects of individual variability. However, assuming $\kappa$ and $\delta$ to be normally distributed around $\bar\kappa$ and $\bar\delta$ will not change the forms of the resulting expressions for the interaction distribution and the fitness function. They will just have increased variance. So I'll assume the $\kappa$ and $\delta$ are constant. Of course, relaxing these assumptions will allow us to investigate the evolution of the interaction distribution and fitness function. But for simplicity I will at first ignore these tantalizing venues.

Each interaction has an effect on the fitness of an individual. For an individual with phenotype $x$ that interacts with $K$ individuals with phenotypes $z_1,z_2,\dots,z_K$, we can define fitness for $x$ to be

$$W(x|z_1,\dots,z_K)\equiv\prod_{i=1}^{K}W(x|z_i).$$

If $K=0$ then the product is empty and by convention takes the value 1. This makes perfect sense when realizing that multiplying any number by 1 has no effect. We can now plug in the form of fitness suggested above to get

$$W(x|z_1,\dots,z_K)=\para{\frac{C}{\sqrt{2\pi\beta^2}}}^K\exp\para{-\sum_{i=1}^{K}\frac{(z_i+\delta-x)^2}{2\beta^2}}.$$

Before we move further to calculate the mean fitness for an individual with trait $x$, let's work out including the interaction distribution for one interaction. Above we have the traits $z_1,\dots,z_K$ written as a given. However, the value those traits take will depend on their distribution as well as the distribution of preference for the individual with trait $x$. Taking guidance from universal Darwinism and the Bayesian update algorithm in particular, we can find the distribution of $Z_x$, the random variable capturing the trait value encountered by an individual with trait $x$ after incorporating both the distribution of the trait in the community and interaction distribution of the trait $x$. This new distribution, denoted $\tilde\phi$, is calculated as

$$\tilde\phi(z)=\frac{\iota(x,z)\phi(z)}{\int\iota(x,y)\phi(y)dy}=\star.$$

Assuming

$$\phi(z)=\frac{1}{\sqrt{2\pi\sigma^2}}\exp\para{-\frac{(\bar z-z)^2}{2\sigma^2}},$$

then

$$\star=\frac{1}{\sqrt{2\pi\tilde\sigma^2}}\exp\para{-\frac{(z-\tilde z)^2}{2\tilde\sigma^2}}$$

with

$$\tilde z=\frac{o^2\bar z+\sigma^2\kappa}{o^2+\sigma^2}, \ \sigma^2=\frac{o^2\sigma^2}{o^2+\sigma^2}.$$


Given $\eta$ total individuals in the community, we can suppose $K\sim\mathrm{Bin}(\eta,p)$, with $p$ representing the proportion of the individuals in the community interacted with. We can calculate the expected fitness for an individual with phenotype $x$ given that it interacts with $K$ individuals as

$$W(x|K)=\int_\R\cdots\int_\R W_1(x|z_1,\dots,z_K)\tilde\phi(z_1)\cdots\tilde\phi(z_K)dz_1\cdots dz_K$$

$$=\para{\int_\R W(x|z)\tilde\phi(z)dz}^K=\para{\frac{C}{\sqrt{2\pi(\beta^2+\tilde\sigma^2)}}}^K\exp\para{-K\frac{(\tilde z+\delta-x)^2}{2(\beta^2+\tilde\sigma^2)}}.$$

Finally, to get the total expected fitness $W(x)$, we average over all possible values of $K$. However, since each component of fitness multiplies together to produce the total fitness, we shouldn't take an arithmetic average, we should take a geometric average. Doing so provides the following result

$$W(x)=\prod_{i=0}^\eta W(x|K=i)^{P(K=i)}=\para{\frac{C}{\sqrt{2\pi(\beta^2+\tilde\sigma^2)}}}^{p\eta}\exp\para{-p\eta\frac{(\tilde z+\delta-x)^2}{2(\beta^2+\tilde\sigma^2)}}$$


Then the mean fitness across individuals within the community (that is, ignoring the taxanomic structure of the community) is

$$\mathfrak{W}\equiv\int W(x)\phi(x)dx$$

$$=\para{\frac{C}{\sqrt{2\pi(\beta^2+\tilde\sigma^2)}}}^{p\eta}\sqrt{\frac{2\pi\frac{\beta^2+\tilde\sigma^2}{p\eta}}{2\pi\para{\frac{\beta^2+\tilde\sigma^2}{p\eta}+\sigma^2}}}\exp\para{-\frac{(\tilde z+\delta-\bar z)^2}{2\para{\frac{\beta^2+\tilde\sigma^2}{p\eta}+\sigma^2}}}$$

Similarly

$$\mathfrak{L}(W)\equiv\int\ln W(x)\phi(x)dx=p\eta\ln\para{\frac{C}{\sqrt{2\pi(\beta^2+\tilde\sigma^2)}}}
-p\eta\frac{(\tilde z+\delta+\bar z)^2+\sigma^2}{2(\beta^2+\tilde\sigma^2)}.$$

Assuming perfect heritability and clonal reproduction,

$$\frac{d\bar z}{dt}=p\eta\frac{\sigma^2}{\beta^2+\tilde\sigma^2}(\tilde z+\delta-\bar z)\para{1-\frac{o^2}{o^2+\sigma^2}}$$

$$=p\eta\frac{\sigma^2}{\beta^2+\tilde\sigma^2}\frac{\sigma^2}{o^2+\sigma^2}(\tilde z+\delta-\bar z)$$

$$=p\eta\frac{\sigma^2}{\beta^2+\tilde\sigma^2}\frac{\sigma^2}{o^2+\sigma^2}\para{\delta+\frac{\sigma^2}{o^2+\sigma^2}(\kappa-\bar z)}$$

If we assume $\beta^2,o^2\gg1$ so that $\beta^2+\sigma^2\approx\beta^2$ and $o^2+\sigma^2\approx o^2$, then

$$\frac{d\bar z}{dt}\approx p\eta\frac{\sigma^4}{\beta^2o^2}\para{\delta+\frac{\sigma^2}{o^2}(\kappa-\bar z)}$$

This assumption implies selection and preference are both weak. Ignoring the evolution of $\sigma^2$ we can define the strength of biotic selection as

$$B\equiv\frac{\sigma^2}{\beta^2}\geq0$$

and specialization as

$$\psi\equiv\frac{\sigma^2}{o^2}\geq0.$$

The above dynamics of the mean trait then simplify to

$$\frac{d\bar z}{dt}\approx p\eta\psi B\para{\delta+\psi(\kappa-\bar z)}.$$

This model can provide insight into why the mean trait of entire communities differ from one location to another. At equilibrium we have

$$\bar z^*=\frac{\delta}{\psi}+\kappa.$$

Then if $\bar z$ differs from one place to another, assuming all of the above, these differences would have to be accounted for by differences in the specialization ($\psi$), the optimal offset ($\delta$) and the preferred phenotype ($\kappa$).

This model also sets the stage for investigating the evolution of $\psi$, $\kappa$ and $\delta$ and also for incorporating demographic dynamics through $\eta$ and the evolution of $p$ which represents the proportion of individuals interacted with.
