---
title: "Variance response to genetic drift"
author: "Bob Week"
date: "5/8/2019"
output: pdf_document
---

Given our distribution of traits

$$\phi(x)=\frac{1}{\sqrt{2\pi G}}\exp\left(-\frac{(x-\bar x)^2}{2G}\right)$$

we can calculate the distribution of sample moments. In particular, given a sample $N_1,\dots,N_I$, we have

$$\bar X\equiv\frac{1}{I}\sum_iX_i\sim\mathcal{N}(\bar x, G/I)$$

and

$$\hat G\equiv\frac{1}{I}\sum_i(X_i-\bar X)^2\sim G\chi^2_{I-1}.$$

This implies $\mathbb{E}\hat G=G\frac{I-1}{I}$ and $\mathbb{V}\hat G=2G\frac{I-1}{I^2}$. Taking inspiration from these results, we wish to derive the evolution of $G$ under genetic drift and mutation. Mutation can be captured by

$$\frac{\partial\phi}{\partial t}=\frac{\mu I}{2}\frac{\partial^2\phi}{\partial x^2}$$

which is just the heat equation. Since we assume $\phi$ is normal with the above expression, this implies

$$\frac{dG}{dt}=\mu I.$$

We'll superimpose the effects of drift onto this base result. To do so in continuous time, we search for a natural diffusion process $Y_t$ such that $Y_t$ is $\chi^2$-distributed for each fixed $t$. The CIR model provides this as a special case and, in general, can be written

$$dG=a(b-G)dt+\sigma\sqrt{G}d\xi$$

for a standard Brownian motion $\xi$. A well estiblished result is, setting $c=\frac{2a}{(1-e^{-a})\sigma^2}$,

$$\mathbb{E}\left(\int_t^{t+1}dG\right)=\frac{\frac{4ab}{\sigma^2}+2cGe^{-a}}{2c}=2b(1-e^{-a})+Ge^{-a}$$

$$\mathbb{V}\left(\int_t^{t+1}dG\right)=\frac{2\left(\frac{4ab}{\sigma^2}+4cGe^{-a}\right)}{(2c)^2}=\frac{2b}{c}(1-e^{-a})+2G\frac{e^{-a}}{c}.$$

Returning to our results from above, by setting $\mathbb{E}\hat G=\mathbb{E}\left(\int_t^{t+1}dG\right)$ and $\mathbb{V}\hat G=\mathbb{V}\left(\int_t^{t+1}dG\right)$ we find

$$b=0, \ \ a=\ln I-\ln(I-1), \ \ \sigma^2=2[\ln I-\ln(I-1)].$$

Hence, with mutation, the SDE for $G$ becomes

$$dG=\Big(\mu I-[\ln I-\ln(I-1)]G\Big)dt+\sqrt{2[\ln I-\ln(I-1)]G}d\xi.$$


