---
title: "Harmonic Analysis 02-04-19"
description: |
date: "`r Sys.Date()`"
output: radix::radix_article
---

\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\<}{\left<}
\newcommand{\>}{\right>}
\newcommand{\ra}{\rightarrow}

$$P_N=\left\{\sum_{|n|\leq N}c_ne^{ixn}|c_n\in\C\right\}$$

- the set of all trig. polynomials of degree $\leq N$

$$S_N f=\sum_{|n|\leq N}\hat f(n)e^{ixn}\in P_N$$

In what follows, let $f\in L^2[-\pi,\pi)$.

- _Lemma (1)_: $f-S_Nf$ is orhtogonal to any polynomial in $P_N$. In particular, $f-S_Nf$ is orhtogonal to $S_Nf$.

- _Pythagorean identity_: If $f$ & $g$ are orth, then

$$\|f+g\|^2=\|f\|^2+\|g\|^2$$

- _Lemma (2)_: $\|f\|^2=\|f-S_Nf\|^2+\sum_{|n|\leq N}|\hat f(n)|^2$


- _Bessels ineq_: $\sum_{n\in\Z}|\hat f(n)|^2\leq\|f\|^2$

- _Best approx lemma_: For ea. $N\geq0$ and all $p\in P_N$

$$\|f-S_Nf\|\leq\|f-p\|$$

Equality holds iff $p=S_Nf$

_Proof_: Denote $e^{inx}$ by $e_n$. Let $p\in P_N$. Then $p=\sum_{|n|\leq N}c_ne_n$ where $c_n\in\C$.

$$f-p=f-\sum_{|n|\leq N}c_ne_n+S_Nf-S_Nf$$

$$=f-S_Nf+\sum(\hat f(n)-c_n)e_n$$

Note $\sum(\hat f(n)-c_n)e_n\in P_N$. Thus, by Lemma (1), $f-S_Nf$ is orth to $\sum(\hat f(n)-c_n)e_n$. Using the Pyth ident

$$\|f-p\|^2=\|f-S_Nf\|^2+\|\sum(\hat f(n)-c_n)e_n\|^2.$$

Thus, the claimed inequality holds. Now we must show the condition for equality is both necessary and sufficient. Since $p=S_Nf$ implies $c_n=\hat f(n)$ for each $|n|\leq N$, we have that this condition is sufficient. Similarly, if

$$\|\sum(\hat f(n)-c_n)e_n\|=0$$

then $\<\sum_{|n|\leq N}(\hat f(n)-c_n)e_n,\sum_{|l|\leq N}(\hat f(l)-c_l)e_l\>=0$. Since $\{e^{inx}\}$ is an orthonormal set, we can use linearity to expand the inner product to find

$$\sum_{|n|\leq N}|\hat f(n)-c_n|^2=0$$

which clearly implies $\hat f(n)=c_n$ for each $|n|\leq N$. This in turn implies $p=S_Nf$. $\square$

- Note: $p$ might depend on the orthonormal set chosen to represent the Fourier expansion.

- Remark: In all the results we have used the fact that $\{e_n=e^{inx}\}$ is orthonormal in $L^2[-\pi,\pi)$. All these results have counterparts for any orthonormal system $\{\psi_n\}_{n=1}^\infty\subset L^2[-\pi,\pi)$. The space $P_N$ is replaced by $W_N=\{f\in L^2|f=\sum_{n=1}^Na_n\psi_n\}$. Also $\hat f(n)$ wrt $\{\psi_n\}$ is $\<f,\psi_n\>$ instead $\<f,e_n\>$.

Our main goal is to prove

- _Mean sqr conv thm_: If $f\in L^2[-\pi,\pi)$ then

$$\int_{-\pi}^\pi|f(x)-S_Nf(x)|^2dx\ra0$$

as $N\ra\infty$. That is, the partial Fourier sums converge to $f$ in the $L^2$ sense. In terms of norm, we have

$$\|f-S_Nf\|\ra0$$

as $N\ra0$.

_Proof_: 

  1) First prove for cont functions. Let $g\in C[-\pi,\pi)$ Show that $\|g-S_Ng\|\ra0$ as $N\ra0$. Fix $\epsilon>0$. By Fej&eacute;r's thm, the Ces&aacute;ro sums $\sigma_Ng$ converge unif to $g$. That is, there is a $M\in\N$ s.t.

$$|g(x)-\sigma_Mg(x)|\leq\epsilon, \ \forall \ x\in[-\pi,\pi).$$

Hence

$$\|g-\sigma_Mg\|=\frac{1}{2\pi}\int_{-\pi}^\pi|g(x)-\sigma_Mg(x)|^2dx\epsilon^2.$$

Note that, for all $N\geq M$, $\sigma_Mg\in P_N$. Then, by the best approx lemma, we have

$$\|g-S_Ng\|\leq\|g-\sigma_Mg\|<\epsilon \ \forall \ N\geq M.$$

This implies that $\|g-S_Ng\|\ra0$ as $N\ra\infty$.

  2) Now prove for $f\in L^2[-\pi,\pi)$. We use the fact that continuous functions are dense in $L^2[-\pi,\pi)$. This means that for each $f\in L^2$ and $\epsilon>0$, there is a cont function $g$ s.t.
  
$$\|f-g\|\leq\epsilon.$$

For $g$ cont, we can find $M\in\N$ s.t. $\|g-S_Mg\|<\epsilon$. This all implies:

$$\|f-S_Mg\|\leq\|f-g\|+\|g-S_Mg\|\leq2\epsilon.$$

For $N\geq M$, $\|f-S_Nf\||leq\|f-S_Mg\|\leq2\epsilon$ by the best approx lemma. Thus, $\|f-S_Nf\|\ra0$ as $N\ra\infty$. $\square$
